apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pixlise-api
  description: |
    The executable package for the pixlise API.
  links:
    - title: Website
      url: https://pixlise.org
    - title: Documentation
      url: https://pixlise.gitbook.io/
  annotations:
    backstage.io/kubernetes-id: pixlise-api
    github.com/project-slug: pixlise/core/internal/pixlise-api
    backstage.io/techdocs-ref: dir:.
    sentry.io/project-slug: pixl-api
    argocd/app-name: backstage
spec:
  type: service
  owner: default/developers
  lifecycle: production
  dependsOn::
    - component:pixlise-api-packages
