apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: data-import
  description: |
    The data importer lambda for pixlise.
  links:
    - title: Website
      url: https://pixlise.org
    - title: Documentation
      url: https://pixlise.gitbook.io/
  annotations:
    github.com/project-slug: pixlise/core/internal/lambdas/data-import
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: default/developers
  lifecycle: production
