// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: diffraction-manual-msgs.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// requires(NONE)
type DiffractionPeakManualListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScanId string `protobuf:"bytes,1,opt,name=scanId,proto3" json:"scanId,omitempty"`
}

func (x *DiffractionPeakManualListReq) Reset() {
	*x = DiffractionPeakManualListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diffraction_manual_msgs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiffractionPeakManualListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffractionPeakManualListReq) ProtoMessage() {}

func (x *DiffractionPeakManualListReq) ProtoReflect() protoreflect.Message {
	mi := &file_diffraction_manual_msgs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffractionPeakManualListReq.ProtoReflect.Descriptor instead.
func (*DiffractionPeakManualListReq) Descriptor() ([]byte, []int) {
	return file_diffraction_manual_msgs_proto_rawDescGZIP(), []int{0}
}

func (x *DiffractionPeakManualListReq) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

type DiffractionPeakManualListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peaks map[string]*ManualDiffractionPeak `protobuf:"bytes,1,rep,name=peaks,proto3" json:"peaks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // id->ManualDiffractionPeak
}

func (x *DiffractionPeakManualListResp) Reset() {
	*x = DiffractionPeakManualListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diffraction_manual_msgs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiffractionPeakManualListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffractionPeakManualListResp) ProtoMessage() {}

func (x *DiffractionPeakManualListResp) ProtoReflect() protoreflect.Message {
	mi := &file_diffraction_manual_msgs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffractionPeakManualListResp.ProtoReflect.Descriptor instead.
func (*DiffractionPeakManualListResp) Descriptor() ([]byte, []int) {
	return file_diffraction_manual_msgs_proto_rawDescGZIP(), []int{1}
}

func (x *DiffractionPeakManualListResp) GetPeaks() map[string]*ManualDiffractionPeak {
	if x != nil {
		return x.Peaks
	}
	return nil
}

// requires(EDIT_DIFFRACTION)
type DiffractionPeakManualInsertReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScanId    string  `protobuf:"bytes,1,opt,name=scanId,proto3" json:"scanId,omitempty"`
	Pmc       int32   `protobuf:"varint,2,opt,name=pmc,proto3" json:"pmc,omitempty"`
	EnergykeV float32 `protobuf:"fixed32,3,opt,name=energykeV,proto3" json:"energykeV,omitempty"`
}

func (x *DiffractionPeakManualInsertReq) Reset() {
	*x = DiffractionPeakManualInsertReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diffraction_manual_msgs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiffractionPeakManualInsertReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffractionPeakManualInsertReq) ProtoMessage() {}

func (x *DiffractionPeakManualInsertReq) ProtoReflect() protoreflect.Message {
	mi := &file_diffraction_manual_msgs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffractionPeakManualInsertReq.ProtoReflect.Descriptor instead.
func (*DiffractionPeakManualInsertReq) Descriptor() ([]byte, []int) {
	return file_diffraction_manual_msgs_proto_rawDescGZIP(), []int{2}
}

func (x *DiffractionPeakManualInsertReq) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *DiffractionPeakManualInsertReq) GetPmc() int32 {
	if x != nil {
		return x.Pmc
	}
	return 0
}

func (x *DiffractionPeakManualInsertReq) GetEnergykeV() float32 {
	if x != nil {
		return x.EnergykeV
	}
	return 0
}

type DiffractionPeakManualInsertResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatedId string `protobuf:"bytes,1,opt,name=createdId,proto3" json:"createdId,omitempty"`
}

func (x *DiffractionPeakManualInsertResp) Reset() {
	*x = DiffractionPeakManualInsertResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diffraction_manual_msgs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiffractionPeakManualInsertResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffractionPeakManualInsertResp) ProtoMessage() {}

func (x *DiffractionPeakManualInsertResp) ProtoReflect() protoreflect.Message {
	mi := &file_diffraction_manual_msgs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffractionPeakManualInsertResp.ProtoReflect.Descriptor instead.
func (*DiffractionPeakManualInsertResp) Descriptor() ([]byte, []int) {
	return file_diffraction_manual_msgs_proto_rawDescGZIP(), []int{3}
}

func (x *DiffractionPeakManualInsertResp) GetCreatedId() string {
	if x != nil {
		return x.CreatedId
	}
	return ""
}

// requires(EDIT_DIFFRACTION)
type DiffractionPeakManualDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DiffractionPeakManualDeleteReq) Reset() {
	*x = DiffractionPeakManualDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diffraction_manual_msgs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiffractionPeakManualDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffractionPeakManualDeleteReq) ProtoMessage() {}

func (x *DiffractionPeakManualDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_diffraction_manual_msgs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffractionPeakManualDeleteReq.ProtoReflect.Descriptor instead.
func (*DiffractionPeakManualDeleteReq) Descriptor() ([]byte, []int) {
	return file_diffraction_manual_msgs_proto_rawDescGZIP(), []int{4}
}

func (x *DiffractionPeakManualDeleteReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DiffractionPeakManualDeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DiffractionPeakManualDeleteResp) Reset() {
	*x = DiffractionPeakManualDeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diffraction_manual_msgs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiffractionPeakManualDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffractionPeakManualDeleteResp) ProtoMessage() {}

func (x *DiffractionPeakManualDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_diffraction_manual_msgs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffractionPeakManualDeleteResp.ProtoReflect.Descriptor instead.
func (*DiffractionPeakManualDeleteResp) Descriptor() ([]byte, []int) {
	return file_diffraction_manual_msgs_proto_rawDescGZIP(), []int{5}
}

var File_diffraction_manual_msgs_proto protoreflect.FileDescriptor

var file_diffraction_manual_msgs_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x64, 0x69, 0x66, 0x66, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x6d, 0x61,
	0x6e, 0x75, 0x61, 0x6c, 0x2d, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x16, 0x64, 0x69, 0x66, 0x66, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x1c, 0x44, 0x69, 0x66, 0x66, 0x72,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x65, 0x61, 0x6b, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x61, 0x6e, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x61, 0x6e, 0x49, 0x64, 0x22,
	0xb2, 0x01, 0x0a, 0x1d, 0x44, 0x69, 0x66, 0x66, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50,
	0x65, 0x61, 0x6b, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x3f, 0x0a, 0x05, 0x70, 0x65, 0x61, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x29, 0x2e, 0x44, 0x69, 0x66, 0x66, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x65,
	0x61, 0x6b, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x2e, 0x50, 0x65, 0x61, 0x6b, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x70, 0x65, 0x61,
	0x6b, 0x73, 0x1a, 0x50, 0x0a, 0x0a, 0x50, 0x65, 0x61, 0x6b, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x44, 0x69, 0x66, 0x66, 0x72, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x65, 0x61, 0x6b, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x68, 0x0a, 0x1e, 0x44, 0x69, 0x66, 0x66, 0x72, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x50, 0x65, 0x61, 0x6b, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x49, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x61, 0x6e, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x70, 0x6d, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x6d, 0x63,
	0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x6b, 0x65, 0x56, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x09, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x6b, 0x65, 0x56, 0x22, 0x3f,
	0x0a, 0x1f, 0x44, 0x69, 0x66, 0x66, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x65, 0x61,
	0x6b, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x49, 0x64, 0x22,
	0x30, 0x0a, 0x1e, 0x44, 0x69, 0x66, 0x66, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x65,
	0x61, 0x6b, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x21, 0x0a, 0x1f, 0x44, 0x69, 0x66, 0x66, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x50, 0x65, 0x61, 0x6b, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_diffraction_manual_msgs_proto_rawDescOnce sync.Once
	file_diffraction_manual_msgs_proto_rawDescData = file_diffraction_manual_msgs_proto_rawDesc
)

func file_diffraction_manual_msgs_proto_rawDescGZIP() []byte {
	file_diffraction_manual_msgs_proto_rawDescOnce.Do(func() {
		file_diffraction_manual_msgs_proto_rawDescData = protoimpl.X.CompressGZIP(file_diffraction_manual_msgs_proto_rawDescData)
	})
	return file_diffraction_manual_msgs_proto_rawDescData
}

var file_diffraction_manual_msgs_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_diffraction_manual_msgs_proto_goTypes = []interface{}{
	(*DiffractionPeakManualListReq)(nil),    // 0: DiffractionPeakManualListReq
	(*DiffractionPeakManualListResp)(nil),   // 1: DiffractionPeakManualListResp
	(*DiffractionPeakManualInsertReq)(nil),  // 2: DiffractionPeakManualInsertReq
	(*DiffractionPeakManualInsertResp)(nil), // 3: DiffractionPeakManualInsertResp
	(*DiffractionPeakManualDeleteReq)(nil),  // 4: DiffractionPeakManualDeleteReq
	(*DiffractionPeakManualDeleteResp)(nil), // 5: DiffractionPeakManualDeleteResp
	nil,                                     // 6: DiffractionPeakManualListResp.PeaksEntry
	(*ManualDiffractionPeak)(nil),           // 7: ManualDiffractionPeak
}
var file_diffraction_manual_msgs_proto_depIdxs = []int32{
	6, // 0: DiffractionPeakManualListResp.peaks:type_name -> DiffractionPeakManualListResp.PeaksEntry
	7, // 1: DiffractionPeakManualListResp.PeaksEntry.value:type_name -> ManualDiffractionPeak
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_diffraction_manual_msgs_proto_init() }
func file_diffraction_manual_msgs_proto_init() {
	if File_diffraction_manual_msgs_proto != nil {
		return
	}
	file_diffraction_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_diffraction_manual_msgs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiffractionPeakManualListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diffraction_manual_msgs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiffractionPeakManualListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diffraction_manual_msgs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiffractionPeakManualInsertReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diffraction_manual_msgs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiffractionPeakManualInsertResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diffraction_manual_msgs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiffractionPeakManualDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diffraction_manual_msgs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiffractionPeakManualDeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_diffraction_manual_msgs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_diffraction_manual_msgs_proto_goTypes,
		DependencyIndexes: file_diffraction_manual_msgs_proto_depIdxs,
		MessageInfos:      file_diffraction_manual_msgs_proto_msgTypes,
	}.Build()
	File_diffraction_manual_msgs_proto = out.File
	file_diffraction_manual_msgs_proto_rawDesc = nil
	file_diffraction_manual_msgs_proto_goTypes = nil
	file_diffraction_manual_msgs_proto_depIdxs = nil
}
