// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: expression-group-msgs.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TODO: Paginate?
// requires(NONE)
type ExpressionGroupListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchParams  *SearchParams          `protobuf:"bytes,1,opt,name=searchParams,proto3" json:"searchParams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpressionGroupListReq) Reset() {
	*x = ExpressionGroupListReq{}
	mi := &file_expression_group_msgs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpressionGroupListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressionGroupListReq) ProtoMessage() {}

func (x *ExpressionGroupListReq) ProtoReflect() protoreflect.Message {
	mi := &file_expression_group_msgs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressionGroupListReq.ProtoReflect.Descriptor instead.
func (*ExpressionGroupListReq) Descriptor() ([]byte, []int) {
	return file_expression_group_msgs_proto_rawDescGZIP(), []int{0}
}

func (x *ExpressionGroupListReq) GetSearchParams() *SearchParams {
	if x != nil {
		return x.SearchParams
	}
	return nil
}

type ExpressionGroupListResp struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Groups        map[string]*ExpressionGroup `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpressionGroupListResp) Reset() {
	*x = ExpressionGroupListResp{}
	mi := &file_expression_group_msgs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpressionGroupListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressionGroupListResp) ProtoMessage() {}

func (x *ExpressionGroupListResp) ProtoReflect() protoreflect.Message {
	mi := &file_expression_group_msgs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressionGroupListResp.ProtoReflect.Descriptor instead.
func (*ExpressionGroupListResp) Descriptor() ([]byte, []int) {
	return file_expression_group_msgs_proto_rawDescGZIP(), []int{1}
}

func (x *ExpressionGroupListResp) GetGroups() map[string]*ExpressionGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

// requires(NONE)
type ExpressionGroupGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpressionGroupGetReq) Reset() {
	*x = ExpressionGroupGetReq{}
	mi := &file_expression_group_msgs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpressionGroupGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressionGroupGetReq) ProtoMessage() {}

func (x *ExpressionGroupGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_expression_group_msgs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressionGroupGetReq.ProtoReflect.Descriptor instead.
func (*ExpressionGroupGetReq) Descriptor() ([]byte, []int) {
	return file_expression_group_msgs_proto_rawDescGZIP(), []int{2}
}

func (x *ExpressionGroupGetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ExpressionGroupGetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *ExpressionGroup       `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpressionGroupGetResp) Reset() {
	*x = ExpressionGroupGetResp{}
	mi := &file_expression_group_msgs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpressionGroupGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressionGroupGetResp) ProtoMessage() {}

func (x *ExpressionGroupGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_expression_group_msgs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressionGroupGetResp.ProtoReflect.Descriptor instead.
func (*ExpressionGroupGetResp) Descriptor() ([]byte, []int) {
	return file_expression_group_msgs_proto_rawDescGZIP(), []int{3}
}

func (x *ExpressionGroupGetResp) GetGroup() *ExpressionGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

// If id is blank, assume its new and generate an ID to return, otherwise update & return same one
// requires(EDIT_EXPRESSION_GROUP)
type ExpressionGroupWriteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *ExpressionGroup       `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpressionGroupWriteReq) Reset() {
	*x = ExpressionGroupWriteReq{}
	mi := &file_expression_group_msgs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpressionGroupWriteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressionGroupWriteReq) ProtoMessage() {}

func (x *ExpressionGroupWriteReq) ProtoReflect() protoreflect.Message {
	mi := &file_expression_group_msgs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressionGroupWriteReq.ProtoReflect.Descriptor instead.
func (*ExpressionGroupWriteReq) Descriptor() ([]byte, []int) {
	return file_expression_group_msgs_proto_rawDescGZIP(), []int{4}
}

func (x *ExpressionGroupWriteReq) GetGroup() *ExpressionGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

type ExpressionGroupWriteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *ExpressionGroup       `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpressionGroupWriteResp) Reset() {
	*x = ExpressionGroupWriteResp{}
	mi := &file_expression_group_msgs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpressionGroupWriteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressionGroupWriteResp) ProtoMessage() {}

func (x *ExpressionGroupWriteResp) ProtoReflect() protoreflect.Message {
	mi := &file_expression_group_msgs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressionGroupWriteResp.ProtoReflect.Descriptor instead.
func (*ExpressionGroupWriteResp) Descriptor() ([]byte, []int) {
	return file_expression_group_msgs_proto_rawDescGZIP(), []int{5}
}

func (x *ExpressionGroupWriteResp) GetGroup() *ExpressionGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

// requires(EDIT_EXPRESSION_GROUP)
type ExpressionGroupDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpressionGroupDeleteReq) Reset() {
	*x = ExpressionGroupDeleteReq{}
	mi := &file_expression_group_msgs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpressionGroupDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressionGroupDeleteReq) ProtoMessage() {}

func (x *ExpressionGroupDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_expression_group_msgs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressionGroupDeleteReq.ProtoReflect.Descriptor instead.
func (*ExpressionGroupDeleteReq) Descriptor() ([]byte, []int) {
	return file_expression_group_msgs_proto_rawDescGZIP(), []int{6}
}

func (x *ExpressionGroupDeleteReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ExpressionGroupDeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpressionGroupDeleteResp) Reset() {
	*x = ExpressionGroupDeleteResp{}
	mi := &file_expression_group_msgs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpressionGroupDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressionGroupDeleteResp) ProtoMessage() {}

func (x *ExpressionGroupDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_expression_group_msgs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressionGroupDeleteResp.ProtoReflect.Descriptor instead.
func (*ExpressionGroupDeleteResp) Descriptor() ([]byte, []int) {
	return file_expression_group_msgs_proto_rawDescGZIP(), []int{7}
}

var File_expression_group_msgs_proto protoreflect.FileDescriptor

const file_expression_group_msgs_proto_rawDesc = "" +
	"\n" +
	"\x1bexpression-group-msgs.proto\x1a\x16expression-group.proto\x1a\x13search-params.proto\"K\n" +
	"\x16ExpressionGroupListReq\x121\n" +
	"\fsearchParams\x18\x01 \x01(\v2\r.SearchParamsR\fsearchParams\"\xa4\x01\n" +
	"\x17ExpressionGroupListResp\x12<\n" +
	"\x06groups\x18\x01 \x03(\v2$.ExpressionGroupListResp.GroupsEntryR\x06groups\x1aK\n" +
	"\vGroupsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.ExpressionGroupR\x05value:\x028\x01\"'\n" +
	"\x15ExpressionGroupGetReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x16ExpressionGroupGetResp\x12&\n" +
	"\x05group\x18\x01 \x01(\v2\x10.ExpressionGroupR\x05group\"A\n" +
	"\x17ExpressionGroupWriteReq\x12&\n" +
	"\x05group\x18\x01 \x01(\v2\x10.ExpressionGroupR\x05group\"B\n" +
	"\x18ExpressionGroupWriteResp\x12&\n" +
	"\x05group\x18\x01 \x01(\v2\x10.ExpressionGroupR\x05group\"*\n" +
	"\x18ExpressionGroupDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1b\n" +
	"\x19ExpressionGroupDeleteRespB\n" +
	"Z\b.;protosb\x06proto3"

var (
	file_expression_group_msgs_proto_rawDescOnce sync.Once
	file_expression_group_msgs_proto_rawDescData []byte
)

func file_expression_group_msgs_proto_rawDescGZIP() []byte {
	file_expression_group_msgs_proto_rawDescOnce.Do(func() {
		file_expression_group_msgs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_expression_group_msgs_proto_rawDesc), len(file_expression_group_msgs_proto_rawDesc)))
	})
	return file_expression_group_msgs_proto_rawDescData
}

var file_expression_group_msgs_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_expression_group_msgs_proto_goTypes = []any{
	(*ExpressionGroupListReq)(nil),    // 0: ExpressionGroupListReq
	(*ExpressionGroupListResp)(nil),   // 1: ExpressionGroupListResp
	(*ExpressionGroupGetReq)(nil),     // 2: ExpressionGroupGetReq
	(*ExpressionGroupGetResp)(nil),    // 3: ExpressionGroupGetResp
	(*ExpressionGroupWriteReq)(nil),   // 4: ExpressionGroupWriteReq
	(*ExpressionGroupWriteResp)(nil),  // 5: ExpressionGroupWriteResp
	(*ExpressionGroupDeleteReq)(nil),  // 6: ExpressionGroupDeleteReq
	(*ExpressionGroupDeleteResp)(nil), // 7: ExpressionGroupDeleteResp
	nil,                               // 8: ExpressionGroupListResp.GroupsEntry
	(*SearchParams)(nil),              // 9: SearchParams
	(*ExpressionGroup)(nil),           // 10: ExpressionGroup
}
var file_expression_group_msgs_proto_depIdxs = []int32{
	9,  // 0: ExpressionGroupListReq.searchParams:type_name -> SearchParams
	8,  // 1: ExpressionGroupListResp.groups:type_name -> ExpressionGroupListResp.GroupsEntry
	10, // 2: ExpressionGroupGetResp.group:type_name -> ExpressionGroup
	10, // 3: ExpressionGroupWriteReq.group:type_name -> ExpressionGroup
	10, // 4: ExpressionGroupWriteResp.group:type_name -> ExpressionGroup
	10, // 5: ExpressionGroupListResp.GroupsEntry.value:type_name -> ExpressionGroup
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_expression_group_msgs_proto_init() }
func file_expression_group_msgs_proto_init() {
	if File_expression_group_msgs_proto != nil {
		return
	}
	file_expression_group_proto_init()
	file_search_params_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_expression_group_msgs_proto_rawDesc), len(file_expression_group_msgs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_expression_group_msgs_proto_goTypes,
		DependencyIndexes: file_expression_group_msgs_proto_depIdxs,
		MessageInfos:      file_expression_group_msgs_proto_msgTypes,
	}.Build()
	File_expression_group_msgs_proto = out.File
	file_expression_group_msgs_proto_goTypes = nil
	file_expression_group_msgs_proto_depIdxs = nil
}
