// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: expression-calculate.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataUnit int32

const (
	DataUnit_UNIT_DEFAULT DataUnit = 0 // Doubles as unknown, see https://protobuf.dev/programming-guides/dos-donts/
	DataUnit_UNIT_MMOL    DataUnit = 1
	DataUnit_UNIT_PPM     DataUnit = 2
)

// Enum value maps for DataUnit.
var (
	DataUnit_name = map[int32]string{
		0: "UNIT_DEFAULT",
		1: "UNIT_MMOL",
		2: "UNIT_PPM",
	}
	DataUnit_value = map[string]int32{
		"UNIT_DEFAULT": 0,
		"UNIT_MMOL":    1,
		"UNIT_PPM":     2,
	}
)

func (x DataUnit) Enum() *DataUnit {
	p := new(DataUnit)
	*p = x
	return p
}

func (x DataUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_expression_calculate_proto_enumTypes[0].Descriptor()
}

func (DataUnit) Type() protoreflect.EnumType {
	return &file_expression_calculate_proto_enumTypes[0]
}

func (x DataUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataUnit.Descriptor instead.
func (DataUnit) EnumDescriptor() ([]byte, []int) {
	return file_expression_calculate_proto_rawDescGZIP(), []int{0}
}

// Requesting a single expression to be run
type DataSourceParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScanId       string   `protobuf:"bytes,1,opt,name=scanId,proto3" json:"scanId,omitempty"`
	QuantId      string   `protobuf:"bytes,2,opt,name=quantId,proto3" json:"quantId,omitempty"`
	ExpressionId string   `protobuf:"bytes,3,opt,name=expressionId,proto3" json:"expressionId,omitempty"`
	RoiId        string   `protobuf:"bytes,4,opt,name=roiId,proto3" json:"roiId,omitempty"`
	Units        DataUnit `protobuf:"varint,5,opt,name=units,proto3,enum=DataUnit" json:"units,omitempty"`
}

func (x *DataSourceParams) Reset() {
	*x = DataSourceParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expression_calculate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataSourceParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSourceParams) ProtoMessage() {}

func (x *DataSourceParams) ProtoReflect() protoreflect.Message {
	mi := &file_expression_calculate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSourceParams.ProtoReflect.Descriptor instead.
func (*DataSourceParams) Descriptor() ([]byte, []int) {
	return file_expression_calculate_proto_rawDescGZIP(), []int{0}
}

func (x *DataSourceParams) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *DataSourceParams) GetQuantId() string {
	if x != nil {
		return x.QuantId
	}
	return ""
}

func (x *DataSourceParams) GetExpressionId() string {
	if x != nil {
		return x.ExpressionId
	}
	return ""
}

func (x *DataSourceParams) GetRoiId() string {
	if x != nil {
		return x.RoiId
	}
	return ""
}

func (x *DataSourceParams) GetUnits() DataUnit {
	if x != nil {
		return x.Units
	}
	return DataUnit_UNIT_DEFAULT
}

// Grouped results of expressions having run
type RegionDataResults struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueryResults []*RegionDataResultItem `protobuf:"bytes,1,rep,name=queryResults,proto3" json:"queryResults,omitempty"`
	Error        string                  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *RegionDataResults) Reset() {
	*x = RegionDataResults{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expression_calculate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionDataResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionDataResults) ProtoMessage() {}

func (x *RegionDataResults) ProtoReflect() protoreflect.Message {
	mi := &file_expression_calculate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionDataResults.ProtoReflect.Descriptor instead.
func (*RegionDataResults) Descriptor() ([]byte, []int) {
	return file_expression_calculate_proto_rawDescGZIP(), []int{1}
}

func (x *RegionDataResults) GetQueryResults() []*RegionDataResultItem {
	if x != nil {
		return x.QueryResults
	}
	return nil
}

func (x *RegionDataResults) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Complete result of running an individual expression, output is in exprResult but we also receive some meta-data
// for free because it was queried/used in the expression run, and we get the query structure back too.
type RegionDataResultItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExprResult *MemDataQueryResult `protobuf:"bytes,1,opt,name=exprResult,proto3" json:"exprResult,omitempty"`
	Error      string              `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Warning    string              `protobuf:"bytes,3,opt,name=warning,proto3" json:"warning,omitempty"`
	Expression *DataExpression     `protobuf:"bytes,4,opt,name=expression,proto3" json:"expression,omitempty"` // NOTE: Is this redundant??? There's also the same field in DataQueryResult
	//RegionSettings region = 5; // NOTE: Is this redundant??? There's also the same field in DataQueryResult
	Query      *DataSourceParams `protobuf:"bytes,6,opt,name=query,proto3" json:"query,omitempty"`
	IsPMCTable bool              `protobuf:"varint,7,opt,name=isPMCTable,proto3" json:"isPMCTable,omitempty"` // NOTE: Is this redundant??? There's also the same field in DataQueryResult
}

func (x *RegionDataResultItem) Reset() {
	*x = RegionDataResultItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expression_calculate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionDataResultItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionDataResultItem) ProtoMessage() {}

func (x *RegionDataResultItem) ProtoReflect() protoreflect.Message {
	mi := &file_expression_calculate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionDataResultItem.ProtoReflect.Descriptor instead.
func (*RegionDataResultItem) Descriptor() ([]byte, []int) {
	return file_expression_calculate_proto_rawDescGZIP(), []int{2}
}

func (x *RegionDataResultItem) GetExprResult() *MemDataQueryResult {
	if x != nil {
		return x.ExprResult
	}
	return nil
}

func (x *RegionDataResultItem) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RegionDataResultItem) GetWarning() string {
	if x != nil {
		return x.Warning
	}
	return ""
}

func (x *RegionDataResultItem) GetExpression() *DataExpression {
	if x != nil {
		return x.Expression
	}
	return nil
}

func (x *RegionDataResultItem) GetQuery() *DataSourceParams {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *RegionDataResultItem) GetIsPMCTable() bool {
	if x != nil {
		return x.IsPMCTable
	}
	return false
}

var File_expression_calculate_proto protoreflect.FileDescriptor

var file_expression_calculate_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2d, 0x63, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x65, 0x78,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x11, 0x6d, 0x65, 0x6d, 0x6f, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x9f, 0x01, 0x0a, 0x10, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x61, 0x6e, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x61, 0x6e, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x78, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x72, 0x6f, 0x69, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f,
	0x69, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x05, 0x75,
	0x6e, 0x69, 0x74, 0x73, 0x22, 0x64, 0x0a, 0x11, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x39, 0x0a, 0x0c, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0c, 0x71, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xf5, 0x01, 0x0a, 0x14, 0x52,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x33, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4d, 0x65, 0x6d, 0x44, 0x61, 0x74,
	0x61, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0a, 0x65, 0x78,
	0x70, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x77, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x77, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x2f, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x65,
	0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x73, 0x50, 0x4d, 0x43, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x50, 0x4d, 0x43, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x2a, 0x39, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x10,
	0x0a, 0x0c, 0x55, 0x4e, 0x49, 0x54, 0x5f, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00,
	0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e, 0x49, 0x54, 0x5f, 0x4d, 0x4d, 0x4f, 0x4c, 0x10, 0x01, 0x12,
	0x0c, 0x0a, 0x08, 0x55, 0x4e, 0x49, 0x54, 0x5f, 0x50, 0x50, 0x4d, 0x10, 0x02, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_expression_calculate_proto_rawDescOnce sync.Once
	file_expression_calculate_proto_rawDescData = file_expression_calculate_proto_rawDesc
)

func file_expression_calculate_proto_rawDescGZIP() []byte {
	file_expression_calculate_proto_rawDescOnce.Do(func() {
		file_expression_calculate_proto_rawDescData = protoimpl.X.CompressGZIP(file_expression_calculate_proto_rawDescData)
	})
	return file_expression_calculate_proto_rawDescData
}

var file_expression_calculate_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_expression_calculate_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_expression_calculate_proto_goTypes = []interface{}{
	(DataUnit)(0),                // 0: DataUnit
	(*DataSourceParams)(nil),     // 1: DataSourceParams
	(*RegionDataResults)(nil),    // 2: RegionDataResults
	(*RegionDataResultItem)(nil), // 3: RegionDataResultItem
	(*MemDataQueryResult)(nil),   // 4: MemDataQueryResult
	(*DataExpression)(nil),       // 5: DataExpression
}
var file_expression_calculate_proto_depIdxs = []int32{
	0, // 0: DataSourceParams.units:type_name -> DataUnit
	3, // 1: RegionDataResults.queryResults:type_name -> RegionDataResultItem
	4, // 2: RegionDataResultItem.exprResult:type_name -> MemDataQueryResult
	5, // 3: RegionDataResultItem.expression:type_name -> DataExpression
	1, // 4: RegionDataResultItem.query:type_name -> DataSourceParams
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_expression_calculate_proto_init() }
func file_expression_calculate_proto_init() {
	if File_expression_calculate_proto != nil {
		return
	}
	file_expressions_proto_init()
	file_memoisation_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_expression_calculate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataSourceParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expression_calculate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionDataResults); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expression_calculate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionDataResultItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_expression_calculate_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_expression_calculate_proto_goTypes,
		DependencyIndexes: file_expression_calculate_proto_depIdxs,
		EnumInfos:         file_expression_calculate_proto_enumTypes,
		MessageInfos:      file_expression_calculate_proto_msgTypes,
	}.Build()
	File_expression_calculate_proto = out.File
	file_expression_calculate_proto_rawDesc = nil
	file_expression_calculate_proto_goTypes = nil
	file_expression_calculate_proto_depIdxs = nil
}
