// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: expressions.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataExpression struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	Id               string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`  
	Name             string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SourceCode       string                   `protobuf:"bytes,3,opt,name=sourceCode,proto3" json:"sourceCode,omitempty"`
	SourceLanguage   string                   `protobuf:"bytes,4,opt,name=sourceLanguage,proto3" json:"sourceLanguage,omitempty"`
	Comments         string                   `protobuf:"bytes,5,opt,name=comments,proto3" json:"comments,omitempty"`
	Tags             []string                 `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	ModuleReferences []*ModuleReference       `protobuf:"bytes,7,rep,name=moduleReferences,proto3" json:"moduleReferences,omitempty"`
	RecentExecStats  *DataExpressionExecStats `protobuf:"bytes,8,opt,name=recentExecStats,proto3" json:"recentExecStats,omitempty"`
	ModifiedUnixSec  uint32                   `protobuf:"varint,9,opt,name=modifiedUnixSec,proto3" json:"modifiedUnixSec,omitempty"`
	// Only sent out by API, not stored in DB this way
	Owner         *OwnershipSummary `protobuf:"bytes,10,opt,name=owner,proto3" json:"owner,omitempty" bson:"-"`  
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataExpression) Reset() {
	*x = DataExpression{}
	mi := &file_expressions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataExpression) ProtoMessage() {}

func (x *DataExpression) ProtoReflect() protoreflect.Message {
	mi := &file_expressions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataExpression.ProtoReflect.Descriptor instead.
func (*DataExpression) Descriptor() ([]byte, []int) {
	return file_expressions_proto_rawDescGZIP(), []int{0}
}

func (x *DataExpression) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataExpression) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataExpression) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

func (x *DataExpression) GetSourceLanguage() string {
	if x != nil {
		return x.SourceLanguage
	}
	return ""
}

func (x *DataExpression) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

func (x *DataExpression) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DataExpression) GetModuleReferences() []*ModuleReference {
	if x != nil {
		return x.ModuleReferences
	}
	return nil
}

func (x *DataExpression) GetRecentExecStats() *DataExpressionExecStats {
	if x != nil {
		return x.RecentExecStats
	}
	return nil
}

func (x *DataExpression) GetModifiedUnixSec() uint32 {
	if x != nil {
		return x.ModifiedUnixSec
	}
	return 0
}

func (x *DataExpression) GetOwner() *OwnershipSummary {
	if x != nil {
		return x.Owner
	}
	return nil
}

type ModuleReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=moduleId,proto3" json:"moduleId,omitempty"`
	Version       *SemanticVersion       `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleReference) Reset() {
	*x = ModuleReference{}
	mi := &file_expressions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleReference) ProtoMessage() {}

func (x *ModuleReference) ProtoReflect() protoreflect.Message {
	mi := &file_expressions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleReference.ProtoReflect.Descriptor instead.
func (*ModuleReference) Descriptor() ([]byte, []int) {
	return file_expressions_proto_rawDescGZIP(), []int{1}
}

func (x *ModuleReference) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *ModuleReference) GetVersion() *SemanticVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

type DataExpressionExecStats struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DataRequired        []string               `protobuf:"bytes,1,rep,name=dataRequired,proto3" json:"dataRequired,omitempty"`
	RuntimeMsPer1000Pts float32                `protobuf:"fixed32,2,opt,name=runtimeMsPer1000Pts,proto3" json:"runtimeMsPer1000Pts,omitempty" bson:"runtimeMsPer1000Pts,truncate"`  
	TimeStampUnixSec    uint32                 `protobuf:"varint,3,opt,name=timeStampUnixSec,proto3" json:"timeStampUnixSec,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DataExpressionExecStats) Reset() {
	*x = DataExpressionExecStats{}
	mi := &file_expressions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataExpressionExecStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataExpressionExecStats) ProtoMessage() {}

func (x *DataExpressionExecStats) ProtoReflect() protoreflect.Message {
	mi := &file_expressions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataExpressionExecStats.ProtoReflect.Descriptor instead.
func (*DataExpressionExecStats) Descriptor() ([]byte, []int) {
	return file_expressions_proto_rawDescGZIP(), []int{2}
}

func (x *DataExpressionExecStats) GetDataRequired() []string {
	if x != nil {
		return x.DataRequired
	}
	return nil
}

func (x *DataExpressionExecStats) GetRuntimeMsPer1000Pts() float32 {
	if x != nil {
		return x.RuntimeMsPer1000Pts
	}
	return 0
}

func (x *DataExpressionExecStats) GetTimeStampUnixSec() uint32 {
	if x != nil {
		return x.TimeStampUnixSec
	}
	return 0
}

type ExpressionResultItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      int32                  `protobuf:"varint,1,opt,name=location,proto3" json:"location,omitempty"`
	Values        []float32              `protobuf:"fixed32,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpressionResultItem) Reset() {
	*x = ExpressionResultItem{}
	mi := &file_expressions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpressionResultItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressionResultItem) ProtoMessage() {}

func (x *ExpressionResultItem) ProtoReflect() protoreflect.Message {
	mi := &file_expressions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressionResultItem.ProtoReflect.Descriptor instead.
func (*ExpressionResultItem) Descriptor() ([]byte, []int) {
	return file_expressions_proto_rawDescGZIP(), []int{3}
}

func (x *ExpressionResultItem) GetLocation() int32 {
	if x != nil {
		return x.Location
	}
	return 0
}

func (x *ExpressionResultItem) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type ExpressionDisplaySettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`  
	ColourRamp    string                 `protobuf:"bytes,2,opt,name=colourRamp,proto3" json:"colourRamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpressionDisplaySettings) Reset() {
	*x = ExpressionDisplaySettings{}
	mi := &file_expressions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpressionDisplaySettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressionDisplaySettings) ProtoMessage() {}

func (x *ExpressionDisplaySettings) ProtoReflect() protoreflect.Message {
	mi := &file_expressions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressionDisplaySettings.ProtoReflect.Descriptor instead.
func (*ExpressionDisplaySettings) Descriptor() ([]byte, []int) {
	return file_expressions_proto_rawDescGZIP(), []int{4}
}

func (x *ExpressionDisplaySettings) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExpressionDisplaySettings) GetColourRamp() string {
	if x != nil {
		return x.ColourRamp
	}
	return ""
}

var File_expressions_proto protoreflect.FileDescriptor

const file_expressions_proto_rawDesc = "" +
	"\n" +
	"\x11expressions.proto\x1a\x16ownership-access.proto\x1a\rversion.proto\"\x81\x03\n" +
	"\x0eDataExpression\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"sourceCode\x18\x03 \x01(\tR\n" +
	"sourceCode\x12&\n" +
	"\x0esourceLanguage\x18\x04 \x01(\tR\x0esourceLanguage\x12\x1a\n" +
	"\bcomments\x18\x05 \x01(\tR\bcomments\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12<\n" +
	"\x10moduleReferences\x18\a \x03(\v2\x10.ModuleReferenceR\x10moduleReferences\x12B\n" +
	"\x0frecentExecStats\x18\b \x01(\v2\x18.DataExpressionExecStatsR\x0frecentExecStats\x12(\n" +
	"\x0fmodifiedUnixSec\x18\t \x01(\rR\x0fmodifiedUnixSec\x12'\n" +
	"\x05owner\x18\n" +
	" \x01(\v2\x11.OwnershipSummaryR\x05owner\"Y\n" +
	"\x0fModuleReference\x12\x1a\n" +
	"\bmoduleId\x18\x01 \x01(\tR\bmoduleId\x12*\n" +
	"\aversion\x18\x02 \x01(\v2\x10.SemanticVersionR\aversion\"\x9b\x01\n" +
	"\x17DataExpressionExecStats\x12\"\n" +
	"\fdataRequired\x18\x01 \x03(\tR\fdataRequired\x120\n" +
	"\x13runtimeMsPer1000Pts\x18\x02 \x01(\x02R\x13runtimeMsPer1000Pts\x12*\n" +
	"\x10timeStampUnixSec\x18\x03 \x01(\rR\x10timeStampUnixSec\"J\n" +
	"\x14ExpressionResultItem\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\x05R\blocation\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x02R\x06values\"K\n" +
	"\x19ExpressionDisplaySettings\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"colourRamp\x18\x02 \x01(\tR\n" +
	"colourRampB\n" +
	"Z\b.;protosb\x06proto3"

var (
	file_expressions_proto_rawDescOnce sync.Once
	file_expressions_proto_rawDescData []byte
)

func file_expressions_proto_rawDescGZIP() []byte {
	file_expressions_proto_rawDescOnce.Do(func() {
		file_expressions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_expressions_proto_rawDesc), len(file_expressions_proto_rawDesc)))
	})
	return file_expressions_proto_rawDescData
}

var file_expressions_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_expressions_proto_goTypes = []any{
	(*DataExpression)(nil),            // 0: DataExpression
	(*ModuleReference)(nil),           // 1: ModuleReference
	(*DataExpressionExecStats)(nil),   // 2: DataExpressionExecStats
	(*ExpressionResultItem)(nil),      // 3: ExpressionResultItem
	(*ExpressionDisplaySettings)(nil), // 4: ExpressionDisplaySettings
	(*OwnershipSummary)(nil),          // 5: OwnershipSummary
	(*SemanticVersion)(nil),           // 6: SemanticVersion
}
var file_expressions_proto_depIdxs = []int32{
	1, // 0: DataExpression.moduleReferences:type_name -> ModuleReference
	2, // 1: DataExpression.recentExecStats:type_name -> DataExpressionExecStats
	5, // 2: DataExpression.owner:type_name -> OwnershipSummary
	6, // 3: ModuleReference.version:type_name -> SemanticVersion
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_expressions_proto_init() }
func file_expressions_proto_init() {
	if File_expressions_proto != nil {
		return
	}
	file_ownership_access_proto_init()
	file_version_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_expressions_proto_rawDesc), len(file_expressions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_expressions_proto_goTypes,
		DependencyIndexes: file_expressions_proto_depIdxs,
		MessageInfos:      file_expressions_proto_msgTypes,
	}.Build()
	File_expressions_proto = out.File
	file_expressions_proto_goTypes = nil
	file_expressions_proto_depIdxs = nil
}
