// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: image-coreg.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MVPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Line           float32 `protobuf:"fixed32,1,opt,name=Line,proto3" json:"line"`                     
	Sample         float32 `protobuf:"fixed32,2,opt,name=Sample,proto3" json:"sample"`                 
	SpectrumNumber int32   `protobuf:"varint,3,opt,name=SpectrumNumber,proto3" json:"spectrum_number"`  
}

func (x *MVPoint) Reset() {
	*x = MVPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_image_coreg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MVPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MVPoint) ProtoMessage() {}

func (x *MVPoint) ProtoReflect() protoreflect.Message {
	mi := &file_image_coreg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MVPoint.ProtoReflect.Descriptor instead.
func (*MVPoint) Descriptor() ([]byte, []int) {
	return file_image_coreg_proto_rawDescGZIP(), []int{0}
}

func (x *MVPoint) GetLine() float32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *MVPoint) GetSample() float32 {
	if x != nil {
		return x.Sample
	}
	return 0
}

func (x *MVPoint) GetSpectrumNumber() int32 {
	if x != nil {
		return x.SpectrumNumber
	}
	return 0
}

type MVObservation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Interpolated           bool       `protobuf:"varint,1,opt,name=Interpolated,proto3" json:"interpolated"`                     
	ObservationCSVFilename string     `protobuf:"bytes,2,opt,name=ObservationCSVFilename,proto3" json:"observationCSVFilename"`  
	ContextImageUrl        string     `protobuf:"bytes,3,opt,name=ContextImageUrl,proto3" json:"contextImageUrl"`                
	Site                   string     `protobuf:"bytes,4,opt,name=Site,proto3" json:"site"`                                      
	Drive                  int32      `protobuf:"varint,5,opt,name=Drive,proto3" json:"drive"`                                   
	OriginalPoints         []*MVPoint `protobuf:"bytes,6,rep,name=OriginalPoints,proto3" json:"originalPoints"`                  
	TranslatedPoints       []*MVPoint `protobuf:"bytes,7,rep,name=TranslatedPoints,proto3" json:"translatedPoints"`              
}

func (x *MVObservation) Reset() {
	*x = MVObservation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_image_coreg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MVObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MVObservation) ProtoMessage() {}

func (x *MVObservation) ProtoReflect() protoreflect.Message {
	mi := &file_image_coreg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MVObservation.ProtoReflect.Descriptor instead.
func (*MVObservation) Descriptor() ([]byte, []int) {
	return file_image_coreg_proto_rawDescGZIP(), []int{1}
}

func (x *MVObservation) GetInterpolated() bool {
	if x != nil {
		return x.Interpolated
	}
	return false
}

func (x *MVObservation) GetObservationCSVFilename() string {
	if x != nil {
		return x.ObservationCSVFilename
	}
	return ""
}

func (x *MVObservation) GetContextImageUrl() string {
	if x != nil {
		return x.ContextImageUrl
	}
	return ""
}

func (x *MVObservation) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *MVObservation) GetDrive() int32 {
	if x != nil {
		return x.Drive
	}
	return 0
}

func (x *MVObservation) GetOriginalPoints() []*MVPoint {
	if x != nil {
		return x.OriginalPoints
	}
	return nil
}

func (x *MVObservation) GetTranslatedPoints() []*MVPoint {
	if x != nil {
		return x.TranslatedPoints
	}
	return nil
}

type MVWarpedOverlayImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Interpolated   bool   `protobuf:"varint,1,opt,name=Interpolated,proto3" json:"interpolated"`     
	MappedImageUrl string `protobuf:"bytes,2,opt,name=MappedImageUrl,proto3" json:"mappedImageUrl"`  
	WarpedImageUrl string `protobuf:"bytes,3,opt,name=WarpedImageUrl,proto3" json:"warpedImageUrl"`  
}

func (x *MVWarpedOverlayImage) Reset() {
	*x = MVWarpedOverlayImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_image_coreg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MVWarpedOverlayImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MVWarpedOverlayImage) ProtoMessage() {}

func (x *MVWarpedOverlayImage) ProtoReflect() protoreflect.Message {
	mi := &file_image_coreg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MVWarpedOverlayImage.ProtoReflect.Descriptor instead.
func (*MVWarpedOverlayImage) Descriptor() ([]byte, []int) {
	return file_image_coreg_proto_rawDescGZIP(), []int{2}
}

func (x *MVWarpedOverlayImage) GetInterpolated() bool {
	if x != nil {
		return x.Interpolated
	}
	return false
}

func (x *MVWarpedOverlayImage) GetMappedImageUrl() string {
	if x != nil {
		return x.MappedImageUrl
	}
	return ""
}

func (x *MVWarpedOverlayImage) GetWarpedImageUrl() string {
	if x != nil {
		return x.WarpedImageUrl
	}
	return ""
}

type MarsViewerExport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Observations        []*MVObservation        `protobuf:"bytes,1,rep,name=Observations,proto3" json:"observations"`                
	BaseImageUrl        string                  `protobuf:"bytes,2,opt,name=BaseImageUrl,proto3" json:"baseImageUrl"`                
	WarpedOverlayImages []*MVWarpedOverlayImage `protobuf:"bytes,3,rep,name=WarpedOverlayImages,proto3" json:"warpedOverlayImages"`  
	MarsviewerLink      string                  `protobuf:"bytes,4,opt,name=MarsviewerLink,proto3" json:"marsviewerLink"`            
}

func (x *MarsViewerExport) Reset() {
	*x = MarsViewerExport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_image_coreg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarsViewerExport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarsViewerExport) ProtoMessage() {}

func (x *MarsViewerExport) ProtoReflect() protoreflect.Message {
	mi := &file_image_coreg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarsViewerExport.ProtoReflect.Descriptor instead.
func (*MarsViewerExport) Descriptor() ([]byte, []int) {
	return file_image_coreg_proto_rawDescGZIP(), []int{3}
}

func (x *MarsViewerExport) GetObservations() []*MVObservation {
	if x != nil {
		return x.Observations
	}
	return nil
}

func (x *MarsViewerExport) GetBaseImageUrl() string {
	if x != nil {
		return x.BaseImageUrl
	}
	return ""
}

func (x *MarsViewerExport) GetWarpedOverlayImages() []*MVWarpedOverlayImage {
	if x != nil {
		return x.WarpedOverlayImages
	}
	return nil
}

func (x *MarsViewerExport) GetMarsviewerLink() string {
	if x != nil {
		return x.MarsviewerLink
	}
	return ""
}

type ImageCoregImportJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId  string            `protobuf:"bytes,1,opt,name=JobId,proto3" json:"JobId,omitempty"`
	Params *MarsViewerExport `protobuf:"bytes,2,opt,name=Params,proto3" json:"Params,omitempty"`
}

func (x *ImageCoregImportJob) Reset() {
	*x = ImageCoregImportJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_image_coreg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageCoregImportJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageCoregImportJob) ProtoMessage() {}

func (x *ImageCoregImportJob) ProtoReflect() protoreflect.Message {
	mi := &file_image_coreg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageCoregImportJob.ProtoReflect.Descriptor instead.
func (*ImageCoregImportJob) Descriptor() ([]byte, []int) {
	return file_image_coreg_proto_rawDescGZIP(), []int{4}
}

func (x *ImageCoregImportJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ImageCoregImportJob) GetParams() *MarsViewerExport {
	if x != nil {
		return x.Params
	}
	return nil
}

var File_image_coreg_proto protoreflect.FileDescriptor

var file_image_coreg_proto_rawDesc = []byte{
	0x0a, 0x11, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2d, 0x63, 0x6f, 0x72, 0x65, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x07, 0x4d, 0x56, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x4c, 0x69,
	0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x06, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x53, 0x70,
	0x65, 0x63, 0x74, 0x72, 0x75, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0e, 0x53, 0x70, 0x65, 0x63, 0x74, 0x72, 0x75, 0x6d, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x22, 0xa7, 0x02, 0x0a, 0x0d, 0x4d, 0x56, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x6f, 0x6c,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x70, 0x6f, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x12, 0x36, 0x0a, 0x16, 0x4f, 0x62, 0x73, 0x65,
	0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x53, 0x56, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x53, 0x56, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x28, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69,
	0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x53, 0x69, 0x74, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x44, 0x72, 0x69, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x44,
	0x72, 0x69, 0x76, 0x65, 0x12, 0x30, 0x0a, 0x0e, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4d,
	0x56, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0e, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x34, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c,
	0x61, 0x74, 0x65, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x4d, 0x56, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x10, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x8a, 0x01, 0x0a,
	0x14, 0x4d, 0x56, 0x57, 0x61, 0x72, 0x70, 0x65, 0x64, 0x4f, 0x76, 0x65, 0x72, 0x6c, 0x61, 0x79,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x6f,
	0x6c, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x70, 0x6f, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x4d, 0x61, 0x70,
	0x70, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x4d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72,
	0x6c, 0x12, 0x26, 0x0a, 0x0e, 0x57, 0x61, 0x72, 0x70, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x57, 0x61, 0x72, 0x70, 0x65,
	0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x22, 0xdb, 0x01, 0x0a, 0x10, 0x4d, 0x61,
	0x72, 0x73, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x32,
	0x0a, 0x0c, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4d, 0x56, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55,
	0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x47, 0x0a, 0x13, 0x57, 0x61, 0x72, 0x70, 0x65, 0x64,
	0x4f, 0x76, 0x65, 0x72, 0x6c, 0x61, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x4d, 0x56, 0x57, 0x61, 0x72, 0x70, 0x65, 0x64, 0x4f, 0x76,
	0x65, 0x72, 0x6c, 0x61, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x13, 0x57, 0x61, 0x72, 0x70,
	0x65, 0x64, 0x4f, 0x76, 0x65, 0x72, 0x6c, 0x61, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12,
	0x26, 0x0a, 0x0e, 0x4d, 0x61, 0x72, 0x73, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x4c, 0x69, 0x6e,
	0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x4d, 0x61, 0x72, 0x73, 0x76, 0x69, 0x65,
	0x77, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x56, 0x0a, 0x13, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x43, 0x6f, 0x72, 0x65, 0x67, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x4a, 0x6f, 0x62, 0x12, 0x14,
	0x0a, 0x05, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4a,
	0x6f, 0x62, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4d, 0x61, 0x72, 0x73, 0x56, 0x69, 0x65, 0x77, 0x65,
	0x72, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x06, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x42,
	0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_image_coreg_proto_rawDescOnce sync.Once
	file_image_coreg_proto_rawDescData = file_image_coreg_proto_rawDesc
)

func file_image_coreg_proto_rawDescGZIP() []byte {
	file_image_coreg_proto_rawDescOnce.Do(func() {
		file_image_coreg_proto_rawDescData = protoimpl.X.CompressGZIP(file_image_coreg_proto_rawDescData)
	})
	return file_image_coreg_proto_rawDescData
}

var file_image_coreg_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_image_coreg_proto_goTypes = []interface{}{
	(*MVPoint)(nil),              // 0: MVPoint
	(*MVObservation)(nil),        // 1: MVObservation
	(*MVWarpedOverlayImage)(nil), // 2: MVWarpedOverlayImage
	(*MarsViewerExport)(nil),     // 3: MarsViewerExport
	(*ImageCoregImportJob)(nil),  // 4: ImageCoregImportJob
}
var file_image_coreg_proto_depIdxs = []int32{
	0, // 0: MVObservation.OriginalPoints:type_name -> MVPoint
	0, // 1: MVObservation.TranslatedPoints:type_name -> MVPoint
	1, // 2: MarsViewerExport.Observations:type_name -> MVObservation
	2, // 3: MarsViewerExport.WarpedOverlayImages:type_name -> MVWarpedOverlayImage
	3, // 4: ImageCoregImportJob.Params:type_name -> MarsViewerExport
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_image_coreg_proto_init() }
func file_image_coreg_proto_init() {
	if File_image_coreg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_image_coreg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MVPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_image_coreg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MVObservation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_image_coreg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MVWarpedOverlayImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_image_coreg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarsViewerExport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_image_coreg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageCoregImportJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_image_coreg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_image_coreg_proto_goTypes,
		DependencyIndexes: file_image_coreg_proto_depIdxs,
		MessageInfos:      file_image_coreg_proto_msgTypes,
	}.Build()
	File_image_coreg_proto = out.File
	file_image_coreg_proto_rawDesc = nil
	file_image_coreg_proto_goTypes = nil
	file_image_coreg_proto_depIdxs = nil
}
