// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: image-beam-location-msgs.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// requires(NONE)
type ImageBeamLocationsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageName string `protobuf:"bytes,1,opt,name=imageName,proto3" json:"imageName,omitempty"`
}

func (x *ImageBeamLocationsReq) Reset() {
	*x = ImageBeamLocationsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_image_beam_location_msgs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageBeamLocationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageBeamLocationsReq) ProtoMessage() {}

func (x *ImageBeamLocationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_image_beam_location_msgs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageBeamLocationsReq.ProtoReflect.Descriptor instead.
func (*ImageBeamLocationsReq) Descriptor() ([]byte, []int) {
	return file_image_beam_location_msgs_proto_rawDescGZIP(), []int{0}
}

func (x *ImageBeamLocationsReq) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

type ImageBeamLocationsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Locations *ImageLocations `protobuf:"bytes,1,opt,name=locations,proto3" json:"locations,omitempty"`
}

func (x *ImageBeamLocationsResp) Reset() {
	*x = ImageBeamLocationsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_image_beam_location_msgs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageBeamLocationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageBeamLocationsResp) ProtoMessage() {}

func (x *ImageBeamLocationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_image_beam_location_msgs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageBeamLocationsResp.ProtoReflect.Descriptor instead.
func (*ImageBeamLocationsResp) Descriptor() ([]byte, []int) {
	return file_image_beam_location_msgs_proto_rawDescGZIP(), []int{1}
}

func (x *ImageBeamLocationsResp) GetLocations() *ImageLocations {
	if x != nil {
		return x.Locations
	}
	return nil
}

var File_image_beam_location_msgs_proto protoreflect.FileDescriptor

var file_image_beam_location_msgs_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2d, 0x62, 0x65, 0x61, 0x6d, 0x2d, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x19, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2d, 0x62, 0x65, 0x61, 0x6d, 0x2d, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x15, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x42, 0x65, 0x61, 0x6d, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x47, 0x0a, 0x16, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x65, 0x61, 0x6d, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x09,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_image_beam_location_msgs_proto_rawDescOnce sync.Once
	file_image_beam_location_msgs_proto_rawDescData = file_image_beam_location_msgs_proto_rawDesc
)

func file_image_beam_location_msgs_proto_rawDescGZIP() []byte {
	file_image_beam_location_msgs_proto_rawDescOnce.Do(func() {
		file_image_beam_location_msgs_proto_rawDescData = protoimpl.X.CompressGZIP(file_image_beam_location_msgs_proto_rawDescData)
	})
	return file_image_beam_location_msgs_proto_rawDescData
}

var file_image_beam_location_msgs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_image_beam_location_msgs_proto_goTypes = []interface{}{
	(*ImageBeamLocationsReq)(nil),  // 0: ImageBeamLocationsReq
	(*ImageBeamLocationsResp)(nil), // 1: ImageBeamLocationsResp
	(*ImageLocations)(nil),         // 2: ImageLocations
}
var file_image_beam_location_msgs_proto_depIdxs = []int32{
	2, // 0: ImageBeamLocationsResp.locations:type_name -> ImageLocations
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_image_beam_location_msgs_proto_init() }
func file_image_beam_location_msgs_proto_init() {
	if File_image_beam_location_msgs_proto != nil {
		return
	}
	file_image_beam_location_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_image_beam_location_msgs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageBeamLocationsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_image_beam_location_msgs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageBeamLocationsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_image_beam_location_msgs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_image_beam_location_msgs_proto_goTypes,
		DependencyIndexes: file_image_beam_location_msgs_proto_depIdxs,
		MessageInfos:      file_image_beam_location_msgs_proto_msgTypes,
	}.Build()
	File_image_beam_location_msgs_proto = out.File
	file_image_beam_location_msgs_proto_rawDesc = nil
	file_image_beam_location_msgs_proto_goTypes = nil
	file_image_beam_location_msgs_proto_depIdxs = nil
}
