// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: modules.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Data Modules are "shared" by default
type DataModuleDB struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`  
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Comments        string                 `protobuf:"bytes,3,opt,name=comments,proto3" json:"comments,omitempty"`
	ModifiedUnixSec uint32                 `protobuf:"varint,4,opt,name=modifiedUnixSec,proto3" json:"modifiedUnixSec,omitempty"`
	// Only sent out by API, not stored in DB this way
	Owner         *OwnershipSummary `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty" bson:"-"`  
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataModuleDB) Reset() {
	*x = DataModuleDB{}
	mi := &file_modules_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataModuleDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataModuleDB) ProtoMessage() {}

func (x *DataModuleDB) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataModuleDB.ProtoReflect.Descriptor instead.
func (*DataModuleDB) Descriptor() ([]byte, []int) {
	return file_modules_proto_rawDescGZIP(), []int{0}
}

func (x *DataModuleDB) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataModuleDB) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataModuleDB) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

func (x *DataModuleDB) GetModifiedUnixSec() uint32 {
	if x != nil {
		return x.ModifiedUnixSec
	}
	return 0
}

func (x *DataModuleDB) GetOwner() *OwnershipSummary {
	if x != nil {
		return x.Owner
	}
	return nil
}

type DataModuleVersionDB struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`  
	ModuleId         string                 `protobuf:"bytes,2,opt,name=moduleId,proto3" json:"moduleId,omitempty"`
	Version          *SemanticVersion       `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Tags             []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Comments         string                 `protobuf:"bytes,5,opt,name=comments,proto3" json:"comments,omitempty"`
	TimeStampUnixSec uint32                 `protobuf:"varint,6,opt,name=timeStampUnixSec,proto3" json:"timeStampUnixSec,omitempty"`
	SourceCode       string                 `protobuf:"bytes,7,opt,name=sourceCode,proto3" json:"sourceCode,omitempty"` //DOIMetadata doiMetadata = 8;
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DataModuleVersionDB) Reset() {
	*x = DataModuleVersionDB{}
	mi := &file_modules_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataModuleVersionDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataModuleVersionDB) ProtoMessage() {}

func (x *DataModuleVersionDB) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataModuleVersionDB.ProtoReflect.Descriptor instead.
func (*DataModuleVersionDB) Descriptor() ([]byte, []int) {
	return file_modules_proto_rawDescGZIP(), []int{1}
}

func (x *DataModuleVersionDB) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataModuleVersionDB) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *DataModuleVersionDB) GetVersion() *SemanticVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *DataModuleVersionDB) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DataModuleVersionDB) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

func (x *DataModuleVersionDB) GetTimeStampUnixSec() uint32 {
	if x != nil {
		return x.TimeStampUnixSec
	}
	return 0
}

func (x *DataModuleVersionDB) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

type DataModuleVersion struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          *SemanticVersion       `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Tags             []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Comments         string                 `protobuf:"bytes,3,opt,name=comments,proto3" json:"comments,omitempty"`
	TimeStampUnixSec uint32                 `protobuf:"varint,4,opt,name=timeStampUnixSec,proto3" json:"timeStampUnixSec,omitempty"`
	// Optional - Get Module doesn't return this but querying a specific version does
	SourceCode    string `protobuf:"bytes,5,opt,name=sourceCode,proto3" json:"sourceCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataModuleVersion) Reset() {
	*x = DataModuleVersion{}
	mi := &file_modules_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataModuleVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataModuleVersion) ProtoMessage() {}

func (x *DataModuleVersion) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataModuleVersion.ProtoReflect.Descriptor instead.
func (*DataModuleVersion) Descriptor() ([]byte, []int) {
	return file_modules_proto_rawDescGZIP(), []int{2}
}

func (x *DataModuleVersion) GetVersion() *SemanticVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *DataModuleVersion) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DataModuleVersion) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

func (x *DataModuleVersion) GetTimeStampUnixSec() uint32 {
	if x != nil {
		return x.TimeStampUnixSec
	}
	return 0
}

func (x *DataModuleVersion) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

// NOT stored in DB!
type DataModule struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Comments        string                 `protobuf:"bytes,3,opt,name=comments,proto3" json:"comments,omitempty"`
	ModifiedUnixSec uint32                 `protobuf:"varint,4,opt,name=modifiedUnixSec,proto3" json:"modifiedUnixSec,omitempty"`
	Creator         *OwnershipSummary      `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Versions        []*DataModuleVersion   `protobuf:"bytes,6,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DataModule) Reset() {
	*x = DataModule{}
	mi := &file_modules_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataModule) ProtoMessage() {}

func (x *DataModule) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataModule.ProtoReflect.Descriptor instead.
func (*DataModule) Descriptor() ([]byte, []int) {
	return file_modules_proto_rawDescGZIP(), []int{3}
}

func (x *DataModule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataModule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataModule) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

func (x *DataModule) GetModifiedUnixSec() uint32 {
	if x != nil {
		return x.ModifiedUnixSec
	}
	return 0
}

func (x *DataModule) GetCreator() *OwnershipSummary {
	if x != nil {
		return x.Creator
	}
	return nil
}

func (x *DataModule) GetVersions() []*DataModuleVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

var File_modules_proto protoreflect.FileDescriptor

const file_modules_proto_rawDesc = "" +
	"\n" +
	"\rmodules.proto\x1a\x16ownership-access.proto\x1a\rversion.proto\"\xa1\x01\n" +
	"\fDataModuleDB\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcomments\x18\x03 \x01(\tR\bcomments\x12(\n" +
	"\x0fmodifiedUnixSec\x18\x04 \x01(\rR\x0fmodifiedUnixSec\x12'\n" +
	"\x05owner\x18\x05 \x01(\v2\x11.OwnershipSummaryR\x05owner\"\xe9\x01\n" +
	"\x13DataModuleVersionDB\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bmoduleId\x18\x02 \x01(\tR\bmoduleId\x12*\n" +
	"\aversion\x18\x03 \x01(\v2\x10.SemanticVersionR\aversion\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1a\n" +
	"\bcomments\x18\x05 \x01(\tR\bcomments\x12*\n" +
	"\x10timeStampUnixSec\x18\x06 \x01(\rR\x10timeStampUnixSec\x12\x1e\n" +
	"\n" +
	"sourceCode\x18\a \x01(\tR\n" +
	"sourceCode\"\xbb\x01\n" +
	"\x11DataModuleVersion\x12*\n" +
	"\aversion\x18\x01 \x01(\v2\x10.SemanticVersionR\aversion\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x1a\n" +
	"\bcomments\x18\x03 \x01(\tR\bcomments\x12*\n" +
	"\x10timeStampUnixSec\x18\x04 \x01(\rR\x10timeStampUnixSec\x12\x1e\n" +
	"\n" +
	"sourceCode\x18\x05 \x01(\tR\n" +
	"sourceCode\"\xd3\x01\n" +
	"\n" +
	"DataModule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcomments\x18\x03 \x01(\tR\bcomments\x12(\n" +
	"\x0fmodifiedUnixSec\x18\x04 \x01(\rR\x0fmodifiedUnixSec\x12+\n" +
	"\acreator\x18\x05 \x01(\v2\x11.OwnershipSummaryR\acreator\x12.\n" +
	"\bversions\x18\x06 \x03(\v2\x12.DataModuleVersionR\bversionsB\n" +
	"Z\b.;protosb\x06proto3"

var (
	file_modules_proto_rawDescOnce sync.Once
	file_modules_proto_rawDescData []byte
)

func file_modules_proto_rawDescGZIP() []byte {
	file_modules_proto_rawDescOnce.Do(func() {
		file_modules_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_proto_rawDesc), len(file_modules_proto_rawDesc)))
	})
	return file_modules_proto_rawDescData
}

var file_modules_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_modules_proto_goTypes = []any{
	(*DataModuleDB)(nil),        // 0: DataModuleDB
	(*DataModuleVersionDB)(nil), // 1: DataModuleVersionDB
	(*DataModuleVersion)(nil),   // 2: DataModuleVersion
	(*DataModule)(nil),          // 3: DataModule
	(*OwnershipSummary)(nil),    // 4: OwnershipSummary
	(*SemanticVersion)(nil),     // 5: SemanticVersion
}
var file_modules_proto_depIdxs = []int32{
	4, // 0: DataModuleDB.owner:type_name -> OwnershipSummary
	5, // 1: DataModuleVersionDB.version:type_name -> SemanticVersion
	5, // 2: DataModuleVersion.version:type_name -> SemanticVersion
	4, // 3: DataModule.creator:type_name -> OwnershipSummary
	2, // 4: DataModule.versions:type_name -> DataModuleVersion
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_modules_proto_init() }
func file_modules_proto_init() {
	if File_modules_proto != nil {
		return
	}
	file_ownership_access_proto_init()
	file_version_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_proto_rawDesc), len(file_modules_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modules_proto_goTypes,
		DependencyIndexes: file_modules_proto_depIdxs,
		MessageInfos:      file_modules_proto_msgTypes,
	}.Build()
	File_modules_proto = out.File
	file_modules_proto_goTypes = nil
	file_modules_proto_depIdxs = nil
}
