// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: permissions.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// These are the permissions a user can have. They have to be defined in Auth0 and are included in
// the JWT permission list. API can verify that the permission required for a message has been set
// before allowing the request to be processed.
// NOTE: Each message name ending with Req is expected to have a line preceeding it
// that looks like this:
// requires(PERMISSION)
// Where PERMISSION is one of the below enums (with the PERM_ prefix removed)
type Permission int32

const (
	Permission_PERM_NONE     Permission = 0 // https://protobuf.dev/programming-guides/dos-donts/ says specify something at 0
	Permission_PERM_QUANTIFY Permission = 1 // Can run quant jobs
	// PERM_JOB_ADMIN = 2; // Can view all quant jobs
	Permission_PERM_USER_ADMIN Permission = 3 // Can edit users, roles, create/delete user-groups
	Permission_PERM_EDIT_SCAN  Permission = 5 // Can upload datasets, rename them, add images
	// PERM_BLESS_QUANT = 6; // Can mark a quant as "blessed"
	Permission_PERM_PIXLISE_ADMIN         Permission = 7
	Permission_PERM_EDIT_DIFFRACTION      Permission = 9  // Can edit detected diffraction peak status AND add user defined peaks
	Permission_PERM_EXPORT                Permission = 10 // Can export data
	Permission_PERM_EDIT_EXPRESSION       Permission = 11 // Can edit/delete expressions, expression groups and data modules
	Permission_PERM_EDIT_API_SETTINGS     Permission = 12 // Can change system settings eg log level
	Permission_PERM_READ_PIQUANT_SETTINGS Permission = 13 // Can read PIQUANT settings
	Permission_PERM_EDIT_PIQUANT_SETTINGS Permission = 14 // Can write PIQUANT settings, eg current version to run
	Permission_PERM_EDIT_ROI              Permission = 15 // Can create/edit/delete ROIs
	Permission_PERM_EDIT_TAGS             Permission = 16 // Can create+edit tags
	Permission_PERM_EDIT_OWN_USER         Permission = 17 // Can edit own user account, eg notifications, name, email etc
	Permission_PERM_EDIT_VIEW_STATE       Permission = 18 // Can save view state
	Permission_PERM_EDIT_ELEMENT_SET      Permission = 19 // Can create/edit/delete Element Sets
	Permission_PERM_EDIT_EXPRESSION_GROUP Permission = 20 // Can create/edit/delete Expression Groups (formerly known as RGB Mixes)
)

// Enum value maps for Permission.
var (
	Permission_name = map[int32]string{
		0:  "PERM_NONE",
		1:  "PERM_QUANTIFY",
		3:  "PERM_USER_ADMIN",
		5:  "PERM_EDIT_SCAN",
		7:  "PERM_PIXLISE_ADMIN",
		9:  "PERM_EDIT_DIFFRACTION",
		10: "PERM_EXPORT",
		11: "PERM_EDIT_EXPRESSION",
		12: "PERM_EDIT_API_SETTINGS",
		13: "PERM_READ_PIQUANT_SETTINGS",
		14: "PERM_EDIT_PIQUANT_SETTINGS",
		15: "PERM_EDIT_ROI",
		16: "PERM_EDIT_TAGS",
		17: "PERM_EDIT_OWN_USER",
		18: "PERM_EDIT_VIEW_STATE",
		19: "PERM_EDIT_ELEMENT_SET",
		20: "PERM_EDIT_EXPRESSION_GROUP",
	}
	Permission_value = map[string]int32{
		"PERM_NONE":                  0,
		"PERM_QUANTIFY":              1,
		"PERM_USER_ADMIN":            3,
		"PERM_EDIT_SCAN":             5,
		"PERM_PIXLISE_ADMIN":         7,
		"PERM_EDIT_DIFFRACTION":      9,
		"PERM_EXPORT":                10,
		"PERM_EDIT_EXPRESSION":       11,
		"PERM_EDIT_API_SETTINGS":     12,
		"PERM_READ_PIQUANT_SETTINGS": 13,
		"PERM_EDIT_PIQUANT_SETTINGS": 14,
		"PERM_EDIT_ROI":              15,
		"PERM_EDIT_TAGS":             16,
		"PERM_EDIT_OWN_USER":         17,
		"PERM_EDIT_VIEW_STATE":       18,
		"PERM_EDIT_ELEMENT_SET":      19,
		"PERM_EDIT_EXPRESSION_GROUP": 20,
	}
)

func (x Permission) Enum() *Permission {
	p := new(Permission)
	*p = x
	return p
}

func (x Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_permissions_proto_enumTypes[0].Descriptor()
}

func (Permission) Type() protoreflect.EnumType {
	return &file_permissions_proto_enumTypes[0]
}

func (x Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Permission.Descriptor instead.
func (Permission) EnumDescriptor() ([]byte, []int) {
	return file_permissions_proto_rawDescGZIP(), []int{0}
}

var File_permissions_proto protoreflect.FileDescriptor

const file_permissions_proto_rawDesc = "" +
	"\n" +
	"\x11permissions.proto*\xa5\x03\n" +
	"\n" +
	"Permission\x12\r\n" +
	"\tPERM_NONE\x10\x00\x12\x11\n" +
	"\rPERM_QUANTIFY\x10\x01\x12\x13\n" +
	"\x0fPERM_USER_ADMIN\x10\x03\x12\x12\n" +
	"\x0ePERM_EDIT_SCAN\x10\x05\x12\x16\n" +
	"\x12PERM_PIXLISE_ADMIN\x10\a\x12\x19\n" +
	"\x15PERM_EDIT_DIFFRACTION\x10\t\x12\x0f\n" +
	"\vPERM_EXPORT\x10\n" +
	"\x12\x18\n" +
	"\x14PERM_EDIT_EXPRESSION\x10\v\x12\x1a\n" +
	"\x16PERM_EDIT_API_SETTINGS\x10\f\x12\x1e\n" +
	"\x1aPERM_READ_PIQUANT_SETTINGS\x10\r\x12\x1e\n" +
	"\x1aPERM_EDIT_PIQUANT_SETTINGS\x10\x0e\x12\x11\n" +
	"\rPERM_EDIT_ROI\x10\x0f\x12\x12\n" +
	"\x0ePERM_EDIT_TAGS\x10\x10\x12\x16\n" +
	"\x12PERM_EDIT_OWN_USER\x10\x11\x12\x18\n" +
	"\x14PERM_EDIT_VIEW_STATE\x10\x12\x12\x19\n" +
	"\x15PERM_EDIT_ELEMENT_SET\x10\x13\x12\x1e\n" +
	"\x1aPERM_EDIT_EXPRESSION_GROUP\x10\x14B\n" +
	"Z\b.;protosb\x06proto3"

var (
	file_permissions_proto_rawDescOnce sync.Once
	file_permissions_proto_rawDescData []byte
)

func file_permissions_proto_rawDescGZIP() []byte {
	file_permissions_proto_rawDescOnce.Do(func() {
		file_permissions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_permissions_proto_rawDesc), len(file_permissions_proto_rawDesc)))
	})
	return file_permissions_proto_rawDescData
}

var file_permissions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_permissions_proto_goTypes = []any{
	(Permission)(0), // 0: Permission
}
var file_permissions_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_permissions_proto_init() }
func file_permissions_proto_init() {
	if File_permissions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_permissions_proto_rawDesc), len(file_permissions_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_permissions_proto_goTypes,
		DependencyIndexes: file_permissions_proto_depIdxs,
		EnumInfos:         file_permissions_proto_enumTypes,
	}.Build()
	File_permissions_proto = out.File
	file_permissions_proto_goTypes = nil
	file_permissions_proto_depIdxs = nil
}
