// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: pseudo-intensities-msgs.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// requires(NONE)
type PseudoIntensityReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScanId  string          `protobuf:"bytes,1,opt,name=scanId,proto3" json:"scanId,omitempty"`
	Entries *ScanEntryRange `protobuf:"bytes,2,opt,name=entries,proto3" json:"entries,omitempty"`
}

func (x *PseudoIntensityReq) Reset() {
	*x = PseudoIntensityReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pseudo_intensities_msgs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PseudoIntensityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PseudoIntensityReq) ProtoMessage() {}

func (x *PseudoIntensityReq) ProtoReflect() protoreflect.Message {
	mi := &file_pseudo_intensities_msgs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PseudoIntensityReq.ProtoReflect.Descriptor instead.
func (*PseudoIntensityReq) Descriptor() ([]byte, []int) {
	return file_pseudo_intensities_msgs_proto_rawDescGZIP(), []int{0}
}

func (x *PseudoIntensityReq) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *PseudoIntensityReq) GetEntries() *ScanEntryRange {
	if x != nil {
		return x.Entries
	}
	return nil
}

type PseudoIntensityResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IntensityLabels []string `protobuf:"bytes,1,rep,name=intensityLabels,proto3" json:"intensityLabels,omitempty"`
	// One per location
	Data []*PseudoIntensityData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *PseudoIntensityResp) Reset() {
	*x = PseudoIntensityResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pseudo_intensities_msgs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PseudoIntensityResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PseudoIntensityResp) ProtoMessage() {}

func (x *PseudoIntensityResp) ProtoReflect() protoreflect.Message {
	mi := &file_pseudo_intensities_msgs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PseudoIntensityResp.ProtoReflect.Descriptor instead.
func (*PseudoIntensityResp) Descriptor() ([]byte, []int) {
	return file_pseudo_intensities_msgs_proto_rawDescGZIP(), []int{1}
}

func (x *PseudoIntensityResp) GetIntensityLabels() []string {
	if x != nil {
		return x.IntensityLabels
	}
	return nil
}

func (x *PseudoIntensityResp) GetData() []*PseudoIntensityData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pseudo_intensities_msgs_proto protoreflect.FileDescriptor

var file_pseudo_intensities_msgs_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x73, 0x65, 0x75, 0x64, 0x6f, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x73, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x2d, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x18, 0x70, 0x73, 0x65, 0x75, 0x64, 0x6f, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x73, 0x63, 0x61, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x57, 0x0a, 0x12, 0x50, 0x73, 0x65, 0x75, 0x64, 0x6f, 0x49,
	0x6e, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x63, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x61,
	0x6e, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x69,
	0x0a, 0x13, 0x50, 0x73, 0x65, 0x75, 0x64, 0x6f, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x73, 0x69,
	0x74, 0x79, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f,
	0x69, 0x6e, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12,
	0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x50, 0x73, 0x65, 0x75, 0x64, 0x6f, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pseudo_intensities_msgs_proto_rawDescOnce sync.Once
	file_pseudo_intensities_msgs_proto_rawDescData = file_pseudo_intensities_msgs_proto_rawDesc
)

func file_pseudo_intensities_msgs_proto_rawDescGZIP() []byte {
	file_pseudo_intensities_msgs_proto_rawDescOnce.Do(func() {
		file_pseudo_intensities_msgs_proto_rawDescData = protoimpl.X.CompressGZIP(file_pseudo_intensities_msgs_proto_rawDescData)
	})
	return file_pseudo_intensities_msgs_proto_rawDescData
}

var file_pseudo_intensities_msgs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pseudo_intensities_msgs_proto_goTypes = []interface{}{
	(*PseudoIntensityReq)(nil),  // 0: PseudoIntensityReq
	(*PseudoIntensityResp)(nil), // 1: PseudoIntensityResp
	(*ScanEntryRange)(nil),      // 2: ScanEntryRange
	(*PseudoIntensityData)(nil), // 3: PseudoIntensityData
}
var file_pseudo_intensities_msgs_proto_depIdxs = []int32{
	2, // 0: PseudoIntensityReq.entries:type_name -> ScanEntryRange
	3, // 1: PseudoIntensityResp.data:type_name -> PseudoIntensityData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pseudo_intensities_msgs_proto_init() }
func file_pseudo_intensities_msgs_proto_init() {
	if File_pseudo_intensities_msgs_proto != nil {
		return
	}
	file_pseudo_intensities_proto_init()
	file_scan_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pseudo_intensities_msgs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PseudoIntensityReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pseudo_intensities_msgs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PseudoIntensityResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pseudo_intensities_msgs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pseudo_intensities_msgs_proto_goTypes,
		DependencyIndexes: file_pseudo_intensities_msgs_proto_depIdxs,
		MessageInfos:      file_pseudo_intensities_msgs_proto_msgTypes,
	}.Build()
	File_pseudo_intensities_msgs_proto = out.File
	file_pseudo_intensities_msgs_proto_rawDesc = nil
	file_pseudo_intensities_msgs_proto_goTypes = nil
	file_pseudo_intensities_msgs_proto_depIdxs = nil
}
