// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: quantification-retrieval-msgs.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuantOutputType int32

const (
	QuantOutputType_QO_UNKNOWN QuantOutputType = 0 // https://protobuf.dev/programming-guides/dos-donts/ says specify an unknown as 0
	QuantOutputType_QO_DATA    QuantOutputType = 1
	QuantOutputType_QO_LOG     QuantOutputType = 2
)

// Enum value maps for QuantOutputType.
var (
	QuantOutputType_name = map[int32]string{
		0: "QO_UNKNOWN",
		1: "QO_DATA",
		2: "QO_LOG",
	}
	QuantOutputType_value = map[string]int32{
		"QO_UNKNOWN": 0,
		"QO_DATA":    1,
		"QO_LOG":     2,
	}
)

func (x QuantOutputType) Enum() *QuantOutputType {
	p := new(QuantOutputType)
	*p = x
	return p
}

func (x QuantOutputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuantOutputType) Descriptor() protoreflect.EnumDescriptor {
	return file_quantification_retrieval_msgs_proto_enumTypes[0].Descriptor()
}

func (QuantOutputType) Type() protoreflect.EnumType {
	return &file_quantification_retrieval_msgs_proto_enumTypes[0]
}

func (x QuantOutputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuantOutputType.Descriptor instead.
func (QuantOutputType) EnumDescriptor() ([]byte, []int) {
	return file_quantification_retrieval_msgs_proto_rawDescGZIP(), []int{0}
}

// requires(NONE)
type QuantListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchParams *SearchParams `protobuf:"bytes,1,opt,name=searchParams,proto3" json:"searchParams,omitempty"`
}

func (x *QuantListReq) Reset() {
	*x = QuantListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quantification_retrieval_msgs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuantListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuantListReq) ProtoMessage() {}

func (x *QuantListReq) ProtoReflect() protoreflect.Message {
	mi := &file_quantification_retrieval_msgs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuantListReq.ProtoReflect.Descriptor instead.
func (*QuantListReq) Descriptor() ([]byte, []int) {
	return file_quantification_retrieval_msgs_proto_rawDescGZIP(), []int{0}
}

func (x *QuantListReq) GetSearchParams() *SearchParams {
	if x != nil {
		return x.SearchParams
	}
	return nil
}

type QuantListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quants []*QuantificationSummary `protobuf:"bytes,1,rep,name=quants,proto3" json:"quants,omitempty"`
}

func (x *QuantListResp) Reset() {
	*x = QuantListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quantification_retrieval_msgs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuantListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuantListResp) ProtoMessage() {}

func (x *QuantListResp) ProtoReflect() protoreflect.Message {
	mi := &file_quantification_retrieval_msgs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuantListResp.ProtoReflect.Descriptor instead.
func (*QuantListResp) Descriptor() ([]byte, []int) {
	return file_quantification_retrieval_msgs_proto_rawDescGZIP(), []int{1}
}

func (x *QuantListResp) GetQuants() []*QuantificationSummary {
	if x != nil {
		return x.Quants
	}
	return nil
}

// requires(NONE)
type QuantGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuantId     string `protobuf:"bytes,1,opt,name=quantId,proto3" json:"quantId,omitempty"`
	SummaryOnly bool   `protobuf:"varint,2,opt,name=summaryOnly,proto3" json:"summaryOnly,omitempty"`
}

func (x *QuantGetReq) Reset() {
	*x = QuantGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quantification_retrieval_msgs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuantGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuantGetReq) ProtoMessage() {}

func (x *QuantGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_quantification_retrieval_msgs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuantGetReq.ProtoReflect.Descriptor instead.
func (*QuantGetReq) Descriptor() ([]byte, []int) {
	return file_quantification_retrieval_msgs_proto_rawDescGZIP(), []int{2}
}

func (x *QuantGetReq) GetQuantId() string {
	if x != nil {
		return x.QuantId
	}
	return ""
}

func (x *QuantGetReq) GetSummaryOnly() bool {
	if x != nil {
		return x.SummaryOnly
	}
	return false
}

type QuantGetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Summary *QuantificationSummary `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Data    *Quantification        `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *QuantGetResp) Reset() {
	*x = QuantGetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quantification_retrieval_msgs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuantGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuantGetResp) ProtoMessage() {}

func (x *QuantGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_quantification_retrieval_msgs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuantGetResp.ProtoReflect.Descriptor instead.
func (*QuantGetResp) Descriptor() ([]byte, []int) {
	return file_quantification_retrieval_msgs_proto_rawDescGZIP(), []int{3}
}

func (x *QuantGetResp) GetSummary() *QuantificationSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *QuantGetResp) GetData() *Quantification {
	if x != nil {
		return x.Data
	}
	return nil
}

// requires(NONE)
type QuantLogListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuantId string `protobuf:"bytes,1,opt,name=quantId,proto3" json:"quantId,omitempty"`
}

func (x *QuantLogListReq) Reset() {
	*x = QuantLogListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quantification_retrieval_msgs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuantLogListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuantLogListReq) ProtoMessage() {}

func (x *QuantLogListReq) ProtoReflect() protoreflect.Message {
	mi := &file_quantification_retrieval_msgs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuantLogListReq.ProtoReflect.Descriptor instead.
func (*QuantLogListReq) Descriptor() ([]byte, []int) {
	return file_quantification_retrieval_msgs_proto_rawDescGZIP(), []int{4}
}

func (x *QuantLogListReq) GetQuantId() string {
	if x != nil {
		return x.QuantId
	}
	return ""
}

type QuantLogListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileNames []string `protobuf:"bytes,1,rep,name=fileNames,proto3" json:"fileNames,omitempty"`
}

func (x *QuantLogListResp) Reset() {
	*x = QuantLogListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quantification_retrieval_msgs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuantLogListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuantLogListResp) ProtoMessage() {}

func (x *QuantLogListResp) ProtoReflect() protoreflect.Message {
	mi := &file_quantification_retrieval_msgs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuantLogListResp.ProtoReflect.Descriptor instead.
func (*QuantLogListResp) Descriptor() ([]byte, []int) {
	return file_quantification_retrieval_msgs_proto_rawDescGZIP(), []int{5}
}

func (x *QuantLogListResp) GetFileNames() []string {
	if x != nil {
		return x.FileNames
	}
	return nil
}

// requires(NONE)
type QuantLogGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuantId string `protobuf:"bytes,1,opt,name=quantId,proto3" json:"quantId,omitempty"`
	LogName string `protobuf:"bytes,2,opt,name=logName,proto3" json:"logName,omitempty"`
}

func (x *QuantLogGetReq) Reset() {
	*x = QuantLogGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quantification_retrieval_msgs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuantLogGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuantLogGetReq) ProtoMessage() {}

func (x *QuantLogGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_quantification_retrieval_msgs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuantLogGetReq.ProtoReflect.Descriptor instead.
func (*QuantLogGetReq) Descriptor() ([]byte, []int) {
	return file_quantification_retrieval_msgs_proto_rawDescGZIP(), []int{6}
}

func (x *QuantLogGetReq) GetQuantId() string {
	if x != nil {
		return x.QuantId
	}
	return ""
}

func (x *QuantLogGetReq) GetLogName() string {
	if x != nil {
		return x.LogName
	}
	return ""
}

type QuantLogGetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogData string `protobuf:"bytes,1,opt,name=logData,proto3" json:"logData,omitempty"`
}

func (x *QuantLogGetResp) Reset() {
	*x = QuantLogGetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quantification_retrieval_msgs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuantLogGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuantLogGetResp) ProtoMessage() {}

func (x *QuantLogGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_quantification_retrieval_msgs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuantLogGetResp.ProtoReflect.Descriptor instead.
func (*QuantLogGetResp) Descriptor() ([]byte, []int) {
	return file_quantification_retrieval_msgs_proto_rawDescGZIP(), []int{7}
}

func (x *QuantLogGetResp) GetLogData() string {
	if x != nil {
		return x.LogData
	}
	return ""
}

// requires(NONE)
type QuantRawDataGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuantId string `protobuf:"bytes,1,opt,name=quantId,proto3" json:"quantId,omitempty"`
}

func (x *QuantRawDataGetReq) Reset() {
	*x = QuantRawDataGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quantification_retrieval_msgs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuantRawDataGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuantRawDataGetReq) ProtoMessage() {}

func (x *QuantRawDataGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_quantification_retrieval_msgs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuantRawDataGetReq.ProtoReflect.Descriptor instead.
func (*QuantRawDataGetReq) Descriptor() ([]byte, []int) {
	return file_quantification_retrieval_msgs_proto_rawDescGZIP(), []int{8}
}

func (x *QuantRawDataGetReq) GetQuantId() string {
	if x != nil {
		return x.QuantId
	}
	return ""
}

type QuantRawDataGetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *QuantRawDataGetResp) Reset() {
	*x = QuantRawDataGetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quantification_retrieval_msgs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuantRawDataGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuantRawDataGetResp) ProtoMessage() {}

func (x *QuantRawDataGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_quantification_retrieval_msgs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuantRawDataGetResp.ProtoReflect.Descriptor instead.
func (*QuantRawDataGetResp) Descriptor() ([]byte, []int) {
	return file_quantification_retrieval_msgs_proto_rawDescGZIP(), []int{9}
}

func (x *QuantRawDataGetResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// requires(NONE)
type QuantLastOutputGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutputType     QuantOutputType `protobuf:"varint,1,opt,name=outputType,proto3,enum=QuantOutputType" json:"outputType,omitempty"`
	ScanId         string          `protobuf:"bytes,2,opt,name=scanId,proto3" json:"scanId,omitempty"`
	PiquantCommand string          `protobuf:"bytes,3,opt,name=piquantCommand,proto3" json:"piquantCommand,omitempty"`
}

func (x *QuantLastOutputGetReq) Reset() {
	*x = QuantLastOutputGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quantification_retrieval_msgs_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuantLastOutputGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuantLastOutputGetReq) ProtoMessage() {}

func (x *QuantLastOutputGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_quantification_retrieval_msgs_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuantLastOutputGetReq.ProtoReflect.Descriptor instead.
func (*QuantLastOutputGetReq) Descriptor() ([]byte, []int) {
	return file_quantification_retrieval_msgs_proto_rawDescGZIP(), []int{10}
}

func (x *QuantLastOutputGetReq) GetOutputType() QuantOutputType {
	if x != nil {
		return x.OutputType
	}
	return QuantOutputType_QO_UNKNOWN
}

func (x *QuantLastOutputGetReq) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *QuantLastOutputGetReq) GetPiquantCommand() string {
	if x != nil {
		return x.PiquantCommand
	}
	return ""
}

type QuantLastOutputGetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *QuantLastOutputGetResp) Reset() {
	*x = QuantLastOutputGetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quantification_retrieval_msgs_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuantLastOutputGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuantLastOutputGetResp) ProtoMessage() {}

func (x *QuantLastOutputGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_quantification_retrieval_msgs_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuantLastOutputGetResp.ProtoReflect.Descriptor instead.
func (*QuantLastOutputGetResp) Descriptor() ([]byte, []int) {
	return file_quantification_retrieval_msgs_proto_rawDescGZIP(), []int{11}
}

func (x *QuantLastOutputGetResp) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

var File_quantification_retrieval_msgs_proto protoreflect.FileDescriptor

var file_quantification_retrieval_msgs_proto_rawDesc = []byte{
	0x0a, 0x23, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2d, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x2d, 0x6d, 0x73, 0x67, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x14, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2d, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a, 0x0c, 0x51,
	0x75, 0x61, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x31, 0x0a, 0x0c, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x52, 0x0c, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x3f,
	0x0a, 0x0d, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x2e, 0x0a, 0x06, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x06, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x73, 0x22,
	0x49, 0x0a, 0x0b, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x4f, 0x6e, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x73,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x4f, 0x6e, 0x6c, 0x79, 0x22, 0x65, 0x0a, 0x0c, 0x51, 0x75,
	0x61, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x07, 0x73, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x51, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x23, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x51, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x2b, 0x0a, 0x0f, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x30,
	0x0a, 0x10, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x22, 0x44, 0x0a, 0x0e, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x6c, 0x6f, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c,
	0x6f, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2b, 0x0a, 0x0f, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x4c,
	0x6f, 0x67, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x67,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x2e, 0x0a, 0x12, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x52, 0x61, 0x77, 0x44,
	0x61, 0x74, 0x61, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x71, 0x75, 0x61,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x49, 0x64, 0x22, 0x29, 0x0a, 0x13, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x52, 0x61, 0x77, 0x44,
	0x61, 0x74, 0x61, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x89,
	0x01, 0x0a, 0x15, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x30, 0x0a, 0x0a, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x51,
	0x75, 0x61, 0x6e, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63,
	0x61, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x61, 0x6e,
	0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x69, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x69, 0x71, 0x75,
	0x61, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x30, 0x0a, 0x16, 0x51, 0x75,
	0x61, 0x6e, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2a, 0x3a, 0x0a, 0x0f,
	0x51, 0x75, 0x61, 0x6e, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0e, 0x0a, 0x0a, 0x51, 0x4f, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x51, 0x4f, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06,
	0x51, 0x4f, 0x5f, 0x4c, 0x4f, 0x47, 0x10, 0x02, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_quantification_retrieval_msgs_proto_rawDescOnce sync.Once
	file_quantification_retrieval_msgs_proto_rawDescData = file_quantification_retrieval_msgs_proto_rawDesc
)

func file_quantification_retrieval_msgs_proto_rawDescGZIP() []byte {
	file_quantification_retrieval_msgs_proto_rawDescOnce.Do(func() {
		file_quantification_retrieval_msgs_proto_rawDescData = protoimpl.X.CompressGZIP(file_quantification_retrieval_msgs_proto_rawDescData)
	})
	return file_quantification_retrieval_msgs_proto_rawDescData
}

var file_quantification_retrieval_msgs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_quantification_retrieval_msgs_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_quantification_retrieval_msgs_proto_goTypes = []interface{}{
	(QuantOutputType)(0),           // 0: QuantOutputType
	(*QuantListReq)(nil),           // 1: QuantListReq
	(*QuantListResp)(nil),          // 2: QuantListResp
	(*QuantGetReq)(nil),            // 3: QuantGetReq
	(*QuantGetResp)(nil),           // 4: QuantGetResp
	(*QuantLogListReq)(nil),        // 5: QuantLogListReq
	(*QuantLogListResp)(nil),       // 6: QuantLogListResp
	(*QuantLogGetReq)(nil),         // 7: QuantLogGetReq
	(*QuantLogGetResp)(nil),        // 8: QuantLogGetResp
	(*QuantRawDataGetReq)(nil),     // 9: QuantRawDataGetReq
	(*QuantRawDataGetResp)(nil),    // 10: QuantRawDataGetResp
	(*QuantLastOutputGetReq)(nil),  // 11: QuantLastOutputGetReq
	(*QuantLastOutputGetResp)(nil), // 12: QuantLastOutputGetResp
	(*SearchParams)(nil),           // 13: SearchParams
	(*QuantificationSummary)(nil),  // 14: QuantificationSummary
	(*Quantification)(nil),         // 15: Quantification
}
var file_quantification_retrieval_msgs_proto_depIdxs = []int32{
	13, // 0: QuantListReq.searchParams:type_name -> SearchParams
	14, // 1: QuantListResp.quants:type_name -> QuantificationSummary
	14, // 2: QuantGetResp.summary:type_name -> QuantificationSummary
	15, // 3: QuantGetResp.data:type_name -> Quantification
	0,  // 4: QuantLastOutputGetReq.outputType:type_name -> QuantOutputType
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_quantification_retrieval_msgs_proto_init() }
func file_quantification_retrieval_msgs_proto_init() {
	if File_quantification_retrieval_msgs_proto != nil {
		return
	}
	file_quantification_meta_proto_init()
	file_quantification_proto_init()
	file_search_params_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_quantification_retrieval_msgs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuantListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quantification_retrieval_msgs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuantListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quantification_retrieval_msgs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuantGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quantification_retrieval_msgs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuantGetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quantification_retrieval_msgs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuantLogListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quantification_retrieval_msgs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuantLogListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quantification_retrieval_msgs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuantLogGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quantification_retrieval_msgs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuantLogGetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quantification_retrieval_msgs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuantRawDataGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quantification_retrieval_msgs_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuantRawDataGetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quantification_retrieval_msgs_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuantLastOutputGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quantification_retrieval_msgs_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuantLastOutputGetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quantification_retrieval_msgs_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quantification_retrieval_msgs_proto_goTypes,
		DependencyIndexes: file_quantification_retrieval_msgs_proto_depIdxs,
		EnumInfos:         file_quantification_retrieval_msgs_proto_enumTypes,
		MessageInfos:      file_quantification_retrieval_msgs_proto_msgTypes,
	}.Build()
	File_quantification_retrieval_msgs_proto = out.File
	file_quantification_retrieval_msgs_proto_rawDesc = nil
	file_quantification_retrieval_msgs_proto_goTypes = nil
	file_quantification_retrieval_msgs_proto_depIdxs = nil
}
