// Copyright (c) 2018-2022 California Institute of Technology (“Caltech”). U.S.
// Government sponsorship acknowledged.
// All rights reserved.
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
// * Redistributions of source code must retain the above copyright notice, this
//   list of conditions and the following disclaimer.
// * Redistributions in binary form must reproduce the above copyright notice,
//   this list of conditions and the following disclaimer in the documentation
//   and/or other materials provided with the distribution.
// * Neither the name of Caltech nor its operating division, the Jet Propulsion
//   Laboratory, nor the names of its contributors may be used to endorse or
//   promote products derived from this software without specific prior written
//   permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.1-devel
// 	protoc        v3.7.1
// source: data-formats/quantification.proto

package protos

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Quantification_QuantDataType int32

const (
	Quantification_QT_FLOAT Quantification_QuantDataType = 0
	Quantification_QT_INT   Quantification_QuantDataType = 1
)

// Enum value maps for Quantification_QuantDataType.
var (
	Quantification_QuantDataType_name = map[int32]string{
		0: "QT_FLOAT",
		1: "QT_INT",
	}
	Quantification_QuantDataType_value = map[string]int32{
		"QT_FLOAT": 0,
		"QT_INT":   1,
	}
)

func (x Quantification_QuantDataType) Enum() *Quantification_QuantDataType {
	p := new(Quantification_QuantDataType)
	*p = x
	return p
}

func (x Quantification_QuantDataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Quantification_QuantDataType) Descriptor() protoreflect.EnumDescriptor {
	return file_data_formats_quantification_proto_enumTypes[0].Descriptor()
}

func (Quantification_QuantDataType) Type() protoreflect.EnumType {
	return &file_data_formats_quantification_proto_enumTypes[0]
}

func (x Quantification_QuantDataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Quantification_QuantDataType.Descriptor instead.
func (Quantification_QuantDataType) EnumDescriptor() ([]byte, []int) {
	return file_data_formats_quantification_proto_rawDescGZIP(), []int{0, 0}
}

type Quantification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Labels      []string                           `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	Types       []Quantification_QuantDataType     `protobuf:"varint,2,rep,packed,name=types,proto3,enum=Quantification_QuantDataType" json:"types,omitempty"`
	LocationSet []*Quantification_QuantLocationSet `protobuf:"bytes,3,rep,name=locationSet,proto3" json:"locationSet,omitempty"`
}

func (x *Quantification) Reset() {
	*x = Quantification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_formats_quantification_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Quantification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quantification) ProtoMessage() {}

func (x *Quantification) ProtoReflect() protoreflect.Message {
	mi := &file_data_formats_quantification_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quantification.ProtoReflect.Descriptor instead.
func (*Quantification) Descriptor() ([]byte, []int) {
	return file_data_formats_quantification_proto_rawDescGZIP(), []int{0}
}

func (x *Quantification) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Quantification) GetTypes() []Quantification_QuantDataType {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *Quantification) GetLocationSet() []*Quantification_QuantLocationSet {
	if x != nil {
		return x.LocationSet
	}
	return nil
}

type Quantification_QuantLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pmc    int32                                         `protobuf:"varint,1,opt,name=pmc,proto3" json:"pmc,omitempty"`
	Rtt    int32                                         `protobuf:"varint,2,opt,name=rtt,proto3" json:"rtt,omitempty"`
	Sclk   int32                                         `protobuf:"varint,3,opt,name=sclk,proto3" json:"sclk,omitempty"` //string filename=4;
	Values []*Quantification_QuantLocation_QuantDataItem `protobuf:"bytes,5,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *Quantification_QuantLocation) Reset() {
	*x = Quantification_QuantLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_formats_quantification_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Quantification_QuantLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quantification_QuantLocation) ProtoMessage() {}

func (x *Quantification_QuantLocation) ProtoReflect() protoreflect.Message {
	mi := &file_data_formats_quantification_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quantification_QuantLocation.ProtoReflect.Descriptor instead.
func (*Quantification_QuantLocation) Descriptor() ([]byte, []int) {
	return file_data_formats_quantification_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Quantification_QuantLocation) GetPmc() int32 {
	if x != nil {
		return x.Pmc
	}
	return 0
}

func (x *Quantification_QuantLocation) GetRtt() int32 {
	if x != nil {
		return x.Rtt
	}
	return 0
}

func (x *Quantification_QuantLocation) GetSclk() int32 {
	if x != nil {
		return x.Sclk
	}
	return 0
}

func (x *Quantification_QuantLocation) GetValues() []*Quantification_QuantLocation_QuantDataItem {
	if x != nil {
		return x.Values
	}
	return nil
}

type Quantification_QuantLocationSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Detector string                          `protobuf:"bytes,1,opt,name=detector,proto3" json:"detector,omitempty"`
	Location []*Quantification_QuantLocation `protobuf:"bytes,2,rep,name=location,proto3" json:"location,omitempty"`
}

func (x *Quantification_QuantLocationSet) Reset() {
	*x = Quantification_QuantLocationSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_formats_quantification_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Quantification_QuantLocationSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quantification_QuantLocationSet) ProtoMessage() {}

func (x *Quantification_QuantLocationSet) ProtoReflect() protoreflect.Message {
	mi := &file_data_formats_quantification_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quantification_QuantLocationSet.ProtoReflect.Descriptor instead.
func (*Quantification_QuantLocationSet) Descriptor() ([]byte, []int) {
	return file_data_formats_quantification_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Quantification_QuantLocationSet) GetDetector() string {
	if x != nil {
		return x.Detector
	}
	return ""
}

func (x *Quantification_QuantLocationSet) GetLocation() []*Quantification_QuantLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

type Quantification_QuantLocation_QuantDataItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fvalue float32 `protobuf:"fixed32,2,opt,name=fvalue,proto3" json:"fvalue,omitempty"`
	Ivalue int32   `protobuf:"varint,3,opt,name=ivalue,proto3" json:"ivalue,omitempty"`
}

func (x *Quantification_QuantLocation_QuantDataItem) Reset() {
	*x = Quantification_QuantLocation_QuantDataItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_formats_quantification_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Quantification_QuantLocation_QuantDataItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quantification_QuantLocation_QuantDataItem) ProtoMessage() {}

func (x *Quantification_QuantLocation_QuantDataItem) ProtoReflect() protoreflect.Message {
	mi := &file_data_formats_quantification_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quantification_QuantLocation_QuantDataItem.ProtoReflect.Descriptor instead.
func (*Quantification_QuantLocation_QuantDataItem) Descriptor() ([]byte, []int) {
	return file_data_formats_quantification_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Quantification_QuantLocation_QuantDataItem) GetFvalue() float32 {
	if x != nil {
		return x.Fvalue
	}
	return 0
}

func (x *Quantification_QuantLocation_QuantDataItem) GetIvalue() int32 {
	if x != nil {
		return x.Ivalue
	}
	return 0
}

var File_data_formats_quantification_proto protoreflect.FileDescriptor

var file_data_formats_quantification_proto_rawDesc = []byte{
	0x0a, 0x21, 0x64, 0x61, 0x74, 0x61, 0x2d, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x2f, 0x71,
	0x75, 0x61, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x87, 0x04, 0x0a, 0x0e, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x33,
	0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x1d, 0x2e,
	0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51,
	0x75, 0x61, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x12, 0x42, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x51, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x52, 0x0b, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x1a, 0xcd, 0x01, 0x0a, 0x0d, 0x51, 0x75, 0x61, 0x6e,
	0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6d, 0x63,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x6d, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x72,
	0x74, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x74, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x63, 0x6c, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x63, 0x6c,
	0x6b, 0x12, 0x43, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2b, 0x2e, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x3f, 0x0a, 0x0d, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x66, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x69, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x69, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x69, 0x0a, 0x10, 0x51, 0x75, 0x61, 0x6e, 0x74,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64,
	0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x39, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x51, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x61, 0x6e, 0x74,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x29, 0x0a, 0x0d, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x51, 0x54, 0x5f, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x51, 0x54, 0x5f, 0x49, 0x4e, 0x54, 0x10, 0x01, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_data_formats_quantification_proto_rawDescOnce sync.Once
	file_data_formats_quantification_proto_rawDescData = file_data_formats_quantification_proto_rawDesc
)

func file_data_formats_quantification_proto_rawDescGZIP() []byte {
	file_data_formats_quantification_proto_rawDescOnce.Do(func() {
		file_data_formats_quantification_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_formats_quantification_proto_rawDescData)
	})
	return file_data_formats_quantification_proto_rawDescData
}

var file_data_formats_quantification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_data_formats_quantification_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_data_formats_quantification_proto_goTypes = []interface{}{
	(Quantification_QuantDataType)(0),                  // 0: Quantification.QuantDataType
	(*Quantification)(nil),                             // 1: Quantification
	(*Quantification_QuantLocation)(nil),               // 2: Quantification.QuantLocation
	(*Quantification_QuantLocationSet)(nil),            // 3: Quantification.QuantLocationSet
	(*Quantification_QuantLocation_QuantDataItem)(nil), // 4: Quantification.QuantLocation.QuantDataItem
}
var file_data_formats_quantification_proto_depIdxs = []int32{
	0, // 0: Quantification.types:type_name -> Quantification.QuantDataType
	3, // 1: Quantification.locationSet:type_name -> Quantification.QuantLocationSet
	4, // 2: Quantification.QuantLocation.values:type_name -> Quantification.QuantLocation.QuantDataItem
	2, // 3: Quantification.QuantLocationSet.location:type_name -> Quantification.QuantLocation
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_data_formats_quantification_proto_init() }
func file_data_formats_quantification_proto_init() {
	if File_data_formats_quantification_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_formats_quantification_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Quantification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_formats_quantification_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Quantification_QuantLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_formats_quantification_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Quantification_QuantLocationSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_formats_quantification_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Quantification_QuantLocation_QuantDataItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_formats_quantification_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_formats_quantification_proto_goTypes,
		DependencyIndexes: file_data_formats_quantification_proto_depIdxs,
		EnumInfos:         file_data_formats_quantification_proto_enumTypes,
		MessageInfos:      file_data_formats_quantification_proto_msgTypes,
	}.Build()
	File_data_formats_quantification_proto = out.File
	file_data_formats_quantification_proto_rawDesc = nil
	file_data_formats_quantification_proto_goTypes = nil
	file_data_formats_quantification_proto_depIdxs = nil
}
