// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: repository-msgs.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// requires(EDIT_EXPRESSION)
type SourceRepositoryListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceRepositoryListReq) Reset() {
	*x = SourceRepositoryListReq{}
	mi := &file_repository_msgs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceRepositoryListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceRepositoryListReq) ProtoMessage() {}

func (x *SourceRepositoryListReq) ProtoReflect() protoreflect.Message {
	mi := &file_repository_msgs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceRepositoryListReq.ProtoReflect.Descriptor instead.
func (*SourceRepositoryListReq) Descriptor() ([]byte, []int) {
	return file_repository_msgs_proto_rawDescGZIP(), []int{0}
}

type SourceRepositoryListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repositories  []*SourceRepository    `protobuf:"bytes,1,rep,name=repositories,proto3" json:"repositories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceRepositoryListResp) Reset() {
	*x = SourceRepositoryListResp{}
	mi := &file_repository_msgs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceRepositoryListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceRepositoryListResp) ProtoMessage() {}

func (x *SourceRepositoryListResp) ProtoReflect() protoreflect.Message {
	mi := &file_repository_msgs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceRepositoryListResp.ProtoReflect.Descriptor instead.
func (*SourceRepositoryListResp) Descriptor() ([]byte, []int) {
	return file_repository_msgs_proto_rawDescGZIP(), []int{1}
}

func (x *SourceRepositoryListResp) GetRepositories() []*SourceRepository {
	if x != nil {
		return x.Repositories
	}
	return nil
}

// requires(EDIT_EXPRESSION)
type SourceRepositorySetReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If id is not set, it creates a new one, otherwise tries to overwrite the one with that id
	Repository    *SourceRepository `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceRepositorySetReq) Reset() {
	*x = SourceRepositorySetReq{}
	mi := &file_repository_msgs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceRepositorySetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceRepositorySetReq) ProtoMessage() {}

func (x *SourceRepositorySetReq) ProtoReflect() protoreflect.Message {
	mi := &file_repository_msgs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceRepositorySetReq.ProtoReflect.Descriptor instead.
func (*SourceRepositorySetReq) Descriptor() ([]byte, []int) {
	return file_repository_msgs_proto_rawDescGZIP(), []int{2}
}

func (x *SourceRepositorySetReq) GetRepository() *SourceRepository {
	if x != nil {
		return x.Repository
	}
	return nil
}

type SourceRepositorySetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    *SourceRepository      `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceRepositorySetResp) Reset() {
	*x = SourceRepositorySetResp{}
	mi := &file_repository_msgs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceRepositorySetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceRepositorySetResp) ProtoMessage() {}

func (x *SourceRepositorySetResp) ProtoReflect() protoreflect.Message {
	mi := &file_repository_msgs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceRepositorySetResp.ProtoReflect.Descriptor instead.
func (*SourceRepositorySetResp) Descriptor() ([]byte, []int) {
	return file_repository_msgs_proto_rawDescGZIP(), []int{3}
}

func (x *SourceRepositorySetResp) GetRepository() *SourceRepository {
	if x != nil {
		return x.Repository
	}
	return nil
}

// requires(EDIT_EXPRESSION)
type SourceRepositoryDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceRepositoryDeleteReq) Reset() {
	*x = SourceRepositoryDeleteReq{}
	mi := &file_repository_msgs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceRepositoryDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceRepositoryDeleteReq) ProtoMessage() {}

func (x *SourceRepositoryDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_repository_msgs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceRepositoryDeleteReq.ProtoReflect.Descriptor instead.
func (*SourceRepositoryDeleteReq) Descriptor() ([]byte, []int) {
	return file_repository_msgs_proto_rawDescGZIP(), []int{4}
}

func (x *SourceRepositoryDeleteReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SourceRepositoryDeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceRepositoryDeleteResp) Reset() {
	*x = SourceRepositoryDeleteResp{}
	mi := &file_repository_msgs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceRepositoryDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceRepositoryDeleteResp) ProtoMessage() {}

func (x *SourceRepositoryDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_repository_msgs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceRepositoryDeleteResp.ProtoReflect.Descriptor instead.
func (*SourceRepositoryDeleteResp) Descriptor() ([]byte, []int) {
	return file_repository_msgs_proto_rawDescGZIP(), []int{5}
}

var File_repository_msgs_proto protoreflect.FileDescriptor

const file_repository_msgs_proto_rawDesc = "" +
	"\n" +
	"\x15repository-msgs.proto\x1a\x10repository.proto\"\x19\n" +
	"\x17SourceRepositoryListReq\"Q\n" +
	"\x18SourceRepositoryListResp\x125\n" +
	"\frepositories\x18\x01 \x03(\v2\x11.SourceRepositoryR\frepositories\"K\n" +
	"\x16SourceRepositorySetReq\x121\n" +
	"\n" +
	"repository\x18\x01 \x01(\v2\x11.SourceRepositoryR\n" +
	"repository\"L\n" +
	"\x17SourceRepositorySetResp\x121\n" +
	"\n" +
	"repository\x18\x01 \x01(\v2\x11.SourceRepositoryR\n" +
	"repository\"+\n" +
	"\x19SourceRepositoryDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1c\n" +
	"\x1aSourceRepositoryDeleteRespB\n" +
	"Z\b.;protosb\x06proto3"

var (
	file_repository_msgs_proto_rawDescOnce sync.Once
	file_repository_msgs_proto_rawDescData []byte
)

func file_repository_msgs_proto_rawDescGZIP() []byte {
	file_repository_msgs_proto_rawDescOnce.Do(func() {
		file_repository_msgs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repository_msgs_proto_rawDesc), len(file_repository_msgs_proto_rawDesc)))
	})
	return file_repository_msgs_proto_rawDescData
}

var file_repository_msgs_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_repository_msgs_proto_goTypes = []any{
	(*SourceRepositoryListReq)(nil),    // 0: SourceRepositoryListReq
	(*SourceRepositoryListResp)(nil),   // 1: SourceRepositoryListResp
	(*SourceRepositorySetReq)(nil),     // 2: SourceRepositorySetReq
	(*SourceRepositorySetResp)(nil),    // 3: SourceRepositorySetResp
	(*SourceRepositoryDeleteReq)(nil),  // 4: SourceRepositoryDeleteReq
	(*SourceRepositoryDeleteResp)(nil), // 5: SourceRepositoryDeleteResp
	(*SourceRepository)(nil),           // 6: SourceRepository
}
var file_repository_msgs_proto_depIdxs = []int32{
	6, // 0: SourceRepositoryListResp.repositories:type_name -> SourceRepository
	6, // 1: SourceRepositorySetReq.repository:type_name -> SourceRepository
	6, // 2: SourceRepositorySetResp.repository:type_name -> SourceRepository
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_repository_msgs_proto_init() }
func file_repository_msgs_proto_init() {
	if File_repository_msgs_proto != nil {
		return
	}
	file_repository_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repository_msgs_proto_rawDesc), len(file_repository_msgs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_repository_msgs_proto_goTypes,
		DependencyIndexes: file_repository_msgs_proto_depIdxs,
		MessageInfos:      file_repository_msgs_proto_msgTypes,
	}.Build()
	File_repository_msgs_proto = out.File
	file_repository_msgs_proto_goTypes = nil
	file_repository_msgs_proto_depIdxs = nil
}
