// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: scan-beam-location-msgs.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// requires(NONE)
type ScanBeamLocationsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScanId  string          `protobuf:"bytes,1,opt,name=scanId,proto3" json:"scanId,omitempty"`
	Entries *ScanEntryRange `protobuf:"bytes,2,opt,name=entries,proto3" json:"entries,omitempty"`
}

func (x *ScanBeamLocationsReq) Reset() {
	*x = ScanBeamLocationsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_beam_location_msgs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanBeamLocationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanBeamLocationsReq) ProtoMessage() {}

func (x *ScanBeamLocationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_scan_beam_location_msgs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanBeamLocationsReq.ProtoReflect.Descriptor instead.
func (*ScanBeamLocationsReq) Descriptor() ([]byte, []int) {
	return file_scan_beam_location_msgs_proto_rawDescGZIP(), []int{0}
}

func (x *ScanBeamLocationsReq) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *ScanBeamLocationsReq) GetEntries() *ScanEntryRange {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ScanBeamLocationsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BeamLocations []*Coordinate3D `protobuf:"bytes,1,rep,name=beamLocations,proto3" json:"beamLocations,omitempty"`
}

func (x *ScanBeamLocationsResp) Reset() {
	*x = ScanBeamLocationsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_beam_location_msgs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanBeamLocationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanBeamLocationsResp) ProtoMessage() {}

func (x *ScanBeamLocationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_scan_beam_location_msgs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanBeamLocationsResp.ProtoReflect.Descriptor instead.
func (*ScanBeamLocationsResp) Descriptor() ([]byte, []int) {
	return file_scan_beam_location_msgs_proto_rawDescGZIP(), []int{1}
}

func (x *ScanBeamLocationsResp) GetBeamLocations() []*Coordinate3D {
	if x != nil {
		return x.BeamLocations
	}
	return nil
}

type ClientBeamLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PMC        int32         `protobuf:"varint,1,opt,name=PMC,proto3" json:"PMC,omitempty"`
	Coordinate *Coordinate3D `protobuf:"bytes,2,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
}

func (x *ClientBeamLocation) Reset() {
	*x = ClientBeamLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_beam_location_msgs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientBeamLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientBeamLocation) ProtoMessage() {}

func (x *ClientBeamLocation) ProtoReflect() protoreflect.Message {
	mi := &file_scan_beam_location_msgs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientBeamLocation.ProtoReflect.Descriptor instead.
func (*ClientBeamLocation) Descriptor() ([]byte, []int) {
	return file_scan_beam_location_msgs_proto_rawDescGZIP(), []int{2}
}

func (x *ClientBeamLocation) GetPMC() int32 {
	if x != nil {
		return x.PMC
	}
	return 0
}

func (x *ClientBeamLocation) GetCoordinate() *Coordinate3D {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

type ClientBeamLocations struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Locations []*ClientBeamLocation `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
}

func (x *ClientBeamLocations) Reset() {
	*x = ClientBeamLocations{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_beam_location_msgs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientBeamLocations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientBeamLocations) ProtoMessage() {}

func (x *ClientBeamLocations) ProtoReflect() protoreflect.Message {
	mi := &file_scan_beam_location_msgs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientBeamLocations.ProtoReflect.Descriptor instead.
func (*ClientBeamLocations) Descriptor() ([]byte, []int) {
	return file_scan_beam_location_msgs_proto_rawDescGZIP(), []int{3}
}

func (x *ClientBeamLocations) GetLocations() []*ClientBeamLocation {
	if x != nil {
		return x.Locations
	}
	return nil
}

var File_scan_beam_location_msgs_proto protoreflect.FileDescriptor

var file_scan_beam_location_msgs_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x63, 0x61, 0x6e, 0x2d, 0x62, 0x65, 0x61, 0x6d, 0x2d, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x18, 0x73, 0x63, 0x61, 0x6e, 0x2d, 0x62, 0x65, 0x61, 0x6d, 0x2d, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x73, 0x63, 0x61, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a, 0x14, 0x53, 0x63, 0x61, 0x6e, 0x42, 0x65, 0x61,
	0x6d, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x63, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x63, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x22, 0x4c, 0x0a, 0x15, 0x53, 0x63, 0x61, 0x6e, 0x42, 0x65, 0x61, 0x6d, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x0d, 0x62, 0x65, 0x61,
	0x6d, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x33, 0x44, 0x52,
	0x0d, 0x62, 0x65, 0x61, 0x6d, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x55,
	0x0a, 0x12, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x65, 0x61, 0x6d, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x4d, 0x43, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x50, 0x4d, 0x43, 0x12, 0x2d, 0x0a, 0x0a, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69,
	0x6e, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x43, 0x6f, 0x6f,
	0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x33, 0x44, 0x52, 0x0a, 0x63, 0x6f, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x61, 0x74, 0x65, 0x22, 0x48, 0x0a, 0x13, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42,
	0x65, 0x61, 0x6d, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x31, 0x0a, 0x09,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x65, 0x61, 0x6d, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42,
	0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_scan_beam_location_msgs_proto_rawDescOnce sync.Once
	file_scan_beam_location_msgs_proto_rawDescData = file_scan_beam_location_msgs_proto_rawDesc
)

func file_scan_beam_location_msgs_proto_rawDescGZIP() []byte {
	file_scan_beam_location_msgs_proto_rawDescOnce.Do(func() {
		file_scan_beam_location_msgs_proto_rawDescData = protoimpl.X.CompressGZIP(file_scan_beam_location_msgs_proto_rawDescData)
	})
	return file_scan_beam_location_msgs_proto_rawDescData
}

var file_scan_beam_location_msgs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_scan_beam_location_msgs_proto_goTypes = []interface{}{
	(*ScanBeamLocationsReq)(nil),  // 0: ScanBeamLocationsReq
	(*ScanBeamLocationsResp)(nil), // 1: ScanBeamLocationsResp
	(*ClientBeamLocation)(nil),    // 2: ClientBeamLocation
	(*ClientBeamLocations)(nil),   // 3: ClientBeamLocations
	(*ScanEntryRange)(nil),        // 4: ScanEntryRange
	(*Coordinate3D)(nil),          // 5: Coordinate3D
}
var file_scan_beam_location_msgs_proto_depIdxs = []int32{
	4, // 0: ScanBeamLocationsReq.entries:type_name -> ScanEntryRange
	5, // 1: ScanBeamLocationsResp.beamLocations:type_name -> Coordinate3D
	5, // 2: ClientBeamLocation.coordinate:type_name -> Coordinate3D
	2, // 3: ClientBeamLocations.locations:type_name -> ClientBeamLocation
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_scan_beam_location_msgs_proto_init() }
func file_scan_beam_location_msgs_proto_init() {
	if File_scan_beam_location_msgs_proto != nil {
		return
	}
	file_scan_beam_location_proto_init()
	file_scan_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_scan_beam_location_msgs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanBeamLocationsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_beam_location_msgs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanBeamLocationsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_beam_location_msgs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientBeamLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_beam_location_msgs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientBeamLocations); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scan_beam_location_msgs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scan_beam_location_msgs_proto_goTypes,
		DependencyIndexes: file_scan_beam_location_msgs_proto_depIdxs,
		MessageInfos:      file_scan_beam_location_msgs_proto_msgTypes,
	}.Build()
	File_scan_beam_location_msgs_proto = out.File
	file_scan_beam_location_msgs_proto_rawDesc = nil
	file_scan_beam_location_msgs_proto_goTypes = nil
	file_scan_beam_location_msgs_proto_depIdxs = nil
}
