// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: scan.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScanDataType int32

const (
	ScanDataType_SD_UNKNOWN  ScanDataType = 0 // https://protobuf.dev/programming-guides/dos-donts/ says specify an unknown as 0
	ScanDataType_SD_IMAGE    ScanDataType = 1
	ScanDataType_SD_XRF      ScanDataType = 2
	ScanDataType_SD_RGBU     ScanDataType = 3
	ScanDataType_SD_BIGIMAGE ScanDataType = 4 // If the scan has "big image" data - stored as pyramids with tiled layers (see BigScan)
)

// Enum value maps for ScanDataType.
var (
	ScanDataType_name = map[int32]string{
		0: "SD_UNKNOWN",
		1: "SD_IMAGE",
		2: "SD_XRF",
		3: "SD_RGBU",
		4: "SD_BIGIMAGE",
	}
	ScanDataType_value = map[string]int32{
		"SD_UNKNOWN":  0,
		"SD_IMAGE":    1,
		"SD_XRF":      2,
		"SD_RGBU":     3,
		"SD_BIGIMAGE": 4,
	}
)

func (x ScanDataType) Enum() *ScanDataType {
	p := new(ScanDataType)
	*p = x
	return p
}

func (x ScanDataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScanDataType) Descriptor() protoreflect.EnumDescriptor {
	return file_scan_proto_enumTypes[0].Descriptor()
}

func (ScanDataType) Type() protoreflect.EnumType {
	return &file_scan_proto_enumTypes[0]
}

func (x ScanDataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScanDataType.Descriptor instead.
func (ScanDataType) EnumDescriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{0}
}

type ScanInstrument int32

const (
	ScanInstrument_UNKNOWN_INSTRUMENT ScanInstrument = 0 // https://protobuf.dev/programming-guides/dos-donts/ says specify an unknown as 0
	ScanInstrument_PIXL_FM            ScanInstrument = 1 // PIXL flight model, now located on planet Mars
	ScanInstrument_PIXL_EM            ScanInstrument = 2 // PIXL engineering model
	ScanInstrument_JPL_BREADBOARD     ScanInstrument = 3 // JPL PIXL lab Breadboard
	ScanInstrument_SBU_BREADBOARD     ScanInstrument = 4 // Stony Brook Breadboard
	ScanInstrument_BRUKER             ScanInstrument = 5 // TODO: Remove this, never implemented it anyway! Replace with GENERIC_XRF
	ScanInstrument_GENERIC_XRF        ScanInstrument = 6 // Generic XRF, behaves like PIXL but from a commercial provider, eg Bruker
	ScanInstrument_GENERIC_WDS        ScanInstrument = 7 // Wavelength Dispursive Spectroscopy instrument (??)
	ScanInstrument_GENERIC_SEM        ScanInstrument = 8 // Scanning electron microscope
)

// Enum value maps for ScanInstrument.
var (
	ScanInstrument_name = map[int32]string{
		0: "UNKNOWN_INSTRUMENT",
		1: "PIXL_FM",
		2: "PIXL_EM",
		3: "JPL_BREADBOARD",
		4: "SBU_BREADBOARD",
		5: "BRUKER",
		6: "GENERIC_XRF",
		7: "GENERIC_WDS",
		8: "GENERIC_SEM",
	}
	ScanInstrument_value = map[string]int32{
		"UNKNOWN_INSTRUMENT": 0,
		"PIXL_FM":            1,
		"PIXL_EM":            2,
		"JPL_BREADBOARD":     3,
		"SBU_BREADBOARD":     4,
		"BRUKER":             5,
		"GENERIC_XRF":        6,
		"GENERIC_WDS":        7,
		"GENERIC_SEM":        8,
	}
)

func (x ScanInstrument) Enum() *ScanInstrument {
	p := new(ScanInstrument)
	*p = x
	return p
}

func (x ScanInstrument) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScanInstrument) Descriptor() protoreflect.EnumDescriptor {
	return file_scan_proto_enumTypes[1].Descriptor()
}

func (ScanInstrument) Type() protoreflect.EnumType {
	return &file_scan_proto_enumTypes[1]
}

func (x ScanInstrument) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScanInstrument.Descriptor instead.
func (ScanInstrument) EnumDescriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{1}
}

type ScanMetaDataType int32

const (
	ScanMetaDataType_MT_FLOAT  ScanMetaDataType = 0
	ScanMetaDataType_MT_INT    ScanMetaDataType = 1
	ScanMetaDataType_MT_STRING ScanMetaDataType = 2
)

// Enum value maps for ScanMetaDataType.
var (
	ScanMetaDataType_name = map[int32]string{
		0: "MT_FLOAT",
		1: "MT_INT",
		2: "MT_STRING",
	}
	ScanMetaDataType_value = map[string]int32{
		"MT_FLOAT":  0,
		"MT_INT":    1,
		"MT_STRING": 2,
	}
)

func (x ScanMetaDataType) Enum() *ScanMetaDataType {
	p := new(ScanMetaDataType)
	*p = x
	return p
}

func (x ScanMetaDataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScanMetaDataType) Descriptor() protoreflect.EnumDescriptor {
	return file_scan_proto_enumTypes[2].Descriptor()
}

func (ScanMetaDataType) Type() protoreflect.EnumType {
	return &file_scan_proto_enumTypes[2]
}

func (x ScanMetaDataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScanMetaDataType.Descriptor instead.
func (ScanMetaDataType) EnumDescriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{2}
}

type ScanItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID for this scan
	Id          string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`                    
	Title       string                    `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`             // Title to show for this scan
	Description string                    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // Description to show
	DataTypes   []*ScanItem_ScanTypeCount `protobuf:"bytes,4,rep,name=dataTypes,proto3" json:"dataTypes,omitempty"`
	// The instrument that collected the scan
	Instrument ScanInstrument `protobuf:"varint,5,opt,name=instrument,proto3,enum=ScanInstrument" json:"instrument,omitempty"`
	// Configuration name of the instrument as text
	// For PIXL, this is the detector config used, so we run quantifications with
	// the correct config
	InstrumentConfig string `protobuf:"bytes,6,opt,name=instrumentConfig,proto3" json:"instrumentConfig,omitempty"`
	// Unix time stamp for this scan (just to order it, so we don't care if this is the
	// time when the instrument did the scan, or when data was ingested into PIXLISE,
	// just need a time!)
	TimestampUnixSec uint32 `protobuf:"varint,7,opt,name=timestampUnixSec,proto3" json:"timestampUnixSec,omitempty"`
	// Meta-data for the scan to describe in an instrument-specific way when and where
	// it was collected
	//
	// NOTE: for PIXL scans, these will contain:
	// DriveId
	// SiteId, Site,
	// TargetId, Target
	// Sol
	// RTT (round-trip token)
	// SCLK
	Meta map[string]string `protobuf:"bytes,8,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Contents for the scan - what data types it has, and how many
	// NOTE: for PIXL scans, this will contain:
	// NormalSpectra (count)
	// DwellSpectra (count)
	// BulkSpectra (count)
	// MaxSpectra (count)
	// PseudoIntensities (count)
	ContentCounts map[string]int32  `protobuf:"bytes,9,rep,name=contentCounts,proto3" json:"contentCounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	CreatorUserId string            `protobuf:"bytes,10,opt,name=creatorUserId,proto3" json:"creatorUserId,omitempty"` // Optional, but dataset may have been uploaded by a given user
	Owner         *OwnershipSummary `protobuf:"bytes,11,opt,name=owner,proto3" json:"owner,omitempty" bson:"-"`                  
	Tags          []string          `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	// If we import multiple times, we save the import time in our scan item
	PreviousImportTimesUnixSec []uint32 `protobuf:"varint,13,rep,packed,name=previousImportTimesUnixSec,proto3" json:"previousImportTimesUnixSec,omitempty"`
	// Time stamp when we had a complete scan (have all normal spectra)
	CompleteTimeStampUnixSec uint32 `protobuf:"varint,14,opt,name=completeTimeStampUnixSec,proto3" json:"completeTimeStampUnixSec,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ScanItem) Reset() {
	*x = ScanItem{}
	mi := &file_scan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanItem) ProtoMessage() {}

func (x *ScanItem) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanItem.ProtoReflect.Descriptor instead.
func (*ScanItem) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{0}
}

func (x *ScanItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScanItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ScanItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScanItem) GetDataTypes() []*ScanItem_ScanTypeCount {
	if x != nil {
		return x.DataTypes
	}
	return nil
}

func (x *ScanItem) GetInstrument() ScanInstrument {
	if x != nil {
		return x.Instrument
	}
	return ScanInstrument_UNKNOWN_INSTRUMENT
}

func (x *ScanItem) GetInstrumentConfig() string {
	if x != nil {
		return x.InstrumentConfig
	}
	return ""
}

func (x *ScanItem) GetTimestampUnixSec() uint32 {
	if x != nil {
		return x.TimestampUnixSec
	}
	return 0
}

func (x *ScanItem) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ScanItem) GetContentCounts() map[string]int32 {
	if x != nil {
		return x.ContentCounts
	}
	return nil
}

func (x *ScanItem) GetCreatorUserId() string {
	if x != nil {
		return x.CreatorUserId
	}
	return ""
}

func (x *ScanItem) GetOwner() *OwnershipSummary {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *ScanItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ScanItem) GetPreviousImportTimesUnixSec() []uint32 {
	if x != nil {
		return x.PreviousImportTimesUnixSec
	}
	return nil
}

func (x *ScanItem) GetCompleteTimeStampUnixSec() uint32 {
	if x != nil {
		return x.CompleteTimeStampUnixSec
	}
	return 0
}

type ScanMetaDataItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NOTE: we store the meta label outside, so these are expected to sit
	// in a: map<int32, ScanMetaDataItem>
	// Where the map key is the meta label which references the strings
	// returned by ScanMetaLabelsResp
	//
	// Types that are valid to be assigned to Value:
	//
	//	*ScanMetaDataItem_Fvalue
	//	*ScanMetaDataItem_Ivalue
	//	*ScanMetaDataItem_Svalue
	Value         isScanMetaDataItem_Value `protobuf_oneof:"Value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanMetaDataItem) Reset() {
	*x = ScanMetaDataItem{}
	mi := &file_scan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanMetaDataItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanMetaDataItem) ProtoMessage() {}

func (x *ScanMetaDataItem) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanMetaDataItem.ProtoReflect.Descriptor instead.
func (*ScanMetaDataItem) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{1}
}

func (x *ScanMetaDataItem) GetValue() isScanMetaDataItem_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ScanMetaDataItem) GetFvalue() float32 {
	if x != nil {
		if x, ok := x.Value.(*ScanMetaDataItem_Fvalue); ok {
			return x.Fvalue
		}
	}
	return 0
}

func (x *ScanMetaDataItem) GetIvalue() int32 {
	if x != nil {
		if x, ok := x.Value.(*ScanMetaDataItem_Ivalue); ok {
			return x.Ivalue
		}
	}
	return 0
}

func (x *ScanMetaDataItem) GetSvalue() string {
	if x != nil {
		if x, ok := x.Value.(*ScanMetaDataItem_Svalue); ok {
			return x.Svalue
		}
	}
	return ""
}

type isScanMetaDataItem_Value interface {
	isScanMetaDataItem_Value()
}

type ScanMetaDataItem_Fvalue struct {
	Fvalue float32 `protobuf:"fixed32,1,opt,name=fvalue,proto3,oneof"`
}

type ScanMetaDataItem_Ivalue struct {
	Ivalue int32 `protobuf:"varint,2,opt,name=ivalue,proto3,oneof"`
}

type ScanMetaDataItem_Svalue struct {
	Svalue string `protobuf:"bytes,3,opt,name=svalue,proto3,oneof"`
}

func (*ScanMetaDataItem_Fvalue) isScanMetaDataItem_Value() {}

func (*ScanMetaDataItem_Ivalue) isScanMetaDataItem_Value() {}

func (*ScanMetaDataItem_Svalue) isScanMetaDataItem_Value() {}

type ScanEntryRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// We want to be able to list all entry indexes that we're querying
	// This can be just an array of numbers, but we allow encoding runs as
	// <start idx>, -1, <end idx>. Therefore if you need all entries, and
	// the scan has 100 entries, send up 0, -1, 99 and the API will interpret
	// this as needing indexes: 0, 1, 2, ... 98, 99
	// Of course, multiple runs can be encoded, so 0, -1, 4, 50, -1, 55
	// should mean 0, 1, 2, 3, 4, 50, 51, 52, 53, 54, 55
	Indexes       []int32 `protobuf:"varint,1,rep,packed,name=indexes,proto3" json:"indexes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanEntryRange) Reset() {
	*x = ScanEntryRange{}
	mi := &file_scan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanEntryRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanEntryRange) ProtoMessage() {}

func (x *ScanEntryRange) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanEntryRange.ProtoReflect.Descriptor instead.
func (*ScanEntryRange) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{2}
}

func (x *ScanEntryRange) GetIndexes() []int32 {
	if x != nil {
		return x.Indexes
	}
	return nil
}

type ScanAutoShareEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`  
	Viewers       *UserGroupList         `protobuf:"bytes,2,opt,name=viewers,proto3" json:"viewers,omitempty"`
	Editors       *UserGroupList         `protobuf:"bytes,3,opt,name=editors,proto3" json:"editors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanAutoShareEntry) Reset() {
	*x = ScanAutoShareEntry{}
	mi := &file_scan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanAutoShareEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanAutoShareEntry) ProtoMessage() {}

func (x *ScanAutoShareEntry) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanAutoShareEntry.ProtoReflect.Descriptor instead.
func (*ScanAutoShareEntry) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{3}
}

func (x *ScanAutoShareEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScanAutoShareEntry) GetViewers() *UserGroupList {
	if x != nil {
		return x.Viewers
	}
	return nil
}

func (x *ScanAutoShareEntry) GetEditors() *UserGroupList {
	if x != nil {
		return x.Editors
	}
	return nil
}

type JobGroupConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobGroupId    string                 `protobuf:"bytes,1,opt,name=jobGroupId,proto3" json:"jobGroupId,omitempty"`
	DockerImage   string                 `protobuf:"bytes,2,opt,name=dockerImage,proto3" json:"dockerImage,omitempty"`
	FastStart     bool                   `protobuf:"varint,3,opt,name=fastStart,proto3" json:"fastStart,omitempty"`
	NodeCount     int32                  `protobuf:"varint,4,opt,name=nodeCount,proto3" json:"nodeCount,omitempty"`
	NodeConfig    *JobConfig             `protobuf:"bytes,5,opt,name=nodeConfig,proto3" json:"nodeConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobGroupConfig) Reset() {
	*x = JobGroupConfig{}
	mi := &file_scan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobGroupConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobGroupConfig) ProtoMessage() {}

func (x *JobGroupConfig) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobGroupConfig.ProtoReflect.Descriptor instead.
func (*JobGroupConfig) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{4}
}

func (x *JobGroupConfig) GetJobGroupId() string {
	if x != nil {
		return x.JobGroupId
	}
	return ""
}

func (x *JobGroupConfig) GetDockerImage() string {
	if x != nil {
		return x.DockerImage
	}
	return ""
}

func (x *JobGroupConfig) GetFastStart() bool {
	if x != nil {
		return x.FastStart
	}
	return false
}

func (x *JobGroupConfig) GetNodeCount() int32 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *JobGroupConfig) GetNodeConfig() *JobConfig {
	if x != nil {
		return x.NodeConfig
	}
	return nil
}

type JobFilePath struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The remote file info
	RemoteBucket string `protobuf:"bytes,1,opt,name=remoteBucket,proto3" json:"remoteBucket,omitempty"`
	RemotePath   string `protobuf:"bytes,2,opt,name=remotePath,proto3" json:"remotePath,omitempty"`
	// Local copy
	LocalPath     string `protobuf:"bytes,3,opt,name=localPath,proto3" json:"localPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobFilePath) Reset() {
	*x = JobFilePath{}
	mi := &file_scan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobFilePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobFilePath) ProtoMessage() {}

func (x *JobFilePath) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobFilePath.ProtoReflect.Descriptor instead.
func (*JobFilePath) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{5}
}

func (x *JobFilePath) GetRemoteBucket() string {
	if x != nil {
		return x.RemoteBucket
	}
	return ""
}

func (x *JobFilePath) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *JobFilePath) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

type JobConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The job id
	JobId string `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	// What files are required to be present when running the job?
	RequiredFiles []*JobFilePath `protobuf:"bytes,2,rep,name=requiredFiles,proto3" json:"requiredFiles,omitempty"`
	// What command to execute
	Command string   `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Args    []string `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	// What to upload on completion (if file doesn't exist, it can be ignored with a warning)
	OutputFiles   []*JobFilePath `protobuf:"bytes,5,rep,name=outputFiles,proto3" json:"outputFiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobConfig) Reset() {
	*x = JobConfig{}
	mi := &file_scan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobConfig) ProtoMessage() {}

func (x *JobConfig) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobConfig.ProtoReflect.Descriptor instead.
func (*JobConfig) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{6}
}

func (x *JobConfig) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobConfig) GetRequiredFiles() []*JobFilePath {
	if x != nil {
		return x.RequiredFiles
	}
	return nil
}

func (x *JobConfig) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *JobConfig) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *JobConfig) GetOutputFiles() []*JobFilePath {
	if x != nil {
		return x.OutputFiles
	}
	return nil
}

// Client library side message types
type ClientMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryPMCs     []int32                `protobuf:"varint,1,rep,packed,name=EntryPMCs,proto3" json:"EntryPMCs,omitempty"`
	FloatValues   []float64              `protobuf:"fixed64,2,rep,packed,name=FloatValues,proto3" json:"FloatValues,omitempty"`
	IntValues     []int64                `protobuf:"varint,3,rep,packed,name=IntValues,proto3" json:"IntValues,omitempty"`
	StringValues  []string               `protobuf:"bytes,4,rep,name=StringValues,proto3" json:"StringValues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMap) Reset() {
	*x = ClientMap{}
	mi := &file_scan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMap) ProtoMessage() {}

func (x *ClientMap) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMap.ProtoReflect.Descriptor instead.
func (*ClientMap) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{7}
}

func (x *ClientMap) GetEntryPMCs() []int32 {
	if x != nil {
		return x.EntryPMCs
	}
	return nil
}

func (x *ClientMap) GetFloatValues() []float64 {
	if x != nil {
		return x.FloatValues
	}
	return nil
}

func (x *ClientMap) GetIntValues() []int64 {
	if x != nil {
		return x.IntValues
	}
	return nil
}

func (x *ClientMap) GetStringValues() []string {
	if x != nil {
		return x.StringValues
	}
	return nil
}

type ClientStringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strings       []string               `protobuf:"bytes,1,rep,name=Strings,proto3" json:"Strings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientStringList) Reset() {
	*x = ClientStringList{}
	mi := &file_scan_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStringList) ProtoMessage() {}

func (x *ClientStringList) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStringList.ProtoReflect.Descriptor instead.
func (*ClientStringList) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{8}
}

func (x *ClientStringList) GetStrings() []string {
	if x != nil {
		return x.Strings
	}
	return nil
}

// Contains the type and how many of each
// For PIXL:
// XRF (PMC count)
// IMAGE (MCC count+custom image count)
// RGBU (0 or 2)
type ScanItem_ScanTypeCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataType      ScanDataType           `protobuf:"varint,1,opt,name=dataType,proto3,enum=ScanDataType" json:"dataType,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanItem_ScanTypeCount) Reset() {
	*x = ScanItem_ScanTypeCount{}
	mi := &file_scan_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanItem_ScanTypeCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanItem_ScanTypeCount) ProtoMessage() {}

func (x *ScanItem_ScanTypeCount) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanItem_ScanTypeCount.ProtoReflect.Descriptor instead.
func (*ScanItem_ScanTypeCount) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ScanItem_ScanTypeCount) GetDataType() ScanDataType {
	if x != nil {
		return x.DataType
	}
	return ScanDataType_SD_UNKNOWN
}

func (x *ScanItem_ScanTypeCount) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_scan_proto protoreflect.FileDescriptor

const file_scan_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"scan.proto\x1a\x16ownership-access.proto\"\xab\x06\n" +
	"\bScanItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x125\n" +
	"\tdataTypes\x18\x04 \x03(\v2\x17.ScanItem.ScanTypeCountR\tdataTypes\x12/\n" +
	"\n" +
	"instrument\x18\x05 \x01(\x0e2\x0f.ScanInstrumentR\n" +
	"instrument\x12*\n" +
	"\x10instrumentConfig\x18\x06 \x01(\tR\x10instrumentConfig\x12*\n" +
	"\x10timestampUnixSec\x18\a \x01(\rR\x10timestampUnixSec\x12'\n" +
	"\x04meta\x18\b \x03(\v2\x13.ScanItem.MetaEntryR\x04meta\x12B\n" +
	"\rcontentCounts\x18\t \x03(\v2\x1c.ScanItem.ContentCountsEntryR\rcontentCounts\x12$\n" +
	"\rcreatorUserId\x18\n" +
	" \x01(\tR\rcreatorUserId\x12'\n" +
	"\x05owner\x18\v \x01(\v2\x11.OwnershipSummaryR\x05owner\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\x12>\n" +
	"\x1apreviousImportTimesUnixSec\x18\r \x03(\rR\x1apreviousImportTimesUnixSec\x12:\n" +
	"\x18completeTimeStampUnixSec\x18\x0e \x01(\rR\x18completeTimeStampUnixSec\x1aP\n" +
	"\rScanTypeCount\x12)\n" +
	"\bdataType\x18\x01 \x01(\x0e2\r.ScanDataTypeR\bdataType\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12ContentCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"i\n" +
	"\x10ScanMetaDataItem\x12\x18\n" +
	"\x06fvalue\x18\x01 \x01(\x02H\x00R\x06fvalue\x12\x18\n" +
	"\x06ivalue\x18\x02 \x01(\x05H\x00R\x06ivalue\x12\x18\n" +
	"\x06svalue\x18\x03 \x01(\tH\x00R\x06svalueB\a\n" +
	"\x05Value\"*\n" +
	"\x0eScanEntryRange\x12\x18\n" +
	"\aindexes\x18\x01 \x03(\x05R\aindexes\"x\n" +
	"\x12ScanAutoShareEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\aviewers\x18\x02 \x01(\v2\x0e.UserGroupListR\aviewers\x12(\n" +
	"\aeditors\x18\x03 \x01(\v2\x0e.UserGroupListR\aeditors\"\xba\x01\n" +
	"\x0eJobGroupConfig\x12\x1e\n" +
	"\n" +
	"jobGroupId\x18\x01 \x01(\tR\n" +
	"jobGroupId\x12 \n" +
	"\vdockerImage\x18\x02 \x01(\tR\vdockerImage\x12\x1c\n" +
	"\tfastStart\x18\x03 \x01(\bR\tfastStart\x12\x1c\n" +
	"\tnodeCount\x18\x04 \x01(\x05R\tnodeCount\x12*\n" +
	"\n" +
	"nodeConfig\x18\x05 \x01(\v2\n" +
	".JobConfigR\n" +
	"nodeConfig\"o\n" +
	"\vJobFilePath\x12\"\n" +
	"\fremoteBucket\x18\x01 \x01(\tR\fremoteBucket\x12\x1e\n" +
	"\n" +
	"remotePath\x18\x02 \x01(\tR\n" +
	"remotePath\x12\x1c\n" +
	"\tlocalPath\x18\x03 \x01(\tR\tlocalPath\"\xb3\x01\n" +
	"\tJobConfig\x12\x14\n" +
	"\x05jobId\x18\x01 \x01(\tR\x05jobId\x122\n" +
	"\rrequiredFiles\x18\x02 \x03(\v2\f.JobFilePathR\rrequiredFiles\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x12.\n" +
	"\voutputFiles\x18\x05 \x03(\v2\f.JobFilePathR\voutputFiles\"\x8d\x01\n" +
	"\tClientMap\x12\x1c\n" +
	"\tEntryPMCs\x18\x01 \x03(\x05R\tEntryPMCs\x12 \n" +
	"\vFloatValues\x18\x02 \x03(\x01R\vFloatValues\x12\x1c\n" +
	"\tIntValues\x18\x03 \x03(\x03R\tIntValues\x12\"\n" +
	"\fStringValues\x18\x04 \x03(\tR\fStringValues\",\n" +
	"\x10ClientStringList\x12\x18\n" +
	"\aStrings\x18\x01 \x03(\tR\aStrings*V\n" +
	"\fScanDataType\x12\x0e\n" +
	"\n" +
	"SD_UNKNOWN\x10\x00\x12\f\n" +
	"\bSD_IMAGE\x10\x01\x12\n" +
	"\n" +
	"\x06SD_XRF\x10\x02\x12\v\n" +
	"\aSD_RGBU\x10\x03\x12\x0f\n" +
	"\vSD_BIGIMAGE\x10\x04*\xa9\x01\n" +
	"\x0eScanInstrument\x12\x16\n" +
	"\x12UNKNOWN_INSTRUMENT\x10\x00\x12\v\n" +
	"\aPIXL_FM\x10\x01\x12\v\n" +
	"\aPIXL_EM\x10\x02\x12\x12\n" +
	"\x0eJPL_BREADBOARD\x10\x03\x12\x12\n" +
	"\x0eSBU_BREADBOARD\x10\x04\x12\n" +
	"\n" +
	"\x06BRUKER\x10\x05\x12\x0f\n" +
	"\vGENERIC_XRF\x10\x06\x12\x0f\n" +
	"\vGENERIC_WDS\x10\a\x12\x0f\n" +
	"\vGENERIC_SEM\x10\b*;\n" +
	"\x10ScanMetaDataType\x12\f\n" +
	"\bMT_FLOAT\x10\x00\x12\n" +
	"\n" +
	"\x06MT_INT\x10\x01\x12\r\n" +
	"\tMT_STRING\x10\x02B\n" +
	"Z\b.;protosb\x06proto3"

var (
	file_scan_proto_rawDescOnce sync.Once
	file_scan_proto_rawDescData []byte
)

func file_scan_proto_rawDescGZIP() []byte {
	file_scan_proto_rawDescOnce.Do(func() {
		file_scan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scan_proto_rawDesc), len(file_scan_proto_rawDesc)))
	})
	return file_scan_proto_rawDescData
}

var file_scan_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_scan_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_scan_proto_goTypes = []any{
	(ScanDataType)(0),              // 0: ScanDataType
	(ScanInstrument)(0),            // 1: ScanInstrument
	(ScanMetaDataType)(0),          // 2: ScanMetaDataType
	(*ScanItem)(nil),               // 3: ScanItem
	(*ScanMetaDataItem)(nil),       // 4: ScanMetaDataItem
	(*ScanEntryRange)(nil),         // 5: ScanEntryRange
	(*ScanAutoShareEntry)(nil),     // 6: ScanAutoShareEntry
	(*JobGroupConfig)(nil),         // 7: JobGroupConfig
	(*JobFilePath)(nil),            // 8: JobFilePath
	(*JobConfig)(nil),              // 9: JobConfig
	(*ClientMap)(nil),              // 10: ClientMap
	(*ClientStringList)(nil),       // 11: ClientStringList
	(*ScanItem_ScanTypeCount)(nil), // 12: ScanItem.ScanTypeCount
	nil,                            // 13: ScanItem.MetaEntry
	nil,                            // 14: ScanItem.ContentCountsEntry
	(*OwnershipSummary)(nil),       // 15: OwnershipSummary
	(*UserGroupList)(nil),          // 16: UserGroupList
}
var file_scan_proto_depIdxs = []int32{
	12, // 0: ScanItem.dataTypes:type_name -> ScanItem.ScanTypeCount
	1,  // 1: ScanItem.instrument:type_name -> ScanInstrument
	13, // 2: ScanItem.meta:type_name -> ScanItem.MetaEntry
	14, // 3: ScanItem.contentCounts:type_name -> ScanItem.ContentCountsEntry
	15, // 4: ScanItem.owner:type_name -> OwnershipSummary
	16, // 5: ScanAutoShareEntry.viewers:type_name -> UserGroupList
	16, // 6: ScanAutoShareEntry.editors:type_name -> UserGroupList
	9,  // 7: JobGroupConfig.nodeConfig:type_name -> JobConfig
	8,  // 8: JobConfig.requiredFiles:type_name -> JobFilePath
	8,  // 9: JobConfig.outputFiles:type_name -> JobFilePath
	0,  // 10: ScanItem.ScanTypeCount.dataType:type_name -> ScanDataType
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_scan_proto_init() }
func file_scan_proto_init() {
	if File_scan_proto != nil {
		return
	}
	file_ownership_access_proto_init()
	file_scan_proto_msgTypes[1].OneofWrappers = []any{
		(*ScanMetaDataItem_Fvalue)(nil),
		(*ScanMetaDataItem_Ivalue)(nil),
		(*ScanMetaDataItem_Svalue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scan_proto_rawDesc), len(file_scan_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scan_proto_goTypes,
		DependencyIndexes: file_scan_proto_depIdxs,
		EnumInfos:         file_scan_proto_enumTypes,
		MessageInfos:      file_scan_proto_msgTypes,
	}.Build()
	File_scan_proto = out.File
	file_scan_proto_goTypes = nil
	file_scan_proto_depIdxs = nil
}
