// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: scan-msgs.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Allows listing scans. Contains search fields. If these are all blank
// all scans are returned
// requires(NONE)
type ScanListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Allows flexible fields, because scans have flexible metadata
	// but for PIXL suggestions are:
	//
	// The scans ID:
	// - scanId
	//
	// Meta fields (member of db meta struct):
	// - Target, SiteId, Site, RTT, SCLK, Sol, DriveId, TargetId
	//
	// DB struct fields directly accessed:
	// - title
	// - description
	// - instrument
	// - instrumentConfig
	// - timeStampUnixSec
	//
	// Fields that look at counts:
	// (NOT IMPLEMENTED YET) - hasDwell
	// (NOT IMPLEMENTED YET) - hasNormal
	SearchFilters map[string]string `protobuf:"bytes,1,rep,name=searchFilters,proto3" json:"searchFilters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ScanListReq) Reset() {
	*x = ScanListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanListReq) ProtoMessage() {}

func (x *ScanListReq) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanListReq.ProtoReflect.Descriptor instead.
func (*ScanListReq) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{0}
}

func (x *ScanListReq) GetSearchFilters() map[string]string {
	if x != nil {
		return x.SearchFilters
	}
	return nil
}

type ScanListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scans []*ScanItem `protobuf:"bytes,1,rep,name=scans,proto3" json:"scans,omitempty"`
}

func (x *ScanListResp) Reset() {
	*x = ScanListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanListResp) ProtoMessage() {}

func (x *ScanListResp) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanListResp.ProtoReflect.Descriptor instead.
func (*ScanListResp) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{1}
}

func (x *ScanListResp) GetScans() []*ScanItem {
	if x != nil {
		return x.Scans
	}
	return nil
}

type ScanListUpd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScanListUpd) Reset() {
	*x = ScanListUpd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanListUpd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanListUpd) ProtoMessage() {}

func (x *ScanListUpd) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanListUpd.ProtoReflect.Descriptor instead.
func (*ScanListUpd) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{2}
}

// requires(NONE)
type ScanGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ScanGetReq) Reset() {
	*x = ScanGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanGetReq) ProtoMessage() {}

func (x *ScanGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanGetReq.ProtoReflect.Descriptor instead.
func (*ScanGetReq) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{3}
}

func (x *ScanGetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ScanGetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scan *ScanItem `protobuf:"bytes,1,opt,name=scan,proto3" json:"scan,omitempty"`
}

func (x *ScanGetResp) Reset() {
	*x = ScanGetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanGetResp) ProtoMessage() {}

func (x *ScanGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanGetResp.ProtoReflect.Descriptor instead.
func (*ScanGetResp) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{4}
}

func (x *ScanGetResp) GetScan() *ScanItem {
	if x != nil {
		return x.Scan
	}
	return nil
}

// This should trigger a ScanListUpd to go out
// requires(EDIT_SCAN)
type ScanUploadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Format string `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"` // currently only allows jpl-breadboard
	// NOTE: We used to send the zip data up here, but message size was never big enough
	//
	//	so instead of increasing that, we now have a PUT /scan endpoint to pass up
	//	the zip first, then this can be called, passing the same scan id & file name
	//
	// bytes zippedData = 3; // jpl-breadboard implies this is a zip file of MSA files
	ZipFileName string `protobuf:"bytes,4,opt,name=zipFileName,proto3" json:"zipFileName,omitempty"`
}

func (x *ScanUploadReq) Reset() {
	*x = ScanUploadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanUploadReq) ProtoMessage() {}

func (x *ScanUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanUploadReq.ProtoReflect.Descriptor instead.
func (*ScanUploadReq) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{5}
}

func (x *ScanUploadReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScanUploadReq) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ScanUploadReq) GetZipFileName() string {
	if x != nil {
		return x.ZipFileName
	}
	return ""
}

type ScanUploadResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
}

func (x *ScanUploadResp) Reset() {
	*x = ScanUploadResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanUploadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanUploadResp) ProtoMessage() {}

func (x *ScanUploadResp) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanUploadResp.ProtoReflect.Descriptor instead.
func (*ScanUploadResp) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{6}
}

func (x *ScanUploadResp) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type ScanUploadUpd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *JobStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ScanUploadUpd) Reset() {
	*x = ScanUploadUpd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanUploadUpd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanUploadUpd) ProtoMessage() {}

func (x *ScanUploadUpd) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanUploadUpd.ProtoReflect.Descriptor instead.
func (*ScanUploadUpd) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{7}
}

func (x *ScanUploadUpd) GetStatus() *JobStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// Editing who to auto-share a scan with
// requires(EDIT_SCAN)
type ScanAutoShareReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ScanAutoShareReq) Reset() {
	*x = ScanAutoShareReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanAutoShareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanAutoShareReq) ProtoMessage() {}

func (x *ScanAutoShareReq) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanAutoShareReq.ProtoReflect.Descriptor instead.
func (*ScanAutoShareReq) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{8}
}

func (x *ScanAutoShareReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ScanAutoShareResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry *ScanAutoShareEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
}

func (x *ScanAutoShareResp) Reset() {
	*x = ScanAutoShareResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanAutoShareResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanAutoShareResp) ProtoMessage() {}

func (x *ScanAutoShareResp) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanAutoShareResp.ProtoReflect.Descriptor instead.
func (*ScanAutoShareResp) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{9}
}

func (x *ScanAutoShareResp) GetEntry() *ScanAutoShareEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// requires(EDIT_SCAN)
type ScanAutoShareWriteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry *ScanAutoShareEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
}

func (x *ScanAutoShareWriteReq) Reset() {
	*x = ScanAutoShareWriteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanAutoShareWriteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanAutoShareWriteReq) ProtoMessage() {}

func (x *ScanAutoShareWriteReq) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanAutoShareWriteReq.ProtoReflect.Descriptor instead.
func (*ScanAutoShareWriteReq) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{10}
}

func (x *ScanAutoShareWriteReq) GetEntry() *ScanAutoShareEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type ScanAutoShareWriteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScanAutoShareWriteResp) Reset() {
	*x = ScanAutoShareWriteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanAutoShareWriteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanAutoShareWriteResp) ProtoMessage() {}

func (x *ScanAutoShareWriteResp) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanAutoShareWriteResp.ProtoReflect.Descriptor instead.
func (*ScanAutoShareWriteResp) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{11}
}

// This should trigger a ScanListUpd to go out
// requires(EDIT_SCAN)
type ScanMetaWriteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScanId      string `protobuf:"bytes,1,opt,name=scanId,proto3" json:"scanId,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// map<string, string> metaFields = 4;
	Tags []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *ScanMetaWriteReq) Reset() {
	*x = ScanMetaWriteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanMetaWriteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanMetaWriteReq) ProtoMessage() {}

func (x *ScanMetaWriteReq) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanMetaWriteReq.ProtoReflect.Descriptor instead.
func (*ScanMetaWriteReq) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{12}
}

func (x *ScanMetaWriteReq) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *ScanMetaWriteReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ScanMetaWriteReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScanMetaWriteReq) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ScanMetaWriteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScanMetaWriteResp) Reset() {
	*x = ScanMetaWriteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanMetaWriteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanMetaWriteResp) ProtoMessage() {}

func (x *ScanMetaWriteResp) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanMetaWriteResp.ProtoReflect.Descriptor instead.
func (*ScanMetaWriteResp) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{13}
}

// Triggering a re-import, should publish a ScanListUpd to go out
// Useful really only if there is a pipeline hooked up for this kind of data that we
// can re-trigger for. If it's a user-uploaded scan, we can't do anything really...
// requires(EDIT_SCAN)
type ScanTriggerReImportReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScanId string `protobuf:"bytes,1,opt,name=scanId,proto3" json:"scanId,omitempty"`
}

func (x *ScanTriggerReImportReq) Reset() {
	*x = ScanTriggerReImportReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanTriggerReImportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanTriggerReImportReq) ProtoMessage() {}

func (x *ScanTriggerReImportReq) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanTriggerReImportReq.ProtoReflect.Descriptor instead.
func (*ScanTriggerReImportReq) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{14}
}

func (x *ScanTriggerReImportReq) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

type ScanTriggerReImportResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
}

func (x *ScanTriggerReImportResp) Reset() {
	*x = ScanTriggerReImportResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanTriggerReImportResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanTriggerReImportResp) ProtoMessage() {}

func (x *ScanTriggerReImportResp) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanTriggerReImportResp.ProtoReflect.Descriptor instead.
func (*ScanTriggerReImportResp) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{15}
}

func (x *ScanTriggerReImportResp) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type ScanTriggerReImportUpd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *JobStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ScanTriggerReImportUpd) Reset() {
	*x = ScanTriggerReImportUpd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanTriggerReImportUpd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanTriggerReImportUpd) ProtoMessage() {}

func (x *ScanTriggerReImportUpd) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanTriggerReImportUpd.ProtoReflect.Descriptor instead.
func (*ScanTriggerReImportUpd) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{16}
}

func (x *ScanTriggerReImportUpd) GetStatus() *JobStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// requires(NONE)
type ScanMetaLabelsAndTypesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScanId string `protobuf:"bytes,1,opt,name=scanId,proto3" json:"scanId,omitempty"`
}

func (x *ScanMetaLabelsAndTypesReq) Reset() {
	*x = ScanMetaLabelsAndTypesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanMetaLabelsAndTypesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanMetaLabelsAndTypesReq) ProtoMessage() {}

func (x *ScanMetaLabelsAndTypesReq) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanMetaLabelsAndTypesReq.ProtoReflect.Descriptor instead.
func (*ScanMetaLabelsAndTypesReq) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{17}
}

func (x *ScanMetaLabelsAndTypesReq) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

type ScanMetaLabelsAndTypesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MetaLabels []string           `protobuf:"bytes,1,rep,name=metaLabels,proto3" json:"metaLabels,omitempty"`
	MetaTypes  []ScanMetaDataType `protobuf:"varint,2,rep,packed,name=metaTypes,proto3,enum=ScanMetaDataType" json:"metaTypes,omitempty"`
}

func (x *ScanMetaLabelsAndTypesResp) Reset() {
	*x = ScanMetaLabelsAndTypesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanMetaLabelsAndTypesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanMetaLabelsAndTypesResp) ProtoMessage() {}

func (x *ScanMetaLabelsAndTypesResp) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanMetaLabelsAndTypesResp.ProtoReflect.Descriptor instead.
func (*ScanMetaLabelsAndTypesResp) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{18}
}

func (x *ScanMetaLabelsAndTypesResp) GetMetaLabels() []string {
	if x != nil {
		return x.MetaLabels
	}
	return nil
}

func (x *ScanMetaLabelsAndTypesResp) GetMetaTypes() []ScanMetaDataType {
	if x != nil {
		return x.MetaTypes
	}
	return nil
}

// requires(EDIT_SCAN)
type ScanDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScanId                  string `protobuf:"bytes,1,opt,name=scanId,proto3" json:"scanId,omitempty"`
	ScanNameForVerification string `protobuf:"bytes,2,opt,name=scanNameForVerification,proto3" json:"scanNameForVerification,omitempty"`
}

func (x *ScanDeleteReq) Reset() {
	*x = ScanDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanDeleteReq) ProtoMessage() {}

func (x *ScanDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanDeleteReq.ProtoReflect.Descriptor instead.
func (*ScanDeleteReq) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{19}
}

func (x *ScanDeleteReq) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *ScanDeleteReq) GetScanNameForVerification() string {
	if x != nil {
		return x.ScanNameForVerification
	}
	return ""
}

type ScanDeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScanDeleteResp) Reset() {
	*x = ScanDeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanDeleteResp) ProtoMessage() {}

func (x *ScanDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanDeleteResp.ProtoReflect.Descriptor instead.
func (*ScanDeleteResp) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{20}
}

// requires(QUANTIFY)
type ScanTriggerAutoQuantReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScanId string `protobuf:"bytes,1,opt,name=scanId,proto3" json:"scanId,omitempty"`
}

func (x *ScanTriggerAutoQuantReq) Reset() {
	*x = ScanTriggerAutoQuantReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanTriggerAutoQuantReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanTriggerAutoQuantReq) ProtoMessage() {}

func (x *ScanTriggerAutoQuantReq) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanTriggerAutoQuantReq.ProtoReflect.Descriptor instead.
func (*ScanTriggerAutoQuantReq) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{21}
}

func (x *ScanTriggerAutoQuantReq) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

type ScanTriggerAutoQuantResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScanTriggerAutoQuantResp) Reset() {
	*x = ScanTriggerAutoQuantResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanTriggerAutoQuantResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanTriggerAutoQuantResp) ProtoMessage() {}

func (x *ScanTriggerAutoQuantResp) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanTriggerAutoQuantResp.ProtoReflect.Descriptor instead.
func (*ScanTriggerAutoQuantResp) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{22}
}

type ScanListReq_MinMaxInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min int64 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max int64 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *ScanListReq_MinMaxInt) Reset() {
	*x = ScanListReq_MinMaxInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_msgs_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanListReq_MinMaxInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanListReq_MinMaxInt) ProtoMessage() {}

func (x *ScanListReq_MinMaxInt) ProtoReflect() protoreflect.Message {
	mi := &file_scan_msgs_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanListReq_MinMaxInt.ProtoReflect.Descriptor instead.
func (*ScanListReq_MinMaxInt) Descriptor() ([]byte, []int) {
	return file_scan_msgs_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ScanListReq_MinMaxInt) GetMin() int64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *ScanListReq_MinMaxInt) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

var File_scan_msgs_proto protoreflect.FileDescriptor

var file_scan_msgs_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x63, 0x61, 0x6e, 0x2d, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0a, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x09, 0x6a,
	0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc7, 0x01, 0x0a, 0x0b, 0x53, 0x63, 0x61,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x45, 0x0a, 0x0d, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x2e, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x0d, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x1a,
	0x40, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x1a, 0x2f, 0x0a, 0x09, 0x4d, 0x69, 0x6e, 0x4d, 0x61, 0x78, 0x49, 0x6e, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x69, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6d,
	0x61, 0x78, 0x22, 0x2f, 0x0a, 0x0c, 0x53, 0x63, 0x61, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x1f, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x73, 0x63,
	0x61, 0x6e, 0x73, 0x22, 0x0d, 0x0a, 0x0b, 0x53, 0x63, 0x61, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x55,
	0x70, 0x64, 0x22, 0x1c, 0x0a, 0x0a, 0x53, 0x63, 0x61, 0x6e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x2c, 0x0a, 0x0b, 0x53, 0x63, 0x61, 0x6e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x1d, 0x0a, 0x04, 0x73, 0x63, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x53, 0x63, 0x61, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x73, 0x63, 0x61, 0x6e, 0x22, 0x59,
	0x0a, 0x0d, 0x53, 0x63, 0x61, 0x6e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x7a, 0x69, 0x70, 0x46, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x7a, 0x69,
	0x70, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x0e, 0x53, 0x63, 0x61,
	0x6e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6a,
	0x6f, 0x62, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49,
	0x64, 0x22, 0x33, 0x0a, 0x0d, 0x53, 0x63, 0x61, 0x6e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x55,
	0x70, 0x64, 0x12, 0x22, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x22, 0x0a, 0x10, 0x53, 0x63, 0x61, 0x6e, 0x41, 0x75,
	0x74, 0x6f, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3e, 0x0a, 0x11, 0x53, 0x63,
	0x61, 0x6e, 0x41, 0x75, 0x74, 0x6f, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x29, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x53, 0x63, 0x61, 0x6e, 0x41, 0x75, 0x74, 0x6f, 0x53, 0x68, 0x61, 0x72, 0x65, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x42, 0x0a, 0x15, 0x53, 0x63,
	0x61, 0x6e, 0x41, 0x75, 0x74, 0x6f, 0x53, 0x68, 0x61, 0x72, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x29, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x41, 0x75, 0x74, 0x6f, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x18,
	0x0a, 0x16, 0x53, 0x63, 0x61, 0x6e, 0x41, 0x75, 0x74, 0x6f, 0x53, 0x68, 0x61, 0x72, 0x65, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x76, 0x0a, 0x10, 0x53, 0x63, 0x61, 0x6e,
	0x4d, 0x65, 0x74, 0x61, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x63, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63,
	0x61, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73,
	0x22, 0x13, 0x0a, 0x11, 0x53, 0x63, 0x61, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x30, 0x0a, 0x16, 0x53, 0x63, 0x61, 0x6e, 0x54, 0x72, 0x69,
	0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x63, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x63, 0x61, 0x6e, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x17, 0x53, 0x63, 0x61, 0x6e, 0x54,
	0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x16, 0x53, 0x63, 0x61, 0x6e,
	0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x55,
	0x70, 0x64, 0x12, 0x22, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x33, 0x0a, 0x19, 0x53, 0x63, 0x61, 0x6e, 0x4d, 0x65,
	0x74, 0x61, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x41, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x61, 0x6e, 0x49, 0x64, 0x22, 0x6d, 0x0a, 0x1a, 0x53,
	0x63, 0x61, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x41, 0x6e, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x65, 0x74,
	0x61, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6d,
	0x65, 0x74, 0x61, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x2f, 0x0a, 0x09, 0x6d, 0x65, 0x74,
	0x61, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x53,
	0x63, 0x61, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x09, 0x6d, 0x65, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x73, 0x22, 0x61, 0x0a, 0x0d, 0x53, 0x63,
	0x61, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x63, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x61,
	0x6e, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x17, 0x73, 0x63, 0x61, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x46,
	0x6f, 0x72, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x17, 0x73, 0x63, 0x61, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x46, 0x6f,
	0x72, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x10, 0x0a,
	0x0e, 0x53, 0x63, 0x61, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x31, 0x0a, 0x17, 0x53, 0x63, 0x61, 0x6e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x41, 0x75,
	0x74, 0x6f, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63,
	0x61, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x61, 0x6e,
	0x49, 0x64, 0x22, 0x1a, 0x0a, 0x18, 0x53, 0x63, 0x61, 0x6e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65,
	0x72, 0x41, 0x75, 0x74, 0x6f, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0a,
	0x5a, 0x08, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_scan_msgs_proto_rawDescOnce sync.Once
	file_scan_msgs_proto_rawDescData = file_scan_msgs_proto_rawDesc
)

func file_scan_msgs_proto_rawDescGZIP() []byte {
	file_scan_msgs_proto_rawDescOnce.Do(func() {
		file_scan_msgs_proto_rawDescData = protoimpl.X.CompressGZIP(file_scan_msgs_proto_rawDescData)
	})
	return file_scan_msgs_proto_rawDescData
}

var file_scan_msgs_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_scan_msgs_proto_goTypes = []interface{}{
	(*ScanListReq)(nil),                // 0: ScanListReq
	(*ScanListResp)(nil),               // 1: ScanListResp
	(*ScanListUpd)(nil),                // 2: ScanListUpd
	(*ScanGetReq)(nil),                 // 3: ScanGetReq
	(*ScanGetResp)(nil),                // 4: ScanGetResp
	(*ScanUploadReq)(nil),              // 5: ScanUploadReq
	(*ScanUploadResp)(nil),             // 6: ScanUploadResp
	(*ScanUploadUpd)(nil),              // 7: ScanUploadUpd
	(*ScanAutoShareReq)(nil),           // 8: ScanAutoShareReq
	(*ScanAutoShareResp)(nil),          // 9: ScanAutoShareResp
	(*ScanAutoShareWriteReq)(nil),      // 10: ScanAutoShareWriteReq
	(*ScanAutoShareWriteResp)(nil),     // 11: ScanAutoShareWriteResp
	(*ScanMetaWriteReq)(nil),           // 12: ScanMetaWriteReq
	(*ScanMetaWriteResp)(nil),          // 13: ScanMetaWriteResp
	(*ScanTriggerReImportReq)(nil),     // 14: ScanTriggerReImportReq
	(*ScanTriggerReImportResp)(nil),    // 15: ScanTriggerReImportResp
	(*ScanTriggerReImportUpd)(nil),     // 16: ScanTriggerReImportUpd
	(*ScanMetaLabelsAndTypesReq)(nil),  // 17: ScanMetaLabelsAndTypesReq
	(*ScanMetaLabelsAndTypesResp)(nil), // 18: ScanMetaLabelsAndTypesResp
	(*ScanDeleteReq)(nil),              // 19: ScanDeleteReq
	(*ScanDeleteResp)(nil),             // 20: ScanDeleteResp
	(*ScanTriggerAutoQuantReq)(nil),    // 21: ScanTriggerAutoQuantReq
	(*ScanTriggerAutoQuantResp)(nil),   // 22: ScanTriggerAutoQuantResp
	nil,                                // 23: ScanListReq.SearchFiltersEntry
	(*ScanListReq_MinMaxInt)(nil),      // 24: ScanListReq.MinMaxInt
	(*ScanItem)(nil),                   // 25: ScanItem
	(*JobStatus)(nil),                  // 26: JobStatus
	(*ScanAutoShareEntry)(nil),         // 27: ScanAutoShareEntry
	(ScanMetaDataType)(0),              // 28: ScanMetaDataType
}
var file_scan_msgs_proto_depIdxs = []int32{
	23, // 0: ScanListReq.searchFilters:type_name -> ScanListReq.SearchFiltersEntry
	25, // 1: ScanListResp.scans:type_name -> ScanItem
	25, // 2: ScanGetResp.scan:type_name -> ScanItem
	26, // 3: ScanUploadUpd.status:type_name -> JobStatus
	27, // 4: ScanAutoShareResp.entry:type_name -> ScanAutoShareEntry
	27, // 5: ScanAutoShareWriteReq.entry:type_name -> ScanAutoShareEntry
	26, // 6: ScanTriggerReImportUpd.status:type_name -> JobStatus
	28, // 7: ScanMetaLabelsAndTypesResp.metaTypes:type_name -> ScanMetaDataType
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_scan_msgs_proto_init() }
func file_scan_msgs_proto_init() {
	if File_scan_msgs_proto != nil {
		return
	}
	file_scan_proto_init()
	file_job_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_scan_msgs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_msgs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_msgs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanListUpd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_msgs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_msgs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanGetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_msgs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanUploadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_msgs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanUploadResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_msgs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanUploadUpd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_msgs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanAutoShareReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_msgs_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanAutoShareResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_msgs_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanAutoShareWriteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_msgs_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanAutoShareWriteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_msgs_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanMetaWriteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_msgs_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanMetaWriteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_msgs_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanTriggerReImportReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_msgs_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanTriggerReImportResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_msgs_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanTriggerReImportUpd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_msgs_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanMetaLabelsAndTypesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_msgs_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanMetaLabelsAndTypesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_msgs_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_msgs_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanDeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_msgs_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanTriggerAutoQuantReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_msgs_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanTriggerAutoQuantResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_msgs_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanListReq_MinMaxInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scan_msgs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scan_msgs_proto_goTypes,
		DependencyIndexes: file_scan_msgs_proto_depIdxs,
		MessageInfos:      file_scan_msgs_proto_msgTypes,
	}.Build()
	File_scan_msgs_proto = out.File
	file_scan_msgs_proto_rawDesc = nil
	file_scan_msgs_proto_goTypes = nil
	file_scan_msgs_proto_depIdxs = nil
}
