// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: tags.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tag struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`  
	Name   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type   string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	ScanId string                 `protobuf:"bytes,4,opt,name=scanId,proto3" json:"scanId,omitempty"`
	// Only sent out by API, not stored in DB this way
	Owner         *UserInfo `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty" bson:"-"`  
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_tags_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_tags_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_tags_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Tag) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *Tag) GetOwner() *UserInfo {
	if x != nil {
		return x.Owner
	}
	return nil
}

type TagDB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`  
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	ScanId        string                 `protobuf:"bytes,4,opt,name=scanId,proto3" json:"scanId,omitempty"`
	OwnerId       string                 `protobuf:"bytes,5,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagDB) Reset() {
	*x = TagDB{}
	mi := &file_tags_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagDB) ProtoMessage() {}

func (x *TagDB) ProtoReflect() protoreflect.Message {
	mi := &file_tags_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagDB.ProtoReflect.Descriptor instead.
func (*TagDB) Descriptor() ([]byte, []int) {
	return file_tags_proto_rawDescGZIP(), []int{1}
}

func (x *TagDB) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagDB) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagDB) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TagDB) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *TagDB) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type ClientTagList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientTagList) Reset() {
	*x = ClientTagList{}
	mi := &file_tags_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTagList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTagList) ProtoMessage() {}

func (x *ClientTagList) ProtoReflect() protoreflect.Message {
	mi := &file_tags_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTagList.ProtoReflect.Descriptor instead.
func (*ClientTagList) Descriptor() ([]byte, []int) {
	return file_tags_proto_rawDescGZIP(), []int{2}
}

func (x *ClientTagList) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_tags_proto protoreflect.FileDescriptor

const file_tags_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"tags.proto\x1a\n" +
	"user.proto\"v\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06scanId\x18\x04 \x01(\tR\x06scanId\x12\x1f\n" +
	"\x05owner\x18\x05 \x01(\v2\t.UserInfoR\x05owner\"q\n" +
	"\x05TagDB\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06scanId\x18\x04 \x01(\tR\x06scanId\x12\x18\n" +
	"\aownerId\x18\x05 \x01(\tR\aownerId\")\n" +
	"\rClientTagList\x12\x18\n" +
	"\x04tags\x18\x01 \x03(\v2\x04.TagR\x04tagsB\n" +
	"Z\b.;protosb\x06proto3"

var (
	file_tags_proto_rawDescOnce sync.Once
	file_tags_proto_rawDescData []byte
)

func file_tags_proto_rawDescGZIP() []byte {
	file_tags_proto_rawDescOnce.Do(func() {
		file_tags_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tags_proto_rawDesc), len(file_tags_proto_rawDesc)))
	})
	return file_tags_proto_rawDescData
}

var file_tags_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tags_proto_goTypes = []any{
	(*Tag)(nil),           // 0: Tag
	(*TagDB)(nil),         // 1: TagDB
	(*ClientTagList)(nil), // 2: ClientTagList
	(*UserInfo)(nil),      // 3: UserInfo
}
var file_tags_proto_depIdxs = []int32{
	3, // 0: Tag.owner:type_name -> UserInfo
	0, // 1: ClientTagList.tags:type_name -> Tag
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tags_proto_init() }
func file_tags_proto_init() {
	if File_tags_proto != nil {
		return
	}
	file_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tags_proto_rawDesc), len(file_tags_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tags_proto_goTypes,
		DependencyIndexes: file_tags_proto_depIdxs,
		MessageInfos:      file_tags_proto_msgTypes,
	}.Build()
	File_tags_proto = out.File
	file_tags_proto_goTypes = nil
	file_tags_proto_depIdxs = nil
}
