// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: user-notification-setting-msgs.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Retrieving a users notification settings (NOT the notifications themselves)
// requires(NONE)
type UserNotificationSettingsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserNotificationSettingsReq) Reset() {
	*x = UserNotificationSettingsReq{}
	mi := &file_user_notification_setting_msgs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserNotificationSettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserNotificationSettingsReq) ProtoMessage() {}

func (x *UserNotificationSettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_notification_setting_msgs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserNotificationSettingsReq.ProtoReflect.Descriptor instead.
func (*UserNotificationSettingsReq) Descriptor() ([]byte, []int) {
	return file_user_notification_setting_msgs_proto_rawDescGZIP(), []int{0}
}

type UserNotificationSettingsResp struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Notifications *UserNotificationSettings `protobuf:"bytes,1,opt,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserNotificationSettingsResp) Reset() {
	*x = UserNotificationSettingsResp{}
	mi := &file_user_notification_setting_msgs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserNotificationSettingsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserNotificationSettingsResp) ProtoMessage() {}

func (x *UserNotificationSettingsResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_notification_setting_msgs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserNotificationSettingsResp.ProtoReflect.Descriptor instead.
func (*UserNotificationSettingsResp) Descriptor() ([]byte, []int) {
	return file_user_notification_setting_msgs_proto_rawDescGZIP(), []int{1}
}

func (x *UserNotificationSettingsResp) GetNotifications() *UserNotificationSettings {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type UserNotificationSettingsUpd struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Notifications *UserNotificationSettings `protobuf:"bytes,1,opt,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserNotificationSettingsUpd) Reset() {
	*x = UserNotificationSettingsUpd{}
	mi := &file_user_notification_setting_msgs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserNotificationSettingsUpd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserNotificationSettingsUpd) ProtoMessage() {}

func (x *UserNotificationSettingsUpd) ProtoReflect() protoreflect.Message {
	mi := &file_user_notification_setting_msgs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserNotificationSettingsUpd.ProtoReflect.Descriptor instead.
func (*UserNotificationSettingsUpd) Descriptor() ([]byte, []int) {
	return file_user_notification_setting_msgs_proto_rawDescGZIP(), []int{2}
}

func (x *UserNotificationSettingsUpd) GetNotifications() *UserNotificationSettings {
	if x != nil {
		return x.Notifications
	}
	return nil
}

// Modifying notifications should publish a UserNotificationSettingsUpd
// requires(EDIT_OWN_USER)
type UserNotificationSettingsWriteReq struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Notifications *UserNotificationSettings `protobuf:"bytes,1,opt,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserNotificationSettingsWriteReq) Reset() {
	*x = UserNotificationSettingsWriteReq{}
	mi := &file_user_notification_setting_msgs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserNotificationSettingsWriteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserNotificationSettingsWriteReq) ProtoMessage() {}

func (x *UserNotificationSettingsWriteReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_notification_setting_msgs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserNotificationSettingsWriteReq.ProtoReflect.Descriptor instead.
func (*UserNotificationSettingsWriteReq) Descriptor() ([]byte, []int) {
	return file_user_notification_setting_msgs_proto_rawDescGZIP(), []int{3}
}

func (x *UserNotificationSettingsWriteReq) GetNotifications() *UserNotificationSettings {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type UserNotificationSettingsWriteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserNotificationSettingsWriteResp) Reset() {
	*x = UserNotificationSettingsWriteResp{}
	mi := &file_user_notification_setting_msgs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserNotificationSettingsWriteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserNotificationSettingsWriteResp) ProtoMessage() {}

func (x *UserNotificationSettingsWriteResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_notification_setting_msgs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserNotificationSettingsWriteResp.ProtoReflect.Descriptor instead.
func (*UserNotificationSettingsWriteResp) Descriptor() ([]byte, []int) {
	return file_user_notification_setting_msgs_proto_rawDescGZIP(), []int{4}
}

var File_user_notification_setting_msgs_proto protoreflect.FileDescriptor

const file_user_notification_setting_msgs_proto_rawDesc = "" +
	"\n" +
	"$user-notification-setting-msgs.proto\x1a user-notification-settings.proto\"\x1d\n" +
	"\x1bUserNotificationSettingsReq\"_\n" +
	"\x1cUserNotificationSettingsResp\x12?\n" +
	"\rnotifications\x18\x01 \x01(\v2\x19.UserNotificationSettingsR\rnotifications\"^\n" +
	"\x1bUserNotificationSettingsUpd\x12?\n" +
	"\rnotifications\x18\x01 \x01(\v2\x19.UserNotificationSettingsR\rnotifications\"c\n" +
	" UserNotificationSettingsWriteReq\x12?\n" +
	"\rnotifications\x18\x01 \x01(\v2\x19.UserNotificationSettingsR\rnotifications\"#\n" +
	"!UserNotificationSettingsWriteRespB\n" +
	"Z\b.;protosb\x06proto3"

var (
	file_user_notification_setting_msgs_proto_rawDescOnce sync.Once
	file_user_notification_setting_msgs_proto_rawDescData []byte
)

func file_user_notification_setting_msgs_proto_rawDescGZIP() []byte {
	file_user_notification_setting_msgs_proto_rawDescOnce.Do(func() {
		file_user_notification_setting_msgs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_notification_setting_msgs_proto_rawDesc), len(file_user_notification_setting_msgs_proto_rawDesc)))
	})
	return file_user_notification_setting_msgs_proto_rawDescData
}

var file_user_notification_setting_msgs_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_notification_setting_msgs_proto_goTypes = []any{
	(*UserNotificationSettingsReq)(nil),       // 0: UserNotificationSettingsReq
	(*UserNotificationSettingsResp)(nil),      // 1: UserNotificationSettingsResp
	(*UserNotificationSettingsUpd)(nil),       // 2: UserNotificationSettingsUpd
	(*UserNotificationSettingsWriteReq)(nil),  // 3: UserNotificationSettingsWriteReq
	(*UserNotificationSettingsWriteResp)(nil), // 4: UserNotificationSettingsWriteResp
	(*UserNotificationSettings)(nil),          // 5: UserNotificationSettings
}
var file_user_notification_setting_msgs_proto_depIdxs = []int32{
	5, // 0: UserNotificationSettingsResp.notifications:type_name -> UserNotificationSettings
	5, // 1: UserNotificationSettingsUpd.notifications:type_name -> UserNotificationSettings
	5, // 2: UserNotificationSettingsWriteReq.notifications:type_name -> UserNotificationSettings
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_user_notification_setting_msgs_proto_init() }
func file_user_notification_setting_msgs_proto_init() {
	if File_user_notification_setting_msgs_proto != nil {
		return
	}
	file_user_notification_settings_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_notification_setting_msgs_proto_rawDesc), len(file_user_notification_setting_msgs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_notification_setting_msgs_proto_goTypes,
		DependencyIndexes: file_user_notification_setting_msgs_proto_depIdxs,
		MessageInfos:      file_user_notification_setting_msgs_proto_msgTypes,
	}.Build()
	File_user_notification_setting_msgs_proto = out.File
	file_user_notification_setting_msgs_proto_goTypes = nil
	file_user_notification_setting_msgs_proto_depIdxs = nil
}
