// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: user-group-joining-msgs.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// requires(NONE)
type UserGroupJoinReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId  string `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	AsMember bool   `protobuf:"varint,2,opt,name=asMember,proto3" json:"asMember,omitempty"`
}

func (x *UserGroupJoinReq) Reset() {
	*x = UserGroupJoinReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_group_joining_msgs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGroupJoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroupJoinReq) ProtoMessage() {}

func (x *UserGroupJoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_group_joining_msgs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroupJoinReq.ProtoReflect.Descriptor instead.
func (*UserGroupJoinReq) Descriptor() ([]byte, []int) {
	return file_user_group_joining_msgs_proto_rawDescGZIP(), []int{0}
}

func (x *UserGroupJoinReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UserGroupJoinReq) GetAsMember() bool {
	if x != nil {
		return x.AsMember
	}
	return false
}

type UserGroupJoinResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserGroupJoinResp) Reset() {
	*x = UserGroupJoinResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_group_joining_msgs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGroupJoinResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroupJoinResp) ProtoMessage() {}

func (x *UserGroupJoinResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_group_joining_msgs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroupJoinResp.ProtoReflect.Descriptor instead.
func (*UserGroupJoinResp) Descriptor() ([]byte, []int) {
	return file_user_group_joining_msgs_proto_rawDescGZIP(), []int{1}
}

// requires(NONE)
type UserGroupIgnoreJoinReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId   string `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	RequestId string `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
}

func (x *UserGroupIgnoreJoinReq) Reset() {
	*x = UserGroupIgnoreJoinReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_group_joining_msgs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGroupIgnoreJoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroupIgnoreJoinReq) ProtoMessage() {}

func (x *UserGroupIgnoreJoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_group_joining_msgs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroupIgnoreJoinReq.ProtoReflect.Descriptor instead.
func (*UserGroupIgnoreJoinReq) Descriptor() ([]byte, []int) {
	return file_user_group_joining_msgs_proto_rawDescGZIP(), []int{2}
}

func (x *UserGroupIgnoreJoinReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UserGroupIgnoreJoinReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type UserGroupIgnoreJoinResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserGroupIgnoreJoinResp) Reset() {
	*x = UserGroupIgnoreJoinResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_group_joining_msgs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGroupIgnoreJoinResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroupIgnoreJoinResp) ProtoMessage() {}

func (x *UserGroupIgnoreJoinResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_group_joining_msgs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroupIgnoreJoinResp.ProtoReflect.Descriptor instead.
func (*UserGroupIgnoreJoinResp) Descriptor() ([]byte, []int) {
	return file_user_group_joining_msgs_proto_rawDescGZIP(), []int{3}
}

// requires(NONE)
type UserGroupJoinListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId string `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
}

func (x *UserGroupJoinListReq) Reset() {
	*x = UserGroupJoinListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_group_joining_msgs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGroupJoinListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroupJoinListReq) ProtoMessage() {}

func (x *UserGroupJoinListReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_group_joining_msgs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroupJoinListReq.ProtoReflect.Descriptor instead.
func (*UserGroupJoinListReq) Descriptor() ([]byte, []int) {
	return file_user_group_joining_msgs_proto_rawDescGZIP(), []int{4}
}

func (x *UserGroupJoinListReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type UserGroupJoinListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requests []*UserGroupJoinRequestDB `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *UserGroupJoinListResp) Reset() {
	*x = UserGroupJoinListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_group_joining_msgs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGroupJoinListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroupJoinListResp) ProtoMessage() {}

func (x *UserGroupJoinListResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_group_joining_msgs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroupJoinListResp.ProtoReflect.Descriptor instead.
func (*UserGroupJoinListResp) Descriptor() ([]byte, []int) {
	return file_user_group_joining_msgs_proto_rawDescGZIP(), []int{5}
}

func (x *UserGroupJoinListResp) GetRequests() []*UserGroupJoinRequestDB {
	if x != nil {
		return x.Requests
	}
	return nil
}

var File_user_group_joining_msgs_proto protoreflect.FileDescriptor

var file_user_group_joining_msgs_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x75, 0x73, 0x65, 0x72, 0x2d, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2d, 0x6a, 0x6f, 0x69,
	0x6e, 0x69, 0x6e, 0x67, 0x2d, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x10, 0x75, 0x73, 0x65, 0x72, 0x2d, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x48, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4a, 0x6f,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x61, 0x73, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x61, 0x73, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x13, 0x0a, 0x11, 0x55,
	0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x50, 0x0a, 0x16, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x67, 0x6e,
	0x6f, 0x72, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x67, 0x6e, 0x6f, 0x72, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x30, 0x0a,
	0x14, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22,
	0x4c, 0x0a, 0x15, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4a, 0x6f, 0x69, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x44, 0x42, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_user_group_joining_msgs_proto_rawDescOnce sync.Once
	file_user_group_joining_msgs_proto_rawDescData = file_user_group_joining_msgs_proto_rawDesc
)

func file_user_group_joining_msgs_proto_rawDescGZIP() []byte {
	file_user_group_joining_msgs_proto_rawDescOnce.Do(func() {
		file_user_group_joining_msgs_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_group_joining_msgs_proto_rawDescData)
	})
	return file_user_group_joining_msgs_proto_rawDescData
}

var file_user_group_joining_msgs_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_user_group_joining_msgs_proto_goTypes = []interface{}{
	(*UserGroupJoinReq)(nil),        // 0: UserGroupJoinReq
	(*UserGroupJoinResp)(nil),       // 1: UserGroupJoinResp
	(*UserGroupIgnoreJoinReq)(nil),  // 2: UserGroupIgnoreJoinReq
	(*UserGroupIgnoreJoinResp)(nil), // 3: UserGroupIgnoreJoinResp
	(*UserGroupJoinListReq)(nil),    // 4: UserGroupJoinListReq
	(*UserGroupJoinListResp)(nil),   // 5: UserGroupJoinListResp
	(*UserGroupJoinRequestDB)(nil),  // 6: UserGroupJoinRequestDB
}
var file_user_group_joining_msgs_proto_depIdxs = []int32{
	6, // 0: UserGroupJoinListResp.requests:type_name -> UserGroupJoinRequestDB
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_group_joining_msgs_proto_init() }
func file_user_group_joining_msgs_proto_init() {
	if File_user_group_joining_msgs_proto != nil {
		return
	}
	file_user_group_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_user_group_joining_msgs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGroupJoinReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_group_joining_msgs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGroupJoinResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_group_joining_msgs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGroupIgnoreJoinReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_group_joining_msgs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGroupIgnoreJoinResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_group_joining_msgs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGroupJoinListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_group_joining_msgs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGroupJoinListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_group_joining_msgs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_group_joining_msgs_proto_goTypes,
		DependencyIndexes: file_user_group_joining_msgs_proto_depIdxs,
		MessageInfos:      file_user_group_joining_msgs_proto_msgTypes,
	}.Build()
	File_user_group_joining_msgs_proto = out.File
	file_user_group_joining_msgs_proto_rawDesc = nil
	file_user_group_joining_msgs_proto_goTypes = nil
	file_user_group_joining_msgs_proto_depIdxs = nil
}
