// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: user-group.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserGroupRelationship int32

const (
	UserGroupRelationship_UGR_UNKNOWN UserGroupRelationship = 0 // https://protobuf.dev/programming-guides/dos-donts/ says specify an unknown as 0
	UserGroupRelationship_UGR_VIEWER  UserGroupRelationship = 1
	UserGroupRelationship_UGR_MEMBER  UserGroupRelationship = 2
	UserGroupRelationship_UGR_ADMIN   UserGroupRelationship = 3
)

// Enum value maps for UserGroupRelationship.
var (
	UserGroupRelationship_name = map[int32]string{
		0: "UGR_UNKNOWN",
		1: "UGR_VIEWER",
		2: "UGR_MEMBER",
		3: "UGR_ADMIN",
	}
	UserGroupRelationship_value = map[string]int32{
		"UGR_UNKNOWN": 0,
		"UGR_VIEWER":  1,
		"UGR_MEMBER":  2,
		"UGR_ADMIN":   3,
	}
)

func (x UserGroupRelationship) Enum() *UserGroupRelationship {
	p := new(UserGroupRelationship)
	*p = x
	return p
}

func (x UserGroupRelationship) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserGroupRelationship) Descriptor() protoreflect.EnumDescriptor {
	return file_user_group_proto_enumTypes[0].Descriptor()
}

func (UserGroupRelationship) Type() protoreflect.EnumType {
	return &file_user_group_proto_enumTypes[0]
}

func (x UserGroupRelationship) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserGroupRelationship.Descriptor instead.
func (UserGroupRelationship) EnumDescriptor() ([]byte, []int) {
	return file_user_group_proto_rawDescGZIP(), []int{0}
}

// The UserGroup we store in DB
type UserGroupDB struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`  
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description           string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	CreatedUnixSec        uint32                 `protobuf:"varint,7,opt,name=createdUnixSec,proto3" json:"createdUnixSec,omitempty"`
	LastUserJoinedUnixSec uint32                 `protobuf:"varint,9,opt,name=lastUserJoinedUnixSec,proto3" json:"lastUserJoinedUnixSec,omitempty"`
	Joinable              bool                   `protobuf:"varint,10,opt,name=joinable,proto3" json:"joinable,omitempty"`
	DefaultRoles          []string               `protobuf:"bytes,11,rep,name=defaultRoles,proto3" json:"defaultRoles,omitempty"`
	Viewers               *UserGroupList         `protobuf:"bytes,5,opt,name=viewers,proto3" json:"viewers,omitempty"`
	Members               *UserGroupList         `protobuf:"bytes,3,opt,name=members,proto3" json:"members,omitempty"`
	AdminUserIds          []string               `protobuf:"bytes,4,rep,name=adminUserIds,proto3" json:"adminUserIds,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UserGroupDB) Reset() {
	*x = UserGroupDB{}
	mi := &file_user_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGroupDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroupDB) ProtoMessage() {}

func (x *UserGroupDB) ProtoReflect() protoreflect.Message {
	mi := &file_user_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroupDB.ProtoReflect.Descriptor instead.
func (*UserGroupDB) Descriptor() ([]byte, []int) {
	return file_user_group_proto_rawDescGZIP(), []int{0}
}

func (x *UserGroupDB) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserGroupDB) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserGroupDB) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UserGroupDB) GetCreatedUnixSec() uint32 {
	if x != nil {
		return x.CreatedUnixSec
	}
	return 0
}

func (x *UserGroupDB) GetLastUserJoinedUnixSec() uint32 {
	if x != nil {
		return x.LastUserJoinedUnixSec
	}
	return 0
}

func (x *UserGroupDB) GetJoinable() bool {
	if x != nil {
		return x.Joinable
	}
	return false
}

func (x *UserGroupDB) GetDefaultRoles() []string {
	if x != nil {
		return x.DefaultRoles
	}
	return nil
}

func (x *UserGroupDB) GetViewers() *UserGroupList {
	if x != nil {
		return x.Viewers
	}
	return nil
}

func (x *UserGroupDB) GetMembers() *UserGroupList {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *UserGroupDB) GetAdminUserIds() []string {
	if x != nil {
		return x.AdminUserIds
	}
	return nil
}

// User Group Info, just the basics...
type UserGroupInfo struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`  
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description           string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedUnixSec        uint32                 `protobuf:"varint,3,opt,name=createdUnixSec,proto3" json:"createdUnixSec,omitempty"`
	LastUserJoinedUnixSec uint32                 `protobuf:"varint,6,opt,name=lastUserJoinedUnixSec,proto3" json:"lastUserJoinedUnixSec,omitempty"`
	Joinable              bool                   `protobuf:"varint,7,opt,name=joinable,proto3" json:"joinable,omitempty"`
	DefaultRoles          []string               `protobuf:"bytes,8,rep,name=defaultRoles,proto3" json:"defaultRoles,omitempty"`
	// OPTIONAL (only returned in UserGroupListResp)
	RelationshipToUser UserGroupRelationship `protobuf:"varint,4,opt,name=relationshipToUser,proto3,enum=UserGroupRelationship" json:"relationshipToUser,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserGroupInfo) Reset() {
	*x = UserGroupInfo{}
	mi := &file_user_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroupInfo) ProtoMessage() {}

func (x *UserGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroupInfo.ProtoReflect.Descriptor instead.
func (*UserGroupInfo) Descriptor() ([]byte, []int) {
	return file_user_group_proto_rawDescGZIP(), []int{1}
}

func (x *UserGroupInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserGroupInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserGroupInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UserGroupInfo) GetCreatedUnixSec() uint32 {
	if x != nil {
		return x.CreatedUnixSec
	}
	return 0
}

func (x *UserGroupInfo) GetLastUserJoinedUnixSec() uint32 {
	if x != nil {
		return x.LastUserJoinedUnixSec
	}
	return 0
}

func (x *UserGroupInfo) GetJoinable() bool {
	if x != nil {
		return x.Joinable
	}
	return false
}

func (x *UserGroupInfo) GetDefaultRoles() []string {
	if x != nil {
		return x.DefaultRoles
	}
	return nil
}

func (x *UserGroupInfo) GetRelationshipToUser() UserGroupRelationship {
	if x != nil {
		return x.RelationshipToUser
	}
	return UserGroupRelationship_UGR_UNKNOWN
}

type UserGroupInfoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfo            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Groups        []*UserGroupInfo       `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGroupInfoList) Reset() {
	*x = UserGroupInfoList{}
	mi := &file_user_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGroupInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroupInfoList) ProtoMessage() {}

func (x *UserGroupInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_user_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroupInfoList.ProtoReflect.Descriptor instead.
func (*UserGroupInfoList) Descriptor() ([]byte, []int) {
	return file_user_group_proto_rawDescGZIP(), []int{2}
}

func (x *UserGroupInfoList) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *UserGroupInfoList) GetGroups() []*UserGroupInfo {
	if x != nil {
		return x.Groups
	}
	return nil
}

// The user group sent out of API, contains "info" items of each user/user-group
// that's attached to it
type UserGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *UserGroupInfo         `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Viewers       *UserGroupInfoList     `protobuf:"bytes,5,opt,name=viewers,proto3" json:"viewers,omitempty"`
	Members       *UserGroupInfoList     `protobuf:"bytes,3,opt,name=members,proto3" json:"members,omitempty"`
	AdminUsers    []*UserInfo            `protobuf:"bytes,4,rep,name=adminUsers,proto3" json:"adminUsers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGroup) Reset() {
	*x = UserGroup{}
	mi := &file_user_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroup) ProtoMessage() {}

func (x *UserGroup) ProtoReflect() protoreflect.Message {
	mi := &file_user_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroup.ProtoReflect.Descriptor instead.
func (*UserGroup) Descriptor() ([]byte, []int) {
	return file_user_group_proto_rawDescGZIP(), []int{3}
}

func (x *UserGroup) GetInfo() *UserGroupInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *UserGroup) GetViewers() *UserGroupInfoList {
	if x != nil {
		return x.Viewers
	}
	return nil
}

func (x *UserGroup) GetMembers() *UserGroupInfoList {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *UserGroup) GetAdminUsers() []*UserInfo {
	if x != nil {
		return x.AdminUsers
	}
	return nil
}

type UserGroupJoinSummaryInfo struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`  
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description           string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Administrators        []*UserInfo            `protobuf:"bytes,4,rep,name=administrators,proto3" json:"administrators,omitempty"`
	Datasets              uint32                 `protobuf:"varint,5,opt,name=datasets,proto3" json:"datasets,omitempty"`
	LastUserJoinedUnixSec uint32                 `protobuf:"varint,6,opt,name=lastUserJoinedUnixSec,proto3" json:"lastUserJoinedUnixSec,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UserGroupJoinSummaryInfo) Reset() {
	*x = UserGroupJoinSummaryInfo{}
	mi := &file_user_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGroupJoinSummaryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroupJoinSummaryInfo) ProtoMessage() {}

func (x *UserGroupJoinSummaryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroupJoinSummaryInfo.ProtoReflect.Descriptor instead.
func (*UserGroupJoinSummaryInfo) Descriptor() ([]byte, []int) {
	return file_user_group_proto_rawDescGZIP(), []int{4}
}

func (x *UserGroupJoinSummaryInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserGroupJoinSummaryInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserGroupJoinSummaryInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UserGroupJoinSummaryInfo) GetAdministrators() []*UserInfo {
	if x != nil {
		return x.Administrators
	}
	return nil
}

func (x *UserGroupJoinSummaryInfo) GetDatasets() uint32 {
	if x != nil {
		return x.Datasets
	}
	return 0
}

func (x *UserGroupJoinSummaryInfo) GetLastUserJoinedUnixSec() uint32 {
	if x != nil {
		return x.LastUserJoinedUnixSec
	}
	return 0
}

// A request to join a user group - stored in DB
type UserGroupJoinRequestDB struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`                    
	UserId         string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`           // Who sent it
	JoinGroupId    string                 `protobuf:"bytes,3,opt,name=joinGroupId,proto3" json:"joinGroupId,omitempty"` // What they want to join
	AsMember       bool                   `protobuf:"varint,4,opt,name=asMember,proto3" json:"asMember,omitempty"`      // If false, join request is to join as a viewer only
	Details        *UserInfo              `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`         // The joining user's info at the time of the request
	CreatedUnixSec uint32                 `protobuf:"varint,6,opt,name=createdUnixSec,proto3" json:"createdUnixSec,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserGroupJoinRequestDB) Reset() {
	*x = UserGroupJoinRequestDB{}
	mi := &file_user_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGroupJoinRequestDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroupJoinRequestDB) ProtoMessage() {}

func (x *UserGroupJoinRequestDB) ProtoReflect() protoreflect.Message {
	mi := &file_user_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroupJoinRequestDB.ProtoReflect.Descriptor instead.
func (*UserGroupJoinRequestDB) Descriptor() ([]byte, []int) {
	return file_user_group_proto_rawDescGZIP(), []int{5}
}

func (x *UserGroupJoinRequestDB) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserGroupJoinRequestDB) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserGroupJoinRequestDB) GetJoinGroupId() string {
	if x != nil {
		return x.JoinGroupId
	}
	return ""
}

func (x *UserGroupJoinRequestDB) GetAsMember() bool {
	if x != nil {
		return x.AsMember
	}
	return false
}

func (x *UserGroupJoinRequestDB) GetDetails() *UserInfo {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *UserGroupJoinRequestDB) GetCreatedUnixSec() uint32 {
	if x != nil {
		return x.CreatedUnixSec
	}
	return 0
}

var File_user_group_proto protoreflect.FileDescriptor

const file_user_group_proto_rawDesc = "" +
	"\n" +
	"\x10user-group.proto\x1a\x16ownership-access.proto\x1a\n" +
	"user.proto\"\xe9\x02\n" +
	"\vUserGroupDB\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12&\n" +
	"\x0ecreatedUnixSec\x18\a \x01(\rR\x0ecreatedUnixSec\x124\n" +
	"\x15lastUserJoinedUnixSec\x18\t \x01(\rR\x15lastUserJoinedUnixSec\x12\x1a\n" +
	"\bjoinable\x18\n" +
	" \x01(\bR\bjoinable\x12\"\n" +
	"\fdefaultRoles\x18\v \x03(\tR\fdefaultRoles\x12(\n" +
	"\aviewers\x18\x05 \x01(\v2\x0e.UserGroupListR\aviewers\x12(\n" +
	"\amembers\x18\x03 \x01(\v2\x0e.UserGroupListR\amembers\x12\"\n" +
	"\fadminUserIds\x18\x04 \x03(\tR\fadminUserIds\"\xbb\x02\n" +
	"\rUserGroupInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12&\n" +
	"\x0ecreatedUnixSec\x18\x03 \x01(\rR\x0ecreatedUnixSec\x124\n" +
	"\x15lastUserJoinedUnixSec\x18\x06 \x01(\rR\x15lastUserJoinedUnixSec\x12\x1a\n" +
	"\bjoinable\x18\a \x01(\bR\bjoinable\x12\"\n" +
	"\fdefaultRoles\x18\b \x03(\tR\fdefaultRoles\x12F\n" +
	"\x12relationshipToUser\x18\x04 \x01(\x0e2\x16.UserGroupRelationshipR\x12relationshipToUser\"\\\n" +
	"\x11UserGroupInfoList\x12\x1f\n" +
	"\x05users\x18\x01 \x03(\v2\t.UserInfoR\x05users\x12&\n" +
	"\x06groups\x18\x02 \x03(\v2\x0e.UserGroupInfoR\x06groups\"\xb6\x01\n" +
	"\tUserGroup\x12\"\n" +
	"\x04info\x18\x01 \x01(\v2\x0e.UserGroupInfoR\x04info\x12,\n" +
	"\aviewers\x18\x05 \x01(\v2\x12.UserGroupInfoListR\aviewers\x12,\n" +
	"\amembers\x18\x03 \x01(\v2\x12.UserGroupInfoListR\amembers\x12)\n" +
	"\n" +
	"adminUsers\x18\x04 \x03(\v2\t.UserInfoR\n" +
	"adminUsers\"\xe5\x01\n" +
	"\x18UserGroupJoinSummaryInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x121\n" +
	"\x0eadministrators\x18\x04 \x03(\v2\t.UserInfoR\x0eadministrators\x12\x1a\n" +
	"\bdatasets\x18\x05 \x01(\rR\bdatasets\x124\n" +
	"\x15lastUserJoinedUnixSec\x18\x06 \x01(\rR\x15lastUserJoinedUnixSec\"\xcb\x01\n" +
	"\x16UserGroupJoinRequestDB\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12 \n" +
	"\vjoinGroupId\x18\x03 \x01(\tR\vjoinGroupId\x12\x1a\n" +
	"\basMember\x18\x04 \x01(\bR\basMember\x12#\n" +
	"\adetails\x18\x05 \x01(\v2\t.UserInfoR\adetails\x12&\n" +
	"\x0ecreatedUnixSec\x18\x06 \x01(\rR\x0ecreatedUnixSec*W\n" +
	"\x15UserGroupRelationship\x12\x0f\n" +
	"\vUGR_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"UGR_VIEWER\x10\x01\x12\x0e\n" +
	"\n" +
	"UGR_MEMBER\x10\x02\x12\r\n" +
	"\tUGR_ADMIN\x10\x03B\n" +
	"Z\b.;protosb\x06proto3"

var (
	file_user_group_proto_rawDescOnce sync.Once
	file_user_group_proto_rawDescData []byte
)

func file_user_group_proto_rawDescGZIP() []byte {
	file_user_group_proto_rawDescOnce.Do(func() {
		file_user_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_group_proto_rawDesc), len(file_user_group_proto_rawDesc)))
	})
	return file_user_group_proto_rawDescData
}

var file_user_group_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_group_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_user_group_proto_goTypes = []any{
	(UserGroupRelationship)(0),       // 0: UserGroupRelationship
	(*UserGroupDB)(nil),              // 1: UserGroupDB
	(*UserGroupInfo)(nil),            // 2: UserGroupInfo
	(*UserGroupInfoList)(nil),        // 3: UserGroupInfoList
	(*UserGroup)(nil),                // 4: UserGroup
	(*UserGroupJoinSummaryInfo)(nil), // 5: UserGroupJoinSummaryInfo
	(*UserGroupJoinRequestDB)(nil),   // 6: UserGroupJoinRequestDB
	(*UserGroupList)(nil),            // 7: UserGroupList
	(*UserInfo)(nil),                 // 8: UserInfo
}
var file_user_group_proto_depIdxs = []int32{
	7,  // 0: UserGroupDB.viewers:type_name -> UserGroupList
	7,  // 1: UserGroupDB.members:type_name -> UserGroupList
	0,  // 2: UserGroupInfo.relationshipToUser:type_name -> UserGroupRelationship
	8,  // 3: UserGroupInfoList.users:type_name -> UserInfo
	2,  // 4: UserGroupInfoList.groups:type_name -> UserGroupInfo
	2,  // 5: UserGroup.info:type_name -> UserGroupInfo
	3,  // 6: UserGroup.viewers:type_name -> UserGroupInfoList
	3,  // 7: UserGroup.members:type_name -> UserGroupInfoList
	8,  // 8: UserGroup.adminUsers:type_name -> UserInfo
	8,  // 9: UserGroupJoinSummaryInfo.administrators:type_name -> UserInfo
	8,  // 10: UserGroupJoinRequestDB.details:type_name -> UserInfo
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_user_group_proto_init() }
func file_user_group_proto_init() {
	if File_user_group_proto != nil {
		return
	}
	file_ownership_access_proto_init()
	file_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_group_proto_rawDesc), len(file_user_group_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_group_proto_goTypes,
		DependencyIndexes: file_user_group_proto_depIdxs,
		EnumInfos:         file_user_group_proto_enumTypes,
		MessageInfos:      file_user_group_proto_msgTypes,
	}.Build()
	File_user_group_proto = out.File
	file_user_group_proto_goTypes = nil
	file_user_group_proto_depIdxs = nil
}
