// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: user-group-management-msgs.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// //////////////////////////////////////////////////////////////
// Creating, deleting and renaming entire groups
// Should only be accessible to sys admins
// requires(PIXLISE_ADMIN)
type UserGroupCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Joinable      bool                   `protobuf:"varint,3,opt,name=joinable,proto3" json:"joinable,omitempty"`
	DefaultRoles  []string               `protobuf:"bytes,4,rep,name=defaultRoles,proto3" json:"defaultRoles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGroupCreateReq) Reset() {
	*x = UserGroupCreateReq{}
	mi := &file_user_group_management_msgs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGroupCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroupCreateReq) ProtoMessage() {}

func (x *UserGroupCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_group_management_msgs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroupCreateReq.ProtoReflect.Descriptor instead.
func (*UserGroupCreateReq) Descriptor() ([]byte, []int) {
	return file_user_group_management_msgs_proto_rawDescGZIP(), []int{0}
}

func (x *UserGroupCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserGroupCreateReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UserGroupCreateReq) GetJoinable() bool {
	if x != nil {
		return x.Joinable
	}
	return false
}

func (x *UserGroupCreateReq) GetDefaultRoles() []string {
	if x != nil {
		return x.DefaultRoles
	}
	return nil
}

type UserGroupCreateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *UserGroup             `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGroupCreateResp) Reset() {
	*x = UserGroupCreateResp{}
	mi := &file_user_group_management_msgs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGroupCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroupCreateResp) ProtoMessage() {}

func (x *UserGroupCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_group_management_msgs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroupCreateResp.ProtoReflect.Descriptor instead.
func (*UserGroupCreateResp) Descriptor() ([]byte, []int) {
	return file_user_group_management_msgs_proto_rawDescGZIP(), []int{1}
}

func (x *UserGroupCreateResp) GetGroup() *UserGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

// requires(PIXLISE_ADMIN)
type UserGroupDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGroupDeleteReq) Reset() {
	*x = UserGroupDeleteReq{}
	mi := &file_user_group_management_msgs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGroupDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroupDeleteReq) ProtoMessage() {}

func (x *UserGroupDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_group_management_msgs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroupDeleteReq.ProtoReflect.Descriptor instead.
func (*UserGroupDeleteReq) Descriptor() ([]byte, []int) {
	return file_user_group_management_msgs_proto_rawDescGZIP(), []int{2}
}

func (x *UserGroupDeleteReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type UserGroupDeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGroupDeleteResp) Reset() {
	*x = UserGroupDeleteResp{}
	mi := &file_user_group_management_msgs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGroupDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroupDeleteResp) ProtoMessage() {}

func (x *UserGroupDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_group_management_msgs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroupDeleteResp.ProtoReflect.Descriptor instead.
func (*UserGroupDeleteResp) Descriptor() ([]byte, []int) {
	return file_user_group_management_msgs_proto_rawDescGZIP(), []int{3}
}

// requires(PIXLISE_ADMIN)
type UserGroupEditDetailsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Joinable      bool                   `protobuf:"varint,4,opt,name=joinable,proto3" json:"joinable,omitempty"`
	DefaultRoles  []string               `protobuf:"bytes,5,rep,name=defaultRoles,proto3" json:"defaultRoles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGroupEditDetailsReq) Reset() {
	*x = UserGroupEditDetailsReq{}
	mi := &file_user_group_management_msgs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGroupEditDetailsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroupEditDetailsReq) ProtoMessage() {}

func (x *UserGroupEditDetailsReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_group_management_msgs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroupEditDetailsReq.ProtoReflect.Descriptor instead.
func (*UserGroupEditDetailsReq) Descriptor() ([]byte, []int) {
	return file_user_group_management_msgs_proto_rawDescGZIP(), []int{4}
}

func (x *UserGroupEditDetailsReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UserGroupEditDetailsReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserGroupEditDetailsReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UserGroupEditDetailsReq) GetJoinable() bool {
	if x != nil {
		return x.Joinable
	}
	return false
}

func (x *UserGroupEditDetailsReq) GetDefaultRoles() []string {
	if x != nil {
		return x.DefaultRoles
	}
	return nil
}

// requires(PIXLISE_ADMIN)
type UserGroupEditDetailsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *UserGroup             `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGroupEditDetailsResp) Reset() {
	*x = UserGroupEditDetailsResp{}
	mi := &file_user_group_management_msgs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGroupEditDetailsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroupEditDetailsResp) ProtoMessage() {}

func (x *UserGroupEditDetailsResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_group_management_msgs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroupEditDetailsResp.ProtoReflect.Descriptor instead.
func (*UserGroupEditDetailsResp) Descriptor() ([]byte, []int) {
	return file_user_group_management_msgs_proto_rawDescGZIP(), []int{5}
}

func (x *UserGroupEditDetailsResp) GetGroup() *UserGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

var File_user_group_management_msgs_proto protoreflect.FileDescriptor

const file_user_group_management_msgs_proto_rawDesc = "" +
	"\n" +
	" user-group-management-msgs.proto\x1a\x10user-group.proto\"\x8a\x01\n" +
	"\x12UserGroupCreateReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bjoinable\x18\x03 \x01(\bR\bjoinable\x12\"\n" +
	"\fdefaultRoles\x18\x04 \x03(\tR\fdefaultRoles\"7\n" +
	"\x13UserGroupCreateResp\x12 \n" +
	"\x05group\x18\x01 \x01(\v2\n" +
	".UserGroupR\x05group\".\n" +
	"\x12UserGroupDeleteReq\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId\"\x15\n" +
	"\x13UserGroupDeleteResp\"\xa9\x01\n" +
	"\x17UserGroupEditDetailsReq\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bjoinable\x18\x04 \x01(\bR\bjoinable\x12\"\n" +
	"\fdefaultRoles\x18\x05 \x03(\tR\fdefaultRoles\"<\n" +
	"\x18UserGroupEditDetailsResp\x12 \n" +
	"\x05group\x18\x01 \x01(\v2\n" +
	".UserGroupR\x05groupB\n" +
	"Z\b.;protosb\x06proto3"

var (
	file_user_group_management_msgs_proto_rawDescOnce sync.Once
	file_user_group_management_msgs_proto_rawDescData []byte
)

func file_user_group_management_msgs_proto_rawDescGZIP() []byte {
	file_user_group_management_msgs_proto_rawDescOnce.Do(func() {
		file_user_group_management_msgs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_group_management_msgs_proto_rawDesc), len(file_user_group_management_msgs_proto_rawDesc)))
	})
	return file_user_group_management_msgs_proto_rawDescData
}

var file_user_group_management_msgs_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_user_group_management_msgs_proto_goTypes = []any{
	(*UserGroupCreateReq)(nil),       // 0: UserGroupCreateReq
	(*UserGroupCreateResp)(nil),      // 1: UserGroupCreateResp
	(*UserGroupDeleteReq)(nil),       // 2: UserGroupDeleteReq
	(*UserGroupDeleteResp)(nil),      // 3: UserGroupDeleteResp
	(*UserGroupEditDetailsReq)(nil),  // 4: UserGroupEditDetailsReq
	(*UserGroupEditDetailsResp)(nil), // 5: UserGroupEditDetailsResp
	(*UserGroup)(nil),                // 6: UserGroup
}
var file_user_group_management_msgs_proto_depIdxs = []int32{
	6, // 0: UserGroupCreateResp.group:type_name -> UserGroup
	6, // 1: UserGroupEditDetailsResp.group:type_name -> UserGroup
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_group_management_msgs_proto_init() }
func file_user_group_management_msgs_proto_init() {
	if File_user_group_management_msgs_proto != nil {
		return
	}
	file_user_group_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_group_management_msgs_proto_rawDesc), len(file_user_group_management_msgs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_group_management_msgs_proto_goTypes,
		DependencyIndexes: file_user_group_management_msgs_proto_depIdxs,
		MessageInfos:      file_user_group_management_msgs_proto_msgTypes,
	}.Build()
	File_user_group_management_msgs_proto = out.File
	file_user_group_management_msgs_proto_goTypes = nil
	file_user_group_management_msgs_proto_depIdxs = nil
}
