// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: widget-data-msgs.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// requires(NONE)
type WidgetDataGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *WidgetDataGetReq) Reset() {
	*x = WidgetDataGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_data_msgs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WidgetDataGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetDataGetReq) ProtoMessage() {}

func (x *WidgetDataGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_widget_data_msgs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetDataGetReq.ProtoReflect.Descriptor instead.
func (*WidgetDataGetReq) Descriptor() ([]byte, []int) {
	return file_widget_data_msgs_proto_rawDescGZIP(), []int{0}
}

func (x *WidgetDataGetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WidgetDataGetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WidgetData *WidgetData `protobuf:"bytes,1,opt,name=widgetData,proto3" json:"widgetData,omitempty"`
}

func (x *WidgetDataGetResp) Reset() {
	*x = WidgetDataGetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_data_msgs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WidgetDataGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetDataGetResp) ProtoMessage() {}

func (x *WidgetDataGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_widget_data_msgs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetDataGetResp.ProtoReflect.Descriptor instead.
func (*WidgetDataGetResp) Descriptor() ([]byte, []int) {
	return file_widget_data_msgs_proto_rawDescGZIP(), []int{1}
}

func (x *WidgetDataGetResp) GetWidgetData() *WidgetData {
	if x != nil {
		return x.WidgetData
	}
	return nil
}

// requires(EDIT_VIEW_STATE)
type WidgetDataWriteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WidgetData *WidgetData `protobuf:"bytes,1,opt,name=widgetData,proto3" json:"widgetData,omitempty"`
}

func (x *WidgetDataWriteReq) Reset() {
	*x = WidgetDataWriteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_data_msgs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WidgetDataWriteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetDataWriteReq) ProtoMessage() {}

func (x *WidgetDataWriteReq) ProtoReflect() protoreflect.Message {
	mi := &file_widget_data_msgs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetDataWriteReq.ProtoReflect.Descriptor instead.
func (*WidgetDataWriteReq) Descriptor() ([]byte, []int) {
	return file_widget_data_msgs_proto_rawDescGZIP(), []int{2}
}

func (x *WidgetDataWriteReq) GetWidgetData() *WidgetData {
	if x != nil {
		return x.WidgetData
	}
	return nil
}

type WidgetDataWriteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WidgetData *WidgetData `protobuf:"bytes,1,opt,name=widgetData,proto3" json:"widgetData,omitempty"`
}

func (x *WidgetDataWriteResp) Reset() {
	*x = WidgetDataWriteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_data_msgs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WidgetDataWriteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetDataWriteResp) ProtoMessage() {}

func (x *WidgetDataWriteResp) ProtoReflect() protoreflect.Message {
	mi := &file_widget_data_msgs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetDataWriteResp.ProtoReflect.Descriptor instead.
func (*WidgetDataWriteResp) Descriptor() ([]byte, []int) {
	return file_widget_data_msgs_proto_rawDescGZIP(), []int{3}
}

func (x *WidgetDataWriteResp) GetWidgetData() *WidgetData {
	if x != nil {
		return x.WidgetData
	}
	return nil
}

// requires(NONE)
type WidgetMetadataGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *WidgetMetadataGetReq) Reset() {
	*x = WidgetMetadataGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_data_msgs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WidgetMetadataGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetMetadataGetReq) ProtoMessage() {}

func (x *WidgetMetadataGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_widget_data_msgs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetMetadataGetReq.ProtoReflect.Descriptor instead.
func (*WidgetMetadataGetReq) Descriptor() ([]byte, []int) {
	return file_widget_data_msgs_proto_rawDescGZIP(), []int{4}
}

func (x *WidgetMetadataGetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WidgetMetadataGetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WidgetName        string `protobuf:"bytes,2,opt,name=widgetName,proto3" json:"widgetName,omitempty"`
	WidgetDescription string `protobuf:"bytes,3,opt,name=widgetDescription,proto3" json:"widgetDescription,omitempty"`
}

func (x *WidgetMetadataGetResp) Reset() {
	*x = WidgetMetadataGetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_data_msgs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WidgetMetadataGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetMetadataGetResp) ProtoMessage() {}

func (x *WidgetMetadataGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_widget_data_msgs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetMetadataGetResp.ProtoReflect.Descriptor instead.
func (*WidgetMetadataGetResp) Descriptor() ([]byte, []int) {
	return file_widget_data_msgs_proto_rawDescGZIP(), []int{5}
}

func (x *WidgetMetadataGetResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WidgetMetadataGetResp) GetWidgetName() string {
	if x != nil {
		return x.WidgetName
	}
	return ""
}

func (x *WidgetMetadataGetResp) GetWidgetDescription() string {
	if x != nil {
		return x.WidgetDescription
	}
	return ""
}

// requires(EDIT_VIEW_STATE)
type WidgetMetadataWriteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WidgetName        string `protobuf:"bytes,2,opt,name=widgetName,proto3" json:"widgetName,omitempty"`
	WidgetDescription string `protobuf:"bytes,3,opt,name=widgetDescription,proto3" json:"widgetDescription,omitempty"`
}

func (x *WidgetMetadataWriteReq) Reset() {
	*x = WidgetMetadataWriteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_data_msgs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WidgetMetadataWriteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetMetadataWriteReq) ProtoMessage() {}

func (x *WidgetMetadataWriteReq) ProtoReflect() protoreflect.Message {
	mi := &file_widget_data_msgs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetMetadataWriteReq.ProtoReflect.Descriptor instead.
func (*WidgetMetadataWriteReq) Descriptor() ([]byte, []int) {
	return file_widget_data_msgs_proto_rawDescGZIP(), []int{6}
}

func (x *WidgetMetadataWriteReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WidgetMetadataWriteReq) GetWidgetName() string {
	if x != nil {
		return x.WidgetName
	}
	return ""
}

func (x *WidgetMetadataWriteReq) GetWidgetDescription() string {
	if x != nil {
		return x.WidgetDescription
	}
	return ""
}

type WidgetMetadataWriteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WidgetName        string `protobuf:"bytes,2,opt,name=widgetName,proto3" json:"widgetName,omitempty"`
	WidgetDescription string `protobuf:"bytes,3,opt,name=widgetDescription,proto3" json:"widgetDescription,omitempty"`
}

func (x *WidgetMetadataWriteResp) Reset() {
	*x = WidgetMetadataWriteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_data_msgs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WidgetMetadataWriteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetMetadataWriteResp) ProtoMessage() {}

func (x *WidgetMetadataWriteResp) ProtoReflect() protoreflect.Message {
	mi := &file_widget_data_msgs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetMetadataWriteResp.ProtoReflect.Descriptor instead.
func (*WidgetMetadataWriteResp) Descriptor() ([]byte, []int) {
	return file_widget_data_msgs_proto_rawDescGZIP(), []int{7}
}

func (x *WidgetMetadataWriteResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WidgetMetadataWriteResp) GetWidgetName() string {
	if x != nil {
		return x.WidgetName
	}
	return ""
}

func (x *WidgetMetadataWriteResp) GetWidgetDescription() string {
	if x != nil {
		return x.WidgetDescription
	}
	return ""
}

var File_widget_data_msgs_proto protoreflect.FileDescriptor

var file_widget_data_msgs_proto_rawDesc = []byte{
	0x0a, 0x16, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x2d, 0x6d, 0x73,
	0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74,
	0x2d, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x10, 0x57,
	0x69, 0x64, 0x67, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x40, 0x0a, 0x11, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x2b, 0x0a, 0x0a, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x41, 0x0a, 0x12, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x0a, 0x77, 0x69, 0x64, 0x67, 0x65,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x57, 0x69,
	0x64, 0x67, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x42, 0x0a, 0x13, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2b, 0x0a, 0x0a, 0x77,
	0x69, 0x64, 0x67, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x77, 0x69,
	0x64, 0x67, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22, 0x26, 0x0a, 0x14, 0x57, 0x69, 0x64, 0x67,
	0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x75, 0x0a, 0x15, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x77, 0x69, 0x64,
	0x67, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77,
	0x69, 0x64, 0x67, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x77, 0x69, 0x64,
	0x67, 0x65, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x76, 0x0a, 0x16, 0x57, 0x69, 0x64, 0x67, 0x65,
	0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x2c, 0x0a, 0x11, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x77, 0x69,
	0x64, 0x67, 0x65, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x77, 0x0a, 0x17, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x77, 0x69,
	0x64, 0x67, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x77, 0x69,
	0x64, 0x67, 0x65, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_widget_data_msgs_proto_rawDescOnce sync.Once
	file_widget_data_msgs_proto_rawDescData = file_widget_data_msgs_proto_rawDesc
)

func file_widget_data_msgs_proto_rawDescGZIP() []byte {
	file_widget_data_msgs_proto_rawDescOnce.Do(func() {
		file_widget_data_msgs_proto_rawDescData = protoimpl.X.CompressGZIP(file_widget_data_msgs_proto_rawDescData)
	})
	return file_widget_data_msgs_proto_rawDescData
}

var file_widget_data_msgs_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_widget_data_msgs_proto_goTypes = []interface{}{
	(*WidgetDataGetReq)(nil),        // 0: WidgetDataGetReq
	(*WidgetDataGetResp)(nil),       // 1: WidgetDataGetResp
	(*WidgetDataWriteReq)(nil),      // 2: WidgetDataWriteReq
	(*WidgetDataWriteResp)(nil),     // 3: WidgetDataWriteResp
	(*WidgetMetadataGetReq)(nil),    // 4: WidgetMetadataGetReq
	(*WidgetMetadataGetResp)(nil),   // 5: WidgetMetadataGetResp
	(*WidgetMetadataWriteReq)(nil),  // 6: WidgetMetadataWriteReq
	(*WidgetMetadataWriteResp)(nil), // 7: WidgetMetadataWriteResp
	(*WidgetData)(nil),              // 8: WidgetData
}
var file_widget_data_msgs_proto_depIdxs = []int32{
	8, // 0: WidgetDataGetResp.widgetData:type_name -> WidgetData
	8, // 1: WidgetDataWriteReq.widgetData:type_name -> WidgetData
	8, // 2: WidgetDataWriteResp.widgetData:type_name -> WidgetData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_widget_data_msgs_proto_init() }
func file_widget_data_msgs_proto_init() {
	if File_widget_data_msgs_proto != nil {
		return
	}
	file_widget_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_widget_data_msgs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WidgetDataGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_data_msgs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WidgetDataGetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_data_msgs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WidgetDataWriteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_data_msgs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WidgetDataWriteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_data_msgs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WidgetMetadataGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_data_msgs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WidgetMetadataGetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_data_msgs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WidgetMetadataWriteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_data_msgs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WidgetMetadataWriteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_widget_data_msgs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_widget_data_msgs_proto_goTypes,
		DependencyIndexes: file_widget_data_msgs_proto_depIdxs,
		MessageInfos:      file_widget_data_msgs_proto_msgTypes,
	}.Build()
	File_widget_data_msgs_proto = out.File
	file_widget_data_msgs_proto_rawDesc = nil
	file_widget_data_msgs_proto_goTypes = nil
	file_widget_data_msgs_proto_depIdxs = nil
}
