apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pixlise-core-data-import
  description: |
    The data import core packages repo for the pixlise application.
  links:
    - title: Website
      url: https://pixlise.org
    - title: Documentation
      url: https://pixlise.gitbook.io/
  annotations:
    github.com/project-slug: pixlise/core/data-import
    backstage.io/techdocs-ref: dir:.
spec:
  type: library
  owner: default/developers
  lifecycle: production
  dependencyOf:
    - component:data-import
  dependsOn::
    - component:pixlise-core-packagess
