name: Core Development

on:
  push:
    branches:
      - development
  workflow_dispatch:
    inputs:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE_24: true

jobs:
  prerelease:
    uses: ./.github/workflows/main.yml
    with:
      version_format: '${major}.${minor}.${patch}-prerelease.${increment}'
    secrets: inherit
