name: Core Release

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    uses: ./.github/workflows/main.yml
    with:
      version_format: '${major}.${minor}.${patch}'
    secrets: inherit
