name: Core Staging

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: ['main']
  workflow_dispatch:
    inputs:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  staging:
    uses: ./.github/workflows/main.yml
    with:
      version_format: '${major}.${minor}.${patch}-RC${increment}'
    secrets: inherit
